### ISSUE TITLE
I think there is something wrong with the instructions

### ISSUE THREAD

**Issue by thelinuxlich** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#1]
I follow all steps and when I test the config I get "nginx: [emerg] unknown limit_req_zone "bot2_reqlimitip" in /etc/nginx/blockbots.conf:15"

**Comment by thelinuxlich** [comment]
Nevermind, I was adding the globalblacklist.conf after blockbots.conf

**Comment by mitchellkrogza** [comment]
Glad you got it figured out. Please do report back on how it's working for you.

**Comment by mitchellkrogza** [comment]
Readme instructions have been updated to mention that includes must be added within a server {} block
