### ISSUE TITLE
Blacklist domain?

### ISSUE THREAD

**Issue by flooreeda** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#100]
Is it possible to blacklist a domain? I don't see a **blacklist-domains.conf** file.
```
/etc/nginx/bots.d/whitelist-ips.conf
/etc/nginx/bots.d/whitelist-domains.conf
/etc/nginx/bots.d/blacklist-user-agents.conf
/etc/nginx/bots.d/blacklist-ips.conf
/etc/nginx/bots.d/bad-referrer-words.conf
/etc/nginx/bots.d/custom-bad-referrers.conf
```

**Comment by mitchellkrogza** [comment]
Hi @floreeda blacklisting of domains is done through the /etc/nginx/bots.d/custom-bad-referrers.confirst file.

**Comment by mitchellkrogza** [comment]
I have been meaning to add a blacklist-domains.conf include file which will clear confusion for future users so it's in the pipeline.

**Comment by mitchellkrogza** [comment]
New include file introduced in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/0a5376547ca03ef9a756324cbad4698c254e6f4c and https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/4343b7d01535334e05f4bb84717ced56d3dc62df feature not in operation yet in the globalblacklist.conf file but will be added shortly once tested.

**Comment by mitchellkrogza** [comment]
@itoffshore tested and update-ngblocker beautifully finds the new include and downloads it 👍 Will introduce the new include tomorrow after I have tested it 100% to make sure.

**Comment by flooreeda** [comment]
Great, thanks @mitchellkrogza!
