### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by nginxfz** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#103]
hi

My system environment is centos7 64 bit

I installed version 1.10.2 of nginx.

Currently installed in bad robots blocker,

When i went to the 4 step，Prompt the error message when I execute the command：

`cd /usr/sbin/
sudo ./setup-ngxblocker`

`Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt
find: ‘/etc/nginx/sites-available’: No such file or directory
no vhost files in: /etc/nginx/sites-available/*.vhost => exiting.
`
I have searched all .vhost files

But nothing was found

How do i install it?

thanks！

**Comment by mitchellkrogza** [comment]
Hi @nginxfz where have you setup your vhosts? And please explain more about _**"Currently installed in bad robots blocker"**_

**Comment by nginxfz** [comment]
hello

My Nginx install dir:  /usr/local/nginx

My website root dir : /data/www 

(/data/www/index.php)

I have nginx conf file

But did not find vhost files

thanks

**Comment by mitchellkrogza** [comment]
Can you either post your nginx.conf or look inside it if your vhosts have been configured inside nginx.conf ?? You will see 

```
server {
	listen *:80;
    listen [::]:80;  
```

**Comment by nginxfz** [comment]
Yes

My conf is included
```

server {
  listen 80;
  server_name
  access_log off;
  index index.html index.htm index.php;
  root /data/www/;
```

and also i used SSL
`    listen 443 ssl http2;
ssl on;
`
thanks

**Comment by mitchellkrogza** [comment]
Ok that explains why you have no vhosts in `/usr/local/nginx/sites-available` or `/etc/nginx/sites-available` you have 2 options, add the includes yourself into each vhost in nginx.conf or make each of those config's inside nginx.conf proper .vhost files in in `/usr/local/nginx/sites-available` or `/etc/nginx/sites-available`

To add the includes just add the following into each `server { }` section inside nginx.conf

```
	# Block Bad Bots
	include /etc/nginx/bots.d/blockbots.conf;
	include /etc/nginx/bots.d/ddos.conf;
```

But you should actually take the time and move each vhost out of nginx.conf into `sites-available` and link them into nginx using the `ln -s` method.

**Comment by mitchellkrogza** [comment]
So you would add it like this

```
server {
  listen 80;
  server_name
  access_log off;
  index index.html index.htm index.php;
  root /data/www/;
	# Block Bad Bots
	include /etc/nginx/bots.d/blockbots.conf;
	include /etc/nginx/bots.d/ddos.conf;
```

**Comment by nginxfz** [comment]
I added it to .conf file in conf.d
---
server {
  listen 80;
  server_name
  access_log off;
  index index.html index.htm index.php;
  root /data/www/;
	# Block Bad Bots
	include /etc/nginx/bots.d/blockbots.conf;
	include /etc/nginx/bots.d/ddos.conf;


----

service nginx restart

Could not start nginx

Will this page be able to achieve it?

https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-on-centos-7


thanks！

**Comment by nginxfz** [comment]
There are currently no * .vhost files

Is it possible to create this file?

**Comment by mitchellkrogza** [comment]
Where did you put the bots.d folder ? and where did you put the contents of conf.d from this repo ?

**Comment by mitchellkrogza** [comment]
You can email me your full nginx.conf file (do not take out domain names or anything) to mitchellkrog@gmail.com and I will email you back how to modify it properly.

**Comment by nginxfz** [comment]
bots.d file in / etc / nginx /


![image](https://user-images.githubusercontent.com/32761727/31537344-594deab4-b034-11e7-9ebc-268d1476ee98.png)


![image](https://user-images.githubusercontent.com/32761727/31537374-7e83c5ce-b034-11e7-824b-a31ed85c2314.png)

**Comment by nginxfz** [comment]
[root@sv conf.d]# ls
botblocker-nginx-settings.conf  globalblacklist.conf


The globalblacklist.conf file is in /etc/nginx/conf.d

**Comment by mitchellkrogza** [comment]
So your .vhost files are actually .conf files so then you run setup as follows.

`sudo ./setup-ngxblocker -e conf`    <<< dry run

and then 

`sudo ./setup-ngxblocker -x -e conf`   <<< run setup

**Comment by nginxfz** [comment]
OK

thanks i will try it

**Comment by nginxfz** [comment]
` sudo nginx -t
nginx: [emerg] "server_names_hash_bucket_size" directive is not allowed here in /etc/nginx/conf.d/botblocker-nginx-settings.conf:14
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
`

**Comment by nginxfz** [comment]
OK will do

**Comment by nginxfz** [comment]
The Email has been sent

Please help me look at the reasons

Greatful thanks!

**Comment by mitchellkrogza** [comment]
Check your email, all I did was remove the includes you did at the very top of nginx.conf (canot add includes there. And I added the section

```
  # *************************************************************
  # Add the default nginx includes for conf.d and sites-available
  # *************************************************************
  	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
```

**Comment by nginxfz** [comment]
OK

Thank you very much!

**Comment by mitchellkrogza** [comment]
No problem at all .. is it all working now ?

**Comment by nginxfz** [comment]
[root@sv sbin]# sudo nginx -t
nginx: [emerg] "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/conf.d/botblocker-nginx-settings.conf:14
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed


It does not seem to solve........

**Comment by nginxfz** [comment]
![image](https://user-images.githubusercontent.com/32761727/31539317-d09d7764-b03a-11e7-97dd-8af8c52d9757.png)

**Comment by mitchellkrogza** [comment]
comment out line 17 of your nginx.conf

```
http {
  include mime.types;
  default_type application/octet-stream;
  #server_names_hash_bucket_size 128;
  client_header_buffer_size 32k;
  large_client_header_buffers 4 32k;
```

**Comment by mitchellkrogza** [comment]
@nginxfz did you get my email with new nginx.conf file ???

**Comment by nginxfz** [comment]
Yes i got it

I'll try again

thanks！

**Comment by nginxfz** [comment]
It`s working !!

awesome!Thanks!

One more ting..

How do i test bad UA and bad bots has been banned?

**Comment by mitchellkrogza** [comment]
:+1: that’s great. Send me your real domain name via email and I will test for you and show you how to test

**Comment by mitchellkrogza** [comment]
Or take the examples from step 10 of the instructions 

I ![2710eb83-4759-4f5b-8b7f-1260906b851d](https://user-images.githubusercontent.com/9961541/31555937-34013d24-b043-11e7-9fa7-db9f3e8c2a51.jpeg)

**Comment by nginxfz** [comment]
awesome! Thanks!

**Comment by mitchellkrogza** [comment]
Perfect, tested and working 100%
