### ISSUE TITLE
[emerg] unknown "bad_bot" variable nginx: configuration file /etc/nginx/nginx.conf test failed

### ISSUE THREAD

**Issue by kareti** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#104]
Hello,
when I tested nginx, I got this error 
nginx: [emerg] unknown "bad_bot" variable nginx: configuration file /etc/nginx/nginx.conf test failed 

I am using nginx 1.12.1 version

Please suggest. Thanks

**Comment by mitchellkrogza** [comment]
Hi @kareti did you use the install and setup script? Please can you post you /etc/nginx/nginx.conf file and also your vhost config file please.

**Comment by kareti** [comment]
Hi, I used the instructions on https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker
and installed using ssh

nginx.conf

`#   * Official English Documentation: http://nginx.org/en/docs/

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log;
#error_log  /var/log/nginx/error.log  notice;

pid        /var/run/nginx.pid;

############# events start ######
events 
{ 
worker_connections  8000;

# essential for linux, optmized to serve many clients with each thread
use epoll;

# Accept as many connections as possible, after nginx gets notification about a new connection. May flood worker_connections, if that option is set too low.
multi_accept on;

accept_mutex off;
}
############# events end #########

http {
ssl_session_cache shared:SSL:50m;
ssl_session_timeout 1d;
ssl_session_tickets on;

server_tokens off;


client_max_body_size 10m;
client_body_buffer_size 128k;
client_body_timeout 60;
#worker_rlimit_nofile 64000;
send_timeout 60;

 aio threads; 

index  index.php index.html index.htm;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  /var/log/nginx/access.log  main;
	access_log off;
	underscores_in_headers on;

sendfile  on;
sendfile_max_chunk 512k;

	
# Tcp_nopush causes nginx to attempt to send its HTTP response head in one packet, instead of using partial frames. This is useful for prepending headers before calling sendfile, or for throughput optimization.
tcp_nopush on;

# don't buffer data-sends (disable Nagle algorithm). Good for sending frequent small bursts of data in real time.
tcp_nodelay on;

keepalive_disable msie6;
keepalive_requests 500;
keepalive_timeout  60;
	fastcgi_read_timeout 1h;
	fastcgi_buffering off;

    gzip on;
gzip_comp_level 5;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/plain text/css application/javascript application/x-javascript text/javascript text/xml;
    gzip_vary on;

##########################
    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    # include /etc/nginx/conf.d/*.conf;
##########################

	
	server_names_hash_bucket_size 128;

    server {
        listen       X.X.X.X;
        server_name  localhost;
        root         /usr/share/nginx/html;

        #charset koi8-r;

        #access_log  /var/log/nginx/host.access.log  main;




      # deny access to .htaccess files, if Apache's document root concurs with nginx's one
	location ~ /\.ht { deny  all; }
	


	} # end server

		
include /etc/nginx/sites-available/*.conf;


} #end http
`

domain.com.conf

`server {
	listen X.X.X.X;
    server_name  www.domain.com;
    return 301 https://domain.com$request_uri;
}
server {
	listen X.X.X.X;
    server_name  domain.com;
    return 301 https://domain.com$request_uri;
}

server 
{
listen X.X.X.X:443 ssl;
server_name domain.com;
root /home/domain.com/public_html;

ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;
include /etc/nginx/common/ssl-params.conf;

error_log /var/opt/remi/php70/log/php-fpm/www-error.log crit;
access_log /var/log/virtualmin/domain.com_access_log;

# Bad Bot Blocker
include /etc/nginx/bots.d/ddos.conf;
include /etc/nginx/bots.d/blockbots.conf;


     if ($request_method !~ ^(GET|HEAD|POST)$ ) {
         return 444;
     }
	 

error_page  401      /401.php;
error_page  403      /403.php;
error_page  404      /404.php;
error_page  500      /500.php;
error_page  502      /500.php;


}
`

**Comment by mitchellkrogza** [comment]
@kareti first backup your existing nginx.conf `sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.bak`

Then make a new one `sudo nano /etc/nginx/nginx.conf` and paste the contents as below and then try `sudo nginx -t`

```
#   * Official English Documentation: http://nginx.org/en/docs/

user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log;
pid        /var/run/nginx.pid;

############# events start ######
events 
{ 
worker_connections  8000;
use epoll;
multi_accept on;
accept_mutex off;
}
############# events end #########

http 
{
ssl_session_cache shared:SSL:50m;
ssl_session_timeout 1d;
ssl_session_tickets on;

server_tokens off;


client_max_body_size 10m;
client_body_buffer_size 128k;
client_body_timeout 60;
#worker_rlimit_nofile 64000;
send_timeout 60;

 aio threads; 

index  index.php index.html index.htm;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  /var/log/nginx/access.log  main;
	access_log off;
	underscores_in_headers on;

sendfile  on;
sendfile_max_chunk 512k;

	
# Tcp_nopush causes nginx to attempt to send its HTTP response head in one packet, instead of using partial frames. This is useful for prepending headers before calling sendfile, or for throughput optimization.
tcp_nopush on;

# don't buffer data-sends (disable Nagle algorithm). Good for sending frequent small bursts of data in real time.
tcp_nodelay on;

keepalive_disable msie6;
keepalive_requests 500;
keepalive_timeout  60;
	fastcgi_read_timeout 1h;
	fastcgi_buffering off;

    gzip on;
    gzip_comp_level 5;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/plain text/css application/javascript application/x-javascript text/javascript text/xml;
    gzip_vary on;

##########################
    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    # include /etc/nginx/conf.d/*.conf;
##########################

	
include /etc/nginx/sites-available/*.conf;
include /etc/nginx/conf.d/*.conf;


} #end http
```

**Comment by mitchellkrogza** [comment]
I also suggest you specify the CA certificate with your SSL configuration in your vhost file like this

```
	# First include our certificates and chain of trust
	ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;
	## verify chain of trust of OCSP response using Root CA and Intermediate certs
	ssl_trusted_certificate /etc/letsencrypt/live/domain.com/chain.pem;

	# Now include our ssl params
        include /etc/nginx/common/ssl-params.conf;
```

**Comment by kareti** [comment]
Hi, Thanks a lot for your quick reply.
I will follow your suggestions and inform you soon.
Thanks

**Comment by kareti** [comment]
Thanks, problem solved.

**Comment by mitchellkrogza** [comment]
Excellent well done. Enjoy it and be sure to test using the examples on the front page Readme and keep a watch on your log files.
