### ISSUE TITLE
ltx71 

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#105]
ltx71 has been regarded as a bad bot for some time. I see a lot of it in my logs. A visit to their page says

```
LTX71

We continuously scan the internet for security research purposes. Our crawling is not malicious and only notes summary information for a page.

If you have further questions please contact research@ltx71.com
```

Does anyone know more about ltx71 ?

**Comment by mitchellkrogza** [comment]
@thezoggy what is your thoughts or input on this one?

**Comment by thezoggy** [comment]
I view all those webcrawler/scanners/etc as wasted resources. Blocking it wont block any legit traffic/negatively impact the user experience.

If a person wanted to opt-in to these type of 'research' crawlers, they could just whitelist or manually modify the exclusion.

**Comment by mitchellkrogza** [comment]
Thanks @thezoggy I feel the same and get thousands of requests a day from ltx71 so it shall remain blocked.
