### ISSUE TITLE
Random fake referrers

### ISSUE THREAD

**Issue by TheShrike** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#106]
I am getting lots of requests with random fake referrers, do you have suggestions on how to block them?

Here is an example from the access log:

- 145.239.62.130 200 14758 "https://www.vccircle.com/tag/driven/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"
- 79.137.116.213 200 14720 "https://cdn-png2.theactivetimes.com/sites/default/files/styles/3_2_thumbnail/public/thermarest_neoair_xtherm2_p.png?itok=jYkx5DRm" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"
- 188.165.164.21 200 14699 "https://viltsunruoka.vuodatus.net/lue/2011/12/neljas-adventti" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"
- 92.222.81.228  200 14758 "https://www.uvinum.co.uk/beer:b:blonde-beer:n:spain" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"
- 178.33.200.186 200 14760 "https://www.art.ulaval.ca/a-propos/actualites.html/page/17/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"
- 79.137.116.222 200 14750 "https://pt.industries.ul.com/knowledge-solutions/industry-and-product-education" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"
- 37.187.181.156 200 14747 "https://www.moneywise.co.uk/sites/default/files/styles/thumbnail/public/images/articles/waitingfortrain.jpg?itok=4ZNcTL_U" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"

**Comment by mitchellkrogza** [comment]
Thanks @TheShrike you can add those to the file custom-bad-referrers.conf unfortumately it's very easy to fake referrers so your best bet is to monitor your logs for a day or two and see any repeating IP's and block them in blacklist-ips.conf

**Comment by mitchellkrogza** [comment]
@TheShrike blocking `Chrome/50` would not be advisable as they may still be many people using it.

You can block very old versions like `Chrome/14`, `Chrome/15` for example but with the latest being `Chrome/61` I would say anything from 50 > 61 is still actively in use by valid users, not everyone upgrades.
