### ISSUE TITLE
Duplicate directive

### ISSUE THREAD

**Issue by julianrichie** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#107]
found some duplicate directive warning[emerg] when running nginx -t

<img width="682" alt="screen shot 2017-11-01 at 08 50 07" src="https://user-images.githubusercontent.com/1916616/32256470-d1e006c2-bee1-11e7-915d-c543ce916840.png">
<img width="709" alt="screen shot 2017-11-01 at 08 50 19" src="https://user-images.githubusercontent.com/1916616/32256482-e086d430-bee1-11e7-90f3-76f75bcfa783.png">

**Comment by mitchellkrogza** [comment]
Please post your contents of nginx.conf you have a duplicate Include.

**Comment by mitchellkrogza** [comment]
@julianrichie please post your contents of nginx.conf so that I can assist you.

**Comment by mitchellkrogza** [comment]
Closed due to inactivity.
