### ISSUE TITLE
Invalid network

### ISSUE THREAD

**Issue by stefanobaldo** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#108]
nginx: [emerg] invalid network "2001:4860:4000::/36" in /etc/nginx/conf.d/globalblacklist.conf:6851
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by mitchellkrogza** [comment]
Hi @stefanobaldo please post the output of “sudo nginx-V” it seems you are missing the ipv6 module for Nginx

**Comment by stefanobaldo** [comment]
nginx version: openresty/1.11.2.2
built by gcc 4.9.2 (Debian 4.9.2-10)
built with OpenSSL 1.0.1t  3 May 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.60 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.06 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.7 --add-module=../ngx_lua_upstream-0.06 --add-module=../headers-more-nginx-module-0.32 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.17 --add-module=../redis2-nginx-module-0.13 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-http_ssl_module

**Comment by stefanobaldo** [comment]
That's right, I have no ipv6 support. I will try recompiling nginx.

**Comment by stefanobaldo** [comment]
It worked, thank you. Closing.

**Comment by mitchellkrogza** [comment]
Great Stefano glad you got it fixed.
