### ISSUE TITLE
Wrong domains in google-disavow.txt

### ISSUE THREAD

**Issue by elaur** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#11]
L132 domain:addons.mozilla.org/en-us/firefox/addon/ilovevitaly
L1026 domain:eaplay.ru/a00af605

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/854c6efc3413a853461a585427106dd56d22b9ef

**Comment by mitchellkrogza** [comment]
"~*ilovevitaly" already covered on line 775
eaplay.ru fixed.
