### ISSUE TITLE
Whitelist IP not working

### ISSUE THREAD

**Issue by Elfen-Service** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#112]
Hello,

the whitelisting for a specific ip is not working.
We have an external system which uses the user-agent "Mozilla/4.0 (compatible; MSIE 6.0; MS Web Services Client Protocol 2.0.50727.8762)".
I think this is blocked by line 464 in conf.d/globalblacklist.conf as i checked the returncode in line 41 of bots.d/blockbots.conf .
I added the ip in the same format as line 28 in bots.d/whitelist-ips.conf .
Even replacing 111.111.111.111 in the original version does not work.
The vHost includes bots.d/blockbots.conf and bots.d/ddos.conf .

**Comment by mitchellkrogza** [comment]
Hi @Elfen-Service yes it's being blocked by "MS Web Services Client Protocol". Can you try placing the following in your blacklist-user-agents.conf file and then reload nginx and test again.

```"~*\bMS\ Web\ Services\ Client\ Protocol\b"        0;```

**Comment by Elfen-Service** [comment]
Hi,
thank you for the fast reply.
This seems to work.
But IP would be better than allowing all bots using this agent. :(

**Comment by mitchellkrogza** [comment]
Thanks @Elfen-Service I will have a look why the IP whitelist is not respecting the rules.

**Comment by mitchellkrogza** [comment]
Can you try whitelisting the full user agent string in blacklist-user-agents.conf

`"Mozilla/4\.0 (compatible; MSIE\ 6\.0; MS\ Web\ Services\ Client\ Protocol\ 2\.0\.50727\.8762"     0;`

**Comment by Elfen-Service** [comment]
I already tried 
`"~*\bMS\ Web\ Services\ Client\ Protocol 2.0.50727.8762\b" 0; `
to be more specific.
This worked.

Will try the full one in a few minutes...

**Comment by Elfen-Service** [comment]
Nov 20 14:57:12 magento nginx[25693]: nginx: [emerg] could not build map_hash, you should increase map_hash_bucket_size: 64

**Comment by Elfen-Service** [comment]
After increasing map_hash_bucket_size the full string does not work

**Comment by mitchellkrogza** [comment]
That is very strange 🤔  I don't even specify map_has_bucket_size in my nginx.conf I only use the following:

```	types_hash_max_size 2048;
	large_client_header_buffers 4 16k;
	variables_hash_max_size 2048;
	variables_hash_bucket_size 1024;
```

and then also the settings from the botblocker-nginx-settings.conf file

```
server_names_hash_bucket_size 128;
server_names_hash_max_size 4096;
```

**Comment by Elfen-Service** [comment]
We use
`large_client_header_buffers 64 8k;`
and the standard for 
`variables_hash_max_size
variables_hash_bucket_size `

I will give your values a try, but these should not be the problem.

**Comment by mitchellkrogza** [comment]
Never seen this error before I will have to test with the full user agent string to see if I can replictae that.

**Comment by mitchellkrogza** [comment]
If this is working `"~*\bMS\ Web\ Services\ Client\ Protocol 2.0.50727.8762\b" 0;` I would stick with that for now.

**Comment by Elfen-Service** [comment]
I saw now you forgot the ) at the end of the userstring.
I will give this a try and some other variations with escaping and so on.
If not i will stick with the working one as its more specific.

Would be great to get the whitelisting for ips working.
If i have time i will search for the problem, too.
Let me know if you need other infos.

Thank you.

**Comment by mitchellkrogza** [comment]
Thanks @Elfen-Service let me know if you find anything, I will have a look why the whitelisting is not kicking in, need some extra logic before the mapping of user-agents kicks in.
