### ISSUE TITLE
[Help] Nginx 1.4.6 [emerg] unknown limit_req_zone "bot2_reqlimitip" in /etc/nginx/bots.d/blockbots.conf:39

### ISSUE THREAD

**Issue by tttungs** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#113]
Hi,
I'm running : 

> nginx version: nginx/1.4.6 (Ubuntu)
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_spdy_module --with-http_sub_module --with-http_xslt_module --with-mail --with-mail_ssl_module

Follow instruction to install manual i got this error:

> $ nginx -t
> nginx: [emerg] unknown limit_req_zone "bot2_reqlimitip" in /etc/nginx/bots.d/blockbots.conf:39
> nginx: configuration file /etc/nginx/nginx.conf test failed

I tried on my local machine which have nginx version 1.13.6,  it work fine.
However I want to install on my delicate server so any suggest for 1.4.6 version please ?

Thanks

**Comment by mitchellkrogza** [comment]
Compare nginx -V on both versions and you will see what modules you are missing. I am not sure though if 1.4.x will work with the blocker, the blocker has only been designed and tested on 1.10.x > 1.13.x .... 1.4 is a very old version.
On 2017/12/14 02:30:49, zziz <notifications@github.com> wrote:
Hi,
I'm running :
nginx version: nginx/1.4.6 (Ubuntu)
built by gcc 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_spdy_module --with-http_sub_module --with-http_xslt_module --with-mail --with-mail_ssl_module
Follow intruction to install manual i got this error:
$ nginx -t
nginx: [emerg] unknown limit_req_zone "bot2_reqlimitip" in /etc/nginx/bots.d/blockbots.conf:39
nginx: configuration file /etc/nginx/nginx.conf test failed
I tried on my local machine which have nginx version 1.13.6, it work fine.
I want to install on my delicate server so any suggest for 1.4.6 version please ?
Thanks

**Comment by tttungs** [comment]
OK thanks ,  im going to upgrade nginx now.
