### ISSUE TITLE
Important: Big Error in latest globalblacklist.conf

### ISSUE THREAD

**Issue by Elfen-Service** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#115]
Line 215:
`"~*\b\b"                3;`

This results in blocking every call!

**Comment by mitchellkrogza** [comment]
Sincere Apologies @Elfen-Service (and everyone else) has been urgently fixed. Please pull latest update

**Comment by mitchellkrogza** [comment]
@Elfen-Service please pull V3.2017.12.1017 - something went very wrong on Travis pushing out the new build, I disabled some of the tests and V3.2017.12.1017 fixes the problem
