### ISSUE TITLE
Doesn't support unix aliases as emails

### ISSUE THREAD

**Issue by xcorat** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#116]
Wouldn't it be better if it doesn't check the email for `@` and `.`? I would like to use the update script like,
`update-ngxblocker -e webmaster` where sendmail will send the email and forward to proper recipients as set in `/etc/aliases`

**Comment by mitchellkrogza** [comment]
Hi @xcorat I will tag @itoffshore on this to see if he can work out a solution for that.

**Comment by itoffshore** [comment]
@xcorat - if you can confirm the changes in https://github.com/itoffshore/nginx-ultimate-bad-bot-blocker/commit/f40c3271c91bcf37fb2d94e7165eab4c7e49e3ba fix this issue I'll merge it.

**Comment by itoffshore** [comment]
@xcorat use `-m` not `-e` to send mail to a system alias

**Comment by xcorat** [comment]
Works! Thx :)
