### ISSUE TITLE
limit_req_log_level warn;

### ISSUE THREAD

**Issue by i300220** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#117]
Hello

I see this script has been updated tremendously since I added it first.

Congrats for that excellent work.

One question.  If i'd want to add the directive specified in the subject line, and would not want to be changed by the daily updates, where would I put it?

**Comment by mitchellkrogza** [comment]
Hi @i300220 so glad you are enjoying the benefist of the blocker and it sure has come a long way over 2017. I am sure it will grow rapidly in updates this year too.

You can add your required directive in the `botblocker-nginx-settings.conf` include file. 
That file does not get updated with the daily updates.

**Comment by i300220** [comment]
Awesome.  Thanks for your encouragements.

Did the job perfectly!
