### ISSUE TITLE
update failed.

### ISSUE THREAD

**Issue by i300220** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#120]
Strange.

I ran update-ngxblocker in my cron job at 21:07 and it reported something like that (I've deleted the original email, sorry for the lack of precision).

_nothing to do for bots.d/
nothing to do for conf.d/
reloading nginx:  failed._

However I've checked in conf.d and the file  globalblacklist.conf  was indeed updated to the time that the cron job ran at!

I've verified the differences with my old copy dated 2 days ago.

> 
> --- /usr/local/src/nginx-ultimate-bad-bot-blocker/conf.d/globalblacklist.conf   2018-01-05 08:40:00.278961125 -0700
> +++ globalblacklist.conf        2018-01-07 21:07:02.372609898 -0700
> @@ -4,9 +4,9 @@
> 
>  ### VERSION INFORMATION #
>  ###################################################
> -### Version: V3.2018.01.1022
> -### Updated: Fri Jan  5 14:00:24 SAST 2018
> -### Bad Referrer Count: 6101
> +### Version: V3.2018.01.1029
> +### Updated: Sun Jan  7 10:59:12 SAST 2018
> +### Bad Referrer Count: 6110
>  ### Bad Bot Count: 509
>  ###################################################
>  ### VERSION INFORMATION ##
> (...)

I've reloaded nginx manually and all went fine.

Also noticed that 2 of the /usr/sbin/ scripts were updated since yesterday so I've updated them manually afterwards (-s switch addition).

System is debian jessie 8.10.  Nginx is 1.12.2

**Comment by mitchellkrogza** [comment]
@i300220 please can you post the full error message so that myself and @itoffshore can look into this?

**Comment by i300220** [comment]
Gladly but need to wait until the next cron job with pending updates.

If my memory serves well, that's all that was in that email.  No specific error message, the globalblacklist.conf was updated, nginx configuration was not reloaded and the sbin scripts were not updated. Is there a way to increase verbosity, I don't know (bin/sh -x ?).

In the meantime I modified the root crontab, I don't think sbin dirs are part of the PATH in a debian system for obvious reasons: **7 21 * * * PATH=/sbin:/bin:/usr/sbin:/usr/bin /usr/sbin/update-ngxblocker -e me@email.com**

Running the update script manually works beautifully.  Only fails from the crontab.

Suggestion:  would it be possible to change _service nginx reload_ into _/usr/sbin/nginx -t && /usr/sbin/service nginx reload_ in your update script?  The system administrator might very well be working on the configuration while the cron job is being executed and the nginx config in an unknown state.

**Comment by itoffshore** [comment]
@i300220 usually the `nginx` init scripts run `nginx -t` (they do on Alpine Linux)

**Comment by i300220** [comment]
Not on debian.  Crash guaranteed if you run 'service nginx reload' without a valid 
configuration.  I did it a few times inadvertenly in the past.  Learned it the hard way.

Might be a flaw, but it bahaved that way last time I did it.  And you're due for 'killall nginx',
repair your configuration and start it again.  All that time the websites being down.

Or another suggestion,  add a switch to the update script to just notify us that updates are
available.  Can always perform a git pull afterwards or run the update script manually
whenever I see fit to effectively update everything in need of.

**Comment by itoffshore** [comment]
@i300220 you should change the reload line in the nginx service script:

```
[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t -q -g 'daemon on; master_process on;'
ExecStart=/usr/sbin/nginx -g 'daemon on; master_process on;'
ExecReload=/usr/sbin/nginx -g 'daemon on; master_process on;' -s reload
```
to

`
ExecReload=/usr/sbin/nginx -t -g 'daemon on; master_process on;' -s reload`

to just check the blacklist version without downloading anything:

`update-ngxblocker -vs`

**Comment by i300220** [comment]
Seems fixed by adding /usr/sbin to the PATH

 - PATH=/sbin:/bin:/usr/sbin:/usr/bin /usr/sbin/update-ngxblocker -e me@email.com

> 
> LOCAL Version: 3.2018.01.1029
> Updated: Sun Jan  7 10:59:12 SAST 2018
> 
> REMOTE Version: 3.2018.01.1035
> Updated: Thu Jan 11 16:18:51 SAST 2018
> 
> Update Available => 3.2018.01.1035
> 
> Downloading: globalblacklist.conf ...[OK]
> 
> Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt
> 
> Nothing to update for directory: /etc/nginx/conf.d
> Nothing to update for directory: /etc/nginx/bots.d
> Nothing to update for directory: /usr/sbin
> Setting mode: 700 => /usr/sbin/install-ngxblocker
> Setting mode: 700 => /usr/sbin/setup-ngxblocker
> Setting mode: 700 => /usr/sbin/update-ngxblocker
> 
> Reloading NGINX configuration...[OK]
> Emailing report to: me@myemail.com
> 
> 

Thanks guys for your assistance.

**Comment by mitchellkrogza** [comment]
Thanks for reporting back @i300220 glad you got it solved.

**Comment by ScrewLooseDan** [comment]
I had the same issue (on Ubuntu 16.04).  Thanks to @i300220 for posting up his solution, it worked for me as well (adding the path statement to the cron).

There's hints at the bottom of the update script on how to enter this into the crontab, maybe an additional hint for Debian/Ubuntu users?

**Comment by itoffshore** [comment]
@ScrewLooseDan - the examples at the end of `update-ngxblocker` use full paths specifically because `cron` does not normally have `$PATH`

you probably want to add `-q` to the cron command now for less verbose logging so you are only notified of problems or actual updates being applied.

```
# Add this as a cron to run daily / weekly as you like
# Here's a sample CRON entry to update every day at 10pm
# 00 22 * * * sudo /usr/sbin/update-ngxblocker -q

# Here's another example to run it daily at midday using a command line switch to set the email address for the notification
# 00 12 * * * sudo /usr/sbin/update-ngxblocker -e yourname@youremailprovider.com

# Less verbose logging to a system alias mail address (root crontab)
# 00 12 * * * /usr/sbin/update-ngxblocker -q -m webmaster

# better logging for cron jobs:
# https://serverfault.com/questions/137468/better-logging-for-cronjobs-send-cron-output-to-syslog
```

**Comment by ScrewLooseDan** [comment]
I was indeed using full path statements in my cron.  The issue is the script itself needs a path statement (I presume to find the service command).  

This failed on restarting nginx after an update:
`00 22 * * * /usr/sbin/update-ngxblocker -e notmyrealmail@example.com  >/dev/null 2>&1`

It gave the same error that i300220 mentioned in his first post.  The update of the files worked, but very last line in email was "Reloading NGINX configuration...[FAILED]".  Searching is what lead me to this issue thread where i300220 mentioned he used a PATH statement within his cron.  So, I used his example and did like this:

`00 22 * * * PATH=/sbin:/bin:/usr/sbin:/usr/bin /usr/sbin/update-ngxblocker -e notmyrealmail@example.com  >/dev/null 2>&1`

I realize putting a path statement inside the bash script would make it much less portable, so simply mentioning this work around with the other examples might be helpful.

**Comment by itoffshore** [comment]
on your system what does `which service` give ?

**Comment by ScrewLooseDan** [comment]
Looking again at the script, it appears to check for both service and also systemctl.  I'm far from a bash expert, but I presume service would be used if it exists as it's the first one satisfied in the check.

> $ which service	
/usr/sbin/service
$ which systemctl
/bin/systemctl

**Comment by i300220** [comment]
Idem on debian

> $ which service
> /usr/sbin/service
> $ which systemctl
> /bin/systemctl

**Comment by ScrewLooseDan** [comment]
I found a way to emulate the shell that cron runs ([here](https://stackoverflow.com/questions/2135478/how-to-simulate-the-environment-cron-executes-a-script-with)), and that changed my results:

> # which service
> # which systemctl
> /bin/systemctl

Looking at the code, systemctl wouldn't work.  

Line 310:
`$service nginx reload 2>&1 >/dev/null`

The proper syntax for systemctl is like:
`systemctl reload nginx.service`
Note the order, reload follows the command.  And also, the service name includes ".service".

Using the path statement to call the script allows the service command to be found, and that obviously works.
