### ISSUE TITLE
Installed succeeds but still get 200 OK from bad bot tests...

### ISSUE THREAD

**Issue by brianturney** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#124]
Curious where I might have gone wrong.  Installation succeeded with no errors.  Straight forward and easy install steps.  reloaded and restarted nginx.  globalblacklist.conf looks fine.  Tests to see if it works fail.  curl -I http://www.mydomain.com -e http://zx6.ru gives result 200 OK.  This test should fail but does not.

Any ideas on how I can troubleshoot no blocking occurring?  Appears the install succeeded but no bot blocking is happening.

Sincerely,
Brian

**Comment by brianturney** [comment]
I noted the install talks about .vhosts files which on my server do not exist.  yet my nginx server runs just fine.  I have one site.  I do not anticipate the need for vhost files.  The error during install that I missed before is this..  I currently have no vhost files, nor know how to create one nor the need why I would need this.. I have one site and always will have just one site.
/usr/sbin$ sudo ./setup-ngxblocker -x
Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt
no vhost files in: /etc/nginx/sites-available/*.vhost => exiting.

**Comment by brianturney** [comment]
Lastly, the proper steps for setting up a virtual host and correlating files according to https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-virtual-hosts-server-blocks-on-centos-6 show no mention of a file with the extension .vhost.  can you explain why this is?  According to this documentation once my vhost is created, I will still not have a .vhost file.  confused.

**Comment by itoffshore** [comment]
see the configuration at the top of `setup-ngxblocker`
```

WWW=/var/www
VHOST_EXT="vhost"
VHOST_DIR=/etc/nginx/sites-available
```
the vhost file extension is configurable - in your case change it to:

`VHOST_EXT="conf"`

or run the script as:

`setup-ngxblocker -e conf`

all of the scripts accept `--help` command line switches

**Comment by brianturney** [comment]
Thanks.  I missed that tidbit there.  The installer ran,..  though now errors when nginx -t is ran..  bad 'IF' directive in the install blockbots.conf file..  broken install conf files?
/usr/sbin$ sudo nginx -t
nginx: [emerg] "if" directive is not allowed here in /etc/nginx/bots.d/blockbots.conf:40
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by brianturney** [comment]
looks like the includes got slapped at the top of the vhosts file instead of in the server section.   fixed that.  installer just adds to the top of the file which is not correct and will cause errors.

**Comment by brianturney** [comment]
thanks itoffshore you got me going in the right direction.  appears to be working now.  my build does not use .vhost files.  my vhost file is named mysite.com so your comment helped.  I ran it with the com parameter and it worked.  than you so much.

**Comment by mitchellkrogza** [comment]
Hi @brianturney glad you got it working, thanks @itoffshore for the assistance 👍
