### ISSUE TITLE
Bots and Scrapers with blank agent name

### ISSUE THREAD

**Issue by brianturney** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#125]
Will this block scrapers and bots with the agent data empty?  It allowed 200 OK with the test curl -I http://www.mydomain.com -e '  '
I need to block blank/empty agents.

**Comment by mitchellkrogza** [comment]
Hi @brianturney can you try the following code addition to the blockbots.conf file followed by a reload of Nginx. (Try adding this at line 56 of /bots.d/blockbots.conf)

```
if ($http_referer = "") { 
    return 444; 
}
```

**Comment by brianturney** [comment]
You're a rock star.  That worked.  Thank you tons.

**Comment by brianturney** [comment]
I appreciate this a ton.  I sent some love to help feed your cat.  : )  Not a lot but what I can.
Sincerely,
Brian

**Comment by brianturney** [comment]
Unfortunately this last change gave me a 52 response from curl with a blank agent name, but also denied access to every other request.   adding the lines below shuts down my site entirely.  no access from any browser, any ip, no web site access by the world period.  : (
if ($http_referer = "") { 
    return 444; 
}
