### ISSUE TITLE
Possible to install this on a shared InMotionHosting server with WordPress?

### ISSUE THREAD

**Issue by cyberfunk** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#126]
Hello,
I'm just getting my head around PicScout and wanted to know if it's possible to install this on a shared server with InMotionHosting and a WordPress installation. Any information is much appreciated:-)

**Comment by itoffshore** [comment]
not with Shared Hosting - you would need a VPS you fully control.

have a look at [lowendtalk for a VPS](https://www.lowendtalk.com) - you probably want to start with a small OpenVZ container - or sometimes there are good yearly KVM offers

**Comment by cyberfunk** [comment]
Thanks so much! I'll look into this.
