### ISSUE TITLE
Add option arguments for `-i:`

### ISSUE THREAD

**Issue by xcorat** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#128]
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/76b6659c4a18eb399977b8bf8b683d3d3bc3e73f/setup-ngxblocker#L278

**Comment by itoffshore** [comment]
closed by https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/14ee01cef5c8e10e226f0f7e0912ee34834c19a4
