### ISSUE TITLE
Question: What is WWW dir?

### ISSUE THREAD

**Issue by xcorat** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#130]
Sorry for the silly question, I use pyramid and not sure where to point for the `$WWW`directory. What files are the setup script looking for when it looks for in `/var/www`

**Comment by itoffshore** [comment]
the setup script looks in `$WWW` for directories with a dot (  `domain.tld` ) - see `whitelist_domains()`

see also `-n` & `-w` options to supress or change

**Comment by xcorat** [comment]
Kool,Thx!
