### ISSUE TITLE
Executing setup-ngxblocker gives "no vhost files in: /etc/nginx/sites-available/*.vhost => exiting." No such thing as .vhost.

### ISSUE THREAD

**Issue by methodbox** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#137]
AFAIK and since I've been using Nginx, there's no such thing as a *.vhost file for it's configuration.

The files in /etc/nginx/sites-available and ../sites-enabled are with no file extension.

I can find no documentation suggesting this should be the file extension and literally nothing since 2016 that suggests this should be used. Maybe Google is broken.

Also, your guide indicates that the files in question, install-, setup- and update-ngxblocker are are located in the /usr/sbin directory. 

In Ubunut 16.04 they get installed in the /usr/local/sbin directory - this is the default on the dry run.

Regardless of the directory, the file type that it's looking for doesn't and shouldn't exist.

**Comment by methodbox** [comment]
Dug a bit deeper - it looks like this is an old convention of Nginx which hasn't been in use since at least 2016.

Nginx themselves setup the default site configuration files with no extension, hence ```/etc/nginx/sites-available/**default**```. 

The extension ```.conf``` is recognized by the nginx process, but .vhost is deprecated.

**Comment by itoffshore** [comment]
& what happens when you comment out or change as approp[riate at the top of the script ?

`VHOST_EXT="vhost"`

**Comment by methodbox** [comment]
I see nothing in your instructions, default or manual indicating to comment that out.

**Comment by itoffshore** [comment]
also if this functionality is removed & every file is parsed - how can you prevent configuration files in the dfirectory you do not want from being included from being parsed ? 

everything is configurable for a reason

**Comment by methodbox** [comment]
Configuration files shouldn’t be in /etc/nginx/sites-available or ../sites-enabled anyway.

But if you’re making that assumption, then at the very least please update the documentation to reflect that this is required.

**Comment by itoffshore** [comment]
you miss the point entirely

I should add to the docs - do not use if you have no common sense

**Comment by methodbox** [comment]
Okay well go fuck yourself then.

**Comment by itoffshore** [comment]
EDIT - do not use if you have no common sense OR manners
