### ISSUE TITLE
non detection of 301 redirects

### ISSUE THREAD

**Issue by audioscavenger** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#138]
hey, what a good project.

However **setup-ngxblocker** doesn't detect the 301 Redirects most people use, and simply adds:
```
include /etc/nginx/bots.d/ddos.conf; 
include /etc/nginx/bots.d/blockbots.conf;
```
in the last server block found. This just cannot work.
Following best practices (if any?), the last server blocks of a vhost should be used for redirects.

Thus, it would make more sense to your **setup-ngxblocker** script to add these includes in the server block**S** that contain a **root** directive only. Wouldn't it?

**Comment by itoffshore** [comment]
I didn't consider `vhost` files that are just a 301 `return` or `rewrite` (`location` directives with regex allow more fine tuning).

line `392` of the setup script shows how the insertion point is calculated:

`line=$(find_includes $file include last server_ last location first )`

which means insert:
____________________

after the last `server_`

&

before the first `location` directive

&

after the last `include` (within this range `server_ <----> location`)
____________________

you can play around with the parameters passed to `find_includes()` if you are using the simpler `return` statement - using on line `392` something like 

`line=$(find_includes $file include last server_ last return first )`

I will adjust the setup script to only change vhost files that have a `root` directive

**Comment by audioscavenger** [comment]
what a fast answer, awesome. I have to dig into your setup script, from what I read here. Fine by me. I'll test again with your changes and let you know how it worked
