### ISSUE TITLE
New Bots to Check for Addition

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#144]
BDCbot
istellabot
DnyzBot
AlphaBot (alphaseobot)

**Comment by feanorknd** [comment]
Hello:

Reporting InddeedBot .

103 Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0 (IndeedBot 1.1)
https://www.webmasterworld.com/search_engine_spiders/4873713.htm

This site is very interesting also ;)
https://www.webmasterworld.com/search_engine_spiders/
