### ISSUE TITLE
Vhosts without .vhost extension

### ISSUE THREAD

**Issue by janiosarmento** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#147]
There is no way to autoinstall the `include` directives to vhosts files if they do not end with `.vhost` or anything else.

In EasyEngine environments (pretty popular nowadays) the vhosts files are named like:

`/etc/nginx/sites-available/janio.sarmento.org`

**Comment by itoffshore** [comment]
if you have a single domain just use:

`setup-ngxblocker -e org`
