### ISSUE TITLE
Installation instructions not correct

### ISSUE THREAD

**Issue by janiosarmento** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#149]
Step 3 of installation instructions states:

    sudo chmod +x /usr/sbin/setup-ngxblocker
    sudo chmod +x /usr/sbin/update-ngxblocker

However, this location does not contain such files. The correct directory is `/usr/local/sbin`.

Step 4 also refers to the wrong location.

**Comment by mitchellkrogza** [comment]
@janiosarmento you need to download both those files manually, it is documented in the instructions in Step 1 of https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/README.md 

There has been changes in recent weeks to the setup-ngxblocker and install-ngxblocker scripts by the maintainer @itoffshore  so I need to check something has not changed that requires a documentation update but I doubt that. 

Please follow steps 1 > 5 of the readme carefully and report back please.

**Comment by mitchellkrogza** [comment]
@janiosarmento apologies, ignore my previous comment, there was indeed a change made to install-ngxblocker which now defaults to putting the scripts into /usr/local/sbin - https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/fa873a3e208bc8e3c75996af8ec06d9c36a20a91 I will update documentation today thanks for reporting this.

**Comment by mitchellkrogza** [comment]
Has been fixed now @janiosarmento thanks for reporting this, steps 1 > 8 all needed fixing.
