### ISSUE TITLE
Domain reffer exclusion not working good?

### ISSUE THREAD

**Issue by demon326** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#15]
Hi,

To start, i'd like to thank you for creating this list, its awesome! It works good, except that i have one little problem.  The whole site is working, except one page that seems to trigger the badbot list.  The page has the word 'hardcore' in it and that seems to trigger the badbot list, yet i have excluded my server IP and domain names from the reffer check:

`"~*mydomain.com" 0;
"~*metalfans.be" 0;
"~*home-theater.be" 0;`

The url is as follows:
[https://metalfans.be/metalfestivals/ieper-hardcore-fest-2017](url)

Also it seems that it allows the page to be loaded, but not the assets?

Thank you for your time :)

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/f32339032bfae8f9987144eb491182989eb598ed

**Comment by mitchellkrogza** [comment]
Thanks for the alert, it was picking up the word hardcore from the bad referer words section. I agree that the term "hardcore" can be used in good ways, not only bad so it's removed. So glad you are enjoying the benefits of this blocker.
