### ISSUE TITLE
MauiBot (crawler.feedback+wc@gmail.com)

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#152]
Added in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/8ab7b68053be4e40eb37d6647e8960ac26fe4eb2

**Comment by dm8mydog** [comment]
+1 on this, it is ignoring rel="nofollow" and adding to cart.
