### ISSUE TITLE
Suggestion: remove server_names_hash_bucket_size from main nginx.conf

### ISSUE THREAD

**Issue by janiosarmento** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#156]
I found all of my sites already had the `server_names_hash_bucket_size` directive in `/etc/nginx/nginx.conf`.

It would be great if the `setup-ngxblocker` was able to find a potential conflict in `/etc/nginx/nginx.conf` prior to adding the rules to vhosts, in order to avoid issues at `nginx -t` time.

Not sure if it would benefit some else, but for me it would be a great enhancement.

**Comment by centminmod** [comment]
Yeah i run into that issue as well, a simple sed replacement fixes it for me https://github.com/centminmod/centminmod-ultimate-bad-bot-blocker#nginxconf-fix

```
sed -i 's|^server_names_hash_|#server_names_hash_|g' /usr/local/nginx/conf/ultimate-badbot-blocker/botblocker-nginx-settings.conf
```

**Comment by mitchellkrogza** [comment]
Thanks @janiosarmento and @centminmod for reporting this. I am sure @itoffshore can look at this very valuable suggestion

**Comment by itoffshore** [comment]
<a href="https://i.imgur.com/5TslHPY.png">
  <img src="https://imgur.com/5TslHPYl.png" />
</a>

new PR should fix this - I tested with settings of:

```
http {

     server_names_hash_bucket_size
#server_names_hash_max_size
        limit_req_zone
        #limit_conn_zone
```

**Comment by centminmod** [comment]
cheers @itoffshore
