### ISSUE TITLE
Fail2Ban Integration with NUBBB

### ISSUE THREAD

**Issue by Nirjonadda** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#161]
@mitchellkrogza Do you get one email about checking include files edit?

Please can you let me know that how Fail2Ban Integration with NUBBB? Old step no more working.

Old steps : [here](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/26#issuecomment-294482981)

Thanks

**Comment by mitchellkrogza** [comment]
@Nirjonadda not had time to review your files yet, unfortunately I won't be able to until tomorrow, have some family issues.

Have you tested what you sent me?

As for Fail2Ban please what OS, what version of Fail2ban, need more info it's been a very long time since we first discussed this all.

**Comment by Nirjonadda** [comment]
>Have you tested what you sent me?

Yes I have do test but When you have time let me confirm that if this correct.

From my TESTING.

````
[root@sa ~]# curl -A "googlebot" http://mysite.com
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://mysite.com/">here</a>.</p>
</body></html>
[root@sa ~]#
````

Does not showing respond with 200 OK

````
[root@sa ~]# curl -A "80legs" http://mysite.com
curl: (52) Empty reply from server
[root@sa ~]#
````

I think this This working?

> As for Fail2Ban please what OS, what version of Fail2ban, need more info it's been a very long time since we first discussed this all.

I am using CENTOS 7.4 virtuozzo. How to check that what fail2ban version I am used?

**Comment by Nirjonadda** [comment]
fail2ban-client version

````
[root@sa ~]# fail2ban-client version
0.9.7
[root@sa ~]#

**Comment by mitchellkrogza** [comment]
The curl to http (port 80) is correct a 302 permanent redirect response :+1:

Then the second response "empty reply from server" is also :+1: that's always what you want to see

Now test all your curl commands against both http: and https:

**Comment by mitchellkrogza** [comment]
Email me your jail.local file or any customizations you have done to fail2ban

**Comment by Nirjonadda** [comment]
I have not any files jail.local and I am just installed fail2ban, no customizations. All are default setting.

**Comment by Nirjonadda** [comment]
OK I have created jail.local files but can not download nginxrepeatoffender.conf, Showing files not found. Also only want the one jail for NUBBB.

``
cd /etc/fail2ban/action.d

sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/Fail2Ban/action.d/nginxrepeatoffender.conf -O nginxrepeatoffender.conf

cd /etc/fail2ban/filter.d

sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/Fail2Ban/filter.d/nginxrepeatoffender.conf -O nginxrepeatoffender.conf

cd /etc/failban

sudo nano jail.local

[nginxrepeatoffender]
enabled = true
logpath = %(nginx_access_log)s
filter = nginxrepeatoffender
banaction = nginxrepeatoffender
bantime  = 86400   ; 1 day
findtime = 604800   ; 1 week
maxretry = 20
````

**Comment by mitchellkrogza** [comment]
I'll check what's wrong in the morning with that link thanks for reporting


On Apr 13, 2018 at 6:25 PM, <Md Tajirul Islam <notifications@github.com>>
wrote:

OK I have created jail.local files but can not download
nginxrepeatoffender.conf, Showing files not found. Also only want the one
jail for NUBBB.

``
cd /etc/fail2ban/action.d

sudo wget
https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/Fail2Ban/action.d/nginxrepeatoffender.conf
-O nginxrepeatoffender.conf

cd /etc/fail2ban/filter.d

sudo wget
https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/Fail2Ban/filter.d/nginxrepeatoffender.conf
-O nginxrepeatoffender.conf

cd /etc/failban

sudo nano jail.local

[nginxrepeatoffender]
enabled = true
logpath = %(nginx_access_log)s
filter = nginxrepeatoffender
banaction = nginxrepeatoffender
bantime = 86400 ; 1 day
findtime = 604800 ; 1 week
maxretry = 20

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/161#issuecomment-381188891>,
or mute the thread

**Comment by mitchellkrogza** [comment]
@Nirjonadda steps updated in original issues posted here to below

`cd /etc/fail2ban/action.d`

`sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_fail2ban_addon/action.d/nginxrepeatoffender.conf -O nginxrepeatoffender.conf`

`cd /etc/fail2ban/filter.d`

`sudo  wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/_fail2ban_addon/filter.d/nginxrepeatoffender.conf -O nginxrepeatoffender.conf`

`cd /etc/failban`

`sudo nano jail.local`

paste these contents into jail.local and save the file CTRL+X > Y > ENTER this uses nano text editor DON'T USE THE ABOVE jail.local I gave you. Something stupid CentOS has done 😡 , it worked initially but then also crashed on me. Hate it when distro's mess with things and don't follow standards.

```
# Local Jail.conf File
# JAILS
[nginxrepeatoffender]
enabled = true
logpath = %(nginx_access_log)s
filter = nginxrepeatoffender
banaction = nginxrepeatoffender
bantime  = -1   ; Forever
findtime = 604800   ; 1 week
maxretry = 6


```

**Comment by Nirjonadda** [comment]
@mitchellkrogza Great, I think all are working. Please let me know that where we can edit the email address notifications for ban alerts?

````
[root@sa ~]# fail2ban-client status
Status
|- Number of jail:      1
`- Jail list:   nginxrepeatoffender
[root@sa ~]#
````

One more question, Why I am still getting unknown/without bot name? Also Robot "Majestic-12" "linkdexbot/2.0" "Yandex" "Baidu" are not bad bots? Why this are not blocking?

![screenshotcapture_2018_04_14_01_11_28_421](https://user-images.githubusercontent.com/6899856/38766873-c0029474-3fd8-11e8-9585-cbaaa10194a6.jpg)
![screenshotcapture_2018_04_14_01_12_07_637](https://user-images.githubusercontent.com/6899856/38766874-c0204a50-3fd8-11e8-9d4c-f5ad0fdc977c.jpg)
![screenshotcapture_2018_04_14_01_12_21_634](https://user-images.githubusercontent.com/6899856/38766875-c0415cb8-3fd8-11e8-98ac-23694a1f9f08.jpg)
![screenshotcapture_2018_04_14_01_12_43_023](https://user-images.githubusercontent.com/6899856/38766876-c05e2af0-3fd8-11e8-8b17-2dd1774f93ca.jpg)

**Comment by mitchellkrogza** [comment]
@Nirjonadda add the following into the top of jail.local and restart fail2ban service

```
destemail = you@youremail.com
sender = fail2ban@myserver.com
sendername = Fail2Ban
mta = mail
```

**Comment by mitchellkrogza** [comment]
@Nirjonadda we don't block blank User-Agent strings, it CAN be done on Nginx but I would advise against it.

`Majestic12` is blocked but I see they have modified their user-agent to `Majestic-12` it will be fixed shortly.

Any of the others you want to block can be added to your `bots.d/blacklist-user-agents.conf` include file. Not everyone wants to block Yandex, Baidu 

Linkdexbot is also blocked and always has been

you need to grep your logs files to see that when linkdexbot is hitting your site, Nginx is issuing a 444 error to it. `grep 'linkdex' /var/log/nginx/yoursite-access.log`

**Comment by mitchellkrogza** [comment]
@Nirjonadda  Also please make SURE that Majestic is actually being blocked with a `444` response. 

You always need to make sure you monitor your logs using grep to see what Nginx is doing. To check for Majestic use this grep statement

`grep 'MJ12' /var/log/nginx/yoursite-access.log`


You should see something like this

` - [13/Apr/2018:21:30:53 +0200] "GET /robots.txt HTTP/1.0" 444 0 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)" "-"PORT:80 0.000 - . "GZIP:-"`

**Comment by mitchellkrogza** [comment]
@Nirjonadda Closing this issue as the original topic is resolved, **any future issues must be logged as separate issues please.**
