### ISSUE TITLE
502 Bad Gateway error

### ISSUE THREAD

**Issue by Nirjonadda** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#162]
@mitchellkrogza I am getting 502 Bad Gateway error after enabled jail for NUBBB. I have disabled jail.local file then now website lodaing without any error. Please let me know this fix.

**Comment by Nirjonadda** [comment]
Can not add ignoreip because restart are not working. Also my server have 3 IP and how to add? 

````
ignoreip = 127.0.0.1/8 `my server IP` `one more server IP` 8.8.8.8
````
````
[root@sa ~]# service fail2ban restart
Redirecting to /bin/systemctl restart fail2ban.service
Job for fail2ban.service failed because the control process exited with error code. See "systemctl status fail2ban.service" and "journalctl -xe" for details.
[root@sa ~]#
````

**Comment by mitchellkrogza** [comment]
just add all IP's seperated by spaces ONLY no special characters of any sort

`ignoreip = 127.0.0.1/8 x.x.x.x x.x.x.x x.x.x.x 8.8.8.8` add as many as you like

**Comment by mitchellkrogza** [comment]
Some very useful information and debugging information here in this very lengthy article I wrote on Fail2Ban - https://ubuntu101.co.za/security/fail2ban/fail2ban-persistent-bans-ubuntu/

**Comment by itoffshore** [comment]
@Nirjonadda `fail2ban` config files are commented:

```
# "ignoreip" can be an IP address, a CIDR mask or a DNS host. Fail2ban will not
# ban a host which matches an address in this list. Several addresses can be
# defined using space (and/or comma) separator.
ignoreip = 127.0.0.1/8 ::1, 1.2.3.4, 5.6.7.8 
```

**Comment by mitchellkrogza** [comment]
NO commas !!! spaces only !!!!!

**Comment by Nirjonadda** [comment]
Fixed, Thanks !!!

**Comment by mitchellkrogza** [comment]
Great so that's problem 1 sorted.
