### ISSUE TITLE
Allow 403 response to blocked IPs with custom 403 page 

### ISSUE THREAD

**Issue by bretlowery** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#167]
Hi Mitchell, this project works great for me, appreciate your efforts keeping the w/b lists up-to-date.

I have an edge case where I want to 403 the blocked IPs instead of 444ing them. So in blockbots.conf I want to have:

# IP BLOCKS
# *********
if ($validate_client) {
  return 403; #instead of 444
}

(I'm still 444ing bots, bad referrers, etc.) This is so I can inject a custom 403 with some special JS for additional forensics purposes. This may be beyond the scope of Bad Bot Blocker, but being able to do this would allow me to manage blacklists in one place -- your blacklists -- rather than two, with one routing conf file -- yours -- rather than multiple nginx confs controlling multiple blacklists.

I have the custom 403s set up in my nginx confs, and everything works when I don't use Bad Bot Blocker (i.e. when I leave the two includes for ddos.conf and blockbots.conf out of my nginx conf file). However, when I add the two includes back in, I only get the generic 403 nginx Forbidden page, and not my custom page. I've tried reordering items in the nginx conf -- when your two includes get called in relation to my error handlers -- to no avail. 

I'm not asking for debugging help with my nginx confs. I'm just wondering if you've ever tried doing this before with custom error pages, and if so do you have any pointers or examples.

Thanks!

**Comment by itoffshore** [comment]
@bretlowery - a simpler solution is just to have `fail2ban` manage the blacklists from the generated `444` pages (use the `ipset` functionality in `fail2ban` rather than `iptables` for more efficient memory usage)

`fail2sql` will give you the ability to ban persistent attackers in `fail2ban` & give you a db with statistics

**Comment by bretlowery** [comment]
I'll check it out, thx!
