### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by kunzelmanm** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#17]
In the docs for testing you have: curl -I http://yourdomain.com -e http://zyzzcentral.ru

I don't see zyzzcentral.ru in the globalblacklist.conf, so a site would respond normally to that request, I think.

**Comment by mitchellkrogza** [comment]
Sorry, that was removed. Will update the docs.
You can see in my travis tests I no longer test for that but thanks for alerting me to it still being in the docs. Thank you, will push out an update now.
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/.travis.yml

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/8ff3858ef81f7c8e9264f581b57ce381a1fa7856 Thank you for alerting me to that error.
