### ISSUE TITLE
Block countries using GeoIP but respecting whitelisted User agent and IPs

### ISSUE THREAD

**Issue by dutuka** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#170]
Hello,
I want to use GeoIP to block requests from some countries, the GeoIP rules should be applied at the lowest level and respect User agent/IPs whitelist (so that requests from good user agent and whitelisted IPs **from blocked countries** are **not** blocked). 
In the `bots.d` folder, I find only `blacklist-user-agents.conf` but not `whitelist-user-agents.conf` file, where/how can I add a custom user agent to the whitelist.
My nginx already has geoip module, hope you can help me with the configuration. Thanks.

**Comment by mitchellkrogza** [comment]
Hi @dutuka the `blacklist-user-agents.conf` is used for both black and whitelisting, sorry for the confusion.

```
# Even though this file is called blacklist-user-agents, as mentioned it can also be used to whitelist user agents
# By adding them below and setting the 3; to 0; this will permanently whitelist the User-Agent.
```

Please read comments inside all include files carefully. Hope this helps.
