### ISSUE TITLE
2 Google ranges behaving not.

### ISSUE THREAD

**Issue by i300220** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#175]
Hi,

I'm still faithful to your script.  It does great things to my websites.  Thanks for that.

Not a bug properly speaking, just a constatation you might like,

Recently, 1-2 months in time, I got a lot of strange impossible requests all with the same User-Agent, no referrer and HTTP/1.1.  All came from Google.  They do not respect robots.txt and sniff everywhere they're not supposed to.  I thought you should be make aware of it.

I know you whitelist Google IPs, but after inspection from other users, you might want to revisit those.

User-agent:
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"

Ranges:
66.249.64.0/19
72.14.199.0/24

Examples of request:
72.14.199.18 - - [27/May/2018:14:12:01 -0700] "GET /page.php?page%3Dabout_himeji_forklifts&amp HTTP/1.1" 301 178 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
72.14.199.4 - - [27/May/2018:14:12:24 -0700] "GET /page.php?page%3Dabout_himeji_forklifts&amp HTTP/1.1" 302 165 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"

In the meantime, I circumvented your whitelist by issuing manual range bans.  After 6 weeks, no more of those strange requests, and bandwidth has dropped significantly since those 2 ranges were requestings quite a few hundred of megabytes each day!

Thanks again.

**Comment by mitchellkrogza** [comment]
Hi @i300220 thanks for reporting this. Do you have any pages by those names in your site(s)?
It looks like something from project AMP which is looking for something because of the `&amp` on the end. 

Be aware that not all of Google's Bots necessarily send their user-agent string. 

Have you got more log examples of this.

**Comment by i300220** [comment]
Hi Mitchell,

Those are indeed existing pages, but with '&amp' appended to the URL.  Or the '=' sign in parameters changed to '%3D'.  Almost every valid page is tested this way, even the restricted access files/directories (forbidden by robots.txt or meta tag).

Some misbehaved bots will always try the '%3D' thing or try URLs like '/////page.php', I'm used to it, but that '&amp' appended is unique to Google.

Unfortunately, I don't have any more examples.  I keep logs 10 days only and by now they have been rotated.

re Project AMP:  You nailed it I think.  Totally makes sense.  I wasn't aware of it.  Thanks for the hint.

**Comment by mitchellkrogza** [comment]
Glad I could help, their amp bots often look if the page has an amp version to index but those amp bots do not use a friendly user-agent name like `GoogleAmpBot` or something like that.

**Comment by i300220** [comment]
Hi Mitchell,

You asked for more examples, here we go.

For now either we issue a 400 (bad request) or we redirect them to our obsolete browsers page (size 5229).

All sort of requests that doesn't make any sense.

I have tons of them:
`
$:/var/log/nginx# grep chrome/28 access.log.1|wc -l
4268
`

`66.249.90.88 - - [19/Jun/2018:07:51:44 -0700] "GET /shipping_estimator&amp HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:51:45 -0700] "GET /page.php?page=about_bindersRice HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:51:47 -0700] "GET /faq.php HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:51:49 -0700] "GET /page.php?page=about_agricultural_machinery HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:51:50 -0700] "GET /page.php?page=about_cost_verificationSHIPPINGThere& HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:51:52 -0700] "GET /page.php?page=about_tractors HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:51:54 -0700] "GET /faq.php HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:51:55 -0700] "GET /page.php?page%3Dabout_rice_planters&amp HTTP/1.1" 400 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:51:57 -0700] "GET /page.php?page=about_binders HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:51:59 -0700] "GET /page.php?page%3Dabout_banking&amp HTTP/1.1" 400 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.92 - - [19/Jun/2018:07:52:00 -0700] "GET /page.php?page=about_rice_plantersScroll HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.92 - - [19/Jun/2018:07:52:02 -0700] "GET /contact.php HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.92 - - [19/Jun/2018:07:52:03 -0700] "GET /page.php?page=about_testimonials HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:52:05 -0700] "GET /page.php?page%3Dabout_agricultural_machinery&amp HTTP/1.1" 400 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.90 - - [19/Jun/2018:07:52:06 -0700] "GET /shipping_estimatorThese HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.90 - - [19/Jun/2018:07:52:08 -0700] "GET /page.php?page=about_tractor_shipping HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:52:09 -0700] "GET /page.php?page=about_combine_harvesters HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:52:11 -0700] "GET /page.php?page=about_agricultural_machinery HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:52:12 -0700] "GET /shipping_estimator&amp HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:52:14 -0700] "GET /page.php?page%3Dabout_rice_planters&amp HTTP/1.1" 400 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:52:15 -0700] "GET /page.php?page%3Dabout_frequently_asked_questions&amp HTTP/1.1" 400 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:52:17 -0700] "GET /page.php?page%3Dabout_testimonials&amp HTTP/1.1" 400 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:52:18 -0700] "GET /page.php?page%3Dabout_binders&amp HTTP/1.1" 400 568 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"
66.249.90.88 - - [19/Jun/2018:07:52:20 -0700] "GET /page.php?page=about_cost_verification HTTP/1.1" 200 5229 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"`

**Comment by mitchellkrogza** [comment]
Sorry for delay on this. Any update? Which UA did you give a 2 value to? Been doing a lot of changes recently so let me know as I'm ironing out a lot of little bugs and have improved accuracy and false positives big time

**Comment by mitchellkrogza** [comment]
New Rate Limiting Build Test Being Introduced

**Comment by mitchellkrogza** [comment]
@i300220 rate limiting tested and 100% working in latest version. You can over-ride any bot and rate limit it and it works. You can look at the build log, near the end where it does the rate limit testing you will see GoogleBot was successfully rate limited > https://travis-ci.org/mitchellkrogza/nginx-ultimate-bad-bot-blocker/builds/550708959
