### ISSUE TITLE
question: how to parse globalblacklist.conf in python?

### ISSUE THREAD

**Issue by monperrus** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#176]
The distinction between good and bad user-agents is very interesting.
I want to add this information in https://github.com/monperrus/crawler-user-agents/.

Yet, [globalblacklist.conf](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/conf.d/globalblacklist.conf) uses a special format.

How to parse globalblacklist.conf in python?

**Comment by mitchellkrogza** [comment]
Hi @monperrus any pull requests can be done on the following user agents generator lists.

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/_generator_lists/bad-user-agents.list

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/_generator_lists/good-user-agents.list

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/_generator_lists/allowed-user-agents.list

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/_generator_lists/limited-user-agents.list

**Comment by monperrus** [comment]
Thanks. Do you mean that globalblacklist.conf is generated out of those lists?

**Comment by mitchellkrogza** [comment]
Yes @monperrus globalblacklist.conf is generated from all the files in the https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/tree/master/_generator_lists folder

**Comment by monperrus** [comment]
Thanks!
