### ISSUE TITLE
For your review, "Mr.4x3 Powered"

### ISSUE THREAD

**Issue by i300220** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#177]
New user-agent discovered recently.  Just to let you know.

162.213.121.70 - - [05/Jun/2018:16:00:36 -0700] "GET /page.php?page=about_power_boats HTTP/1.1" 200 21271 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:16:34:53 -0700] "GET /page.php?page=about_truck_tyres HTTP/1.1" 200 15945 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:17:02:19 -0700] "GET /page.php?page=about_commuter_cars HTTP/1.1" 200 15443 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:17:21:56 -0700] "GET /page.php?page=about_mini_crane_trucks HTTP/1.1" 200 16340 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:18:01:30 -0700] "GET /page.php?page=about_nichiyu_forklifts HTTP/1.1" 200 16255 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:18:25:32 -0700] "GET /page.php?page=about_yahoo_motorhomes HTTP/1.1" 200 16693 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:19:02:20 -0700] "GET /page.php?page=about_turbochargers HTTP/1.1" 200 16404 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:19:13:45 -0700] "GET /page.php?page=about_parts_systems HTTP/1.1" 200 22972 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:19:46:56 -0700] "GET /page.php?page=about_export_centre HTTP/1.1" 200 19236 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:20:08:33 -0700] "GET /page.php?page=about_interior_parts HTTP/1.1" 200 14740 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:20:30:02 -0700] "GET /page.php?page=about_instruction_vehicles HTTP/1.1" 200 16389 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:20:47:46 -0700] "GET /page.php?page=about_suppliers HTTP/1.1" 200 19443 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:21:09:25 -0700] "GET /page.php?page=about_concrete_mixer_trucks HTTP/1.1" 200 17247 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:21:31:59 -0700] "GET /page.php?page=about_brakes HTTP/1.1" 200 15202 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:21:50:22 -0700] "GET /page.php?page=about_isuzu_trucks HTTP/1.1" 200 18304 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:21:50:23 -0700] "GET /page.php?page=about_isuzu_trucks HTTP/1.1" 200 18304 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:22:08:40 -0700] "GET /page.php?page=about_wheels HTTP/1.1" 200 17027 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:22:08:41 -0700] "GET /page.php?page=about_wheels HTTP/1.1" 200 17027 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:22:28:57 -0700] "GET /page.php?page=about_salvage_motorbikes HTTP/1.1" 200 16497 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:22:55:09 -0700] "GET /page.php?page=about_bars HTTP/1.1" 200 15252 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:23:16:23 -0700] "GET /page.php?page=about_auction_cost_estimator HTTP/1.1" 200 14803 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:23:42:04 -0700] "GET /page.php?page=about_skid_steers HTTP/1.1" 200 15072 "-" "Mr.4x3 Powered"
162.213.121.70 - - [05/Jun/2018:23:56:16 -0700] "GET /page.php?page=about_nissan_trucks HTTP/1.1" 200 17912 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:00:22:20 -0700] "GET /page.php?page=about_differences HTTP/1.1" 200 16674 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:00:42:30 -0700] "GET /page.php?page=about_dismantling HTTP/1.1" 200 15686 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:01:05:27 -0700] "GET /page.php?page=about_cng_vehicles HTTP/1.1" 200 16457 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:01:27:41 -0700] "GET /page.php?page=about_dealer_motorhomes HTTP/1.1" 200 15453 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:01:59:23 -0700] "GET /page.php?page=about_tools HTTP/1.1" 200 15242 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:02:13:27 -0700] "GET /page.php?page=about_team HTTP/1.1" 200 16282 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:02:37:41 -0700] "GET /page.php?page=about_nissan_forklifts HTTP/1.1" 200 16524 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:03:01:21 -0700] "GET /page.php?page=about_honda_cars HTTP/1.1" 200 17384 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:03:25:06 -0700] "GET /shipping_estimator HTTP/1.1" 200 16529 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:04:04:42 -0700] "GET /page.php?page=about_vehicles_to_new_zealand HTTP/1.1" 200 16231 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:04:21:43 -0700] "GET /page.php?page=about_turbo_timers HTTP/1.1" 200 15228 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:04:53:36 -0700] "GET /page.php?page=about_prime_movers HTTP/1.1" 200 16717 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:05:18:31 -0700] "GET /page.php?page=about_sail_boats HTTP/1.1" 200 15824 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:05:36:29 -0700] "GET /page.php?page=about_vacuum_trucks HTTP/1.1" 200 16923 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:06:06:30 -0700] "GET /page.php?page=about_spoilers HTTP/1.1" 200 16135 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:06:23:33 -0700] "GET /page.php?page=about_mini_excavators HTTP/1.1" 200 16157 "-" "Mr.4x3 Powered"
162.213.121.70 - - [06/Jun/2018:06:42:57 -0700] "GET /page.php?page=about_others HTTP/1.1" 200 17631 "-" "Mr.4x3 Powered"

**Comment by mitchellkrogza** [comment]
Thanks very much @i300220 did the bot request robots.txt at all?

**Comment by mitchellkrogza** [comment]
Webmaster World confirms the bot does not request robots.txt - https://www.webmasterworld.com/search_engine_spiders/4872982.htm

**Comment by i300220** [comment]
`did the bot request robots.txt at all?`

no, not once.

**Comment by mitchellkrogza** [comment]
Thanks @i300220 it was introduced in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/a9ef73b12b08327727902e7e9798858e1d782796
