### ISSUE TITLE
setup-ngxblocker changes

### ISSUE THREAD

**Issue by zjagust** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#178]
Hello,

Regarding domain whitelisting, can you please add an option of manual input for vhosts whose location is actually a "proxy pass" and they dont have a **home** location in _/var/www_ .

Second, can you please change lines 115 and 116 from this:
```
if [ -n "$(which dig)" ]; then
ip=$(dig +short myip.opendns.com @resolver1.opendns.com)
```
to this:
```
if [ -n "$(which curl)" ]; then
ip=$(curl ifconfig.co)
```
As it looks like myip.opendns.com does not exits any more and is not resolvable.
Thank you!

**Comment by itoffshore** [comment]
should be fixed now - please test

**Comment by zjagust** [comment]
Sorry for a late response; looks good now, thank you.
