### ISSUE TITLE
For review: "PxBroker/0.3.1/6627"

### ISSUE THREAD

**Issue by zjagust** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#180]
Found this in my access logs:
134.119.212.87 - - [07/Jun/2018:08:04:45 +0200] "GET /echo.php HTTP/1.1" 301 178 "https://www.google.com/" "PxBroker/0.3.1/6627" rt=0.000 uct="-" uht="-" urt="-"

I looked it up trough several useragent lookup tools and no info at all. Not quite sure is it relevant at all or related to this: https://github.com/constverum/ProxyBroker/blob/master/proxybroker/utils.py#L41

**Comment by mitchellkrogza** [comment]
I found this reference. I also picked it up 3 times in my logs now.

https://www.abuseipdb.com/check/134.119.212.39

**Comment by zjagust** [comment]
Thank you!
