### ISSUE TITLE
Quick-Crawler (+https://www.scrapinghub.com/)

### ISSUE THREAD

**Issue by it-can** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#181]
This is a scraping bot, think it should be blocked

```
Quick-Crawler (+https://www.scrapinghub.com/)
```

**Comment by mitchellkrogza** [comment]
Thank you @it-can added in latest build https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/2a3bc40f733ea37020f85b33293f3fdd2ffc0fad
