### ISSUE TITLE
ahrefbots

### ISSUE THREAD

**Issue by i300220** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#184]
Hi Mitchell,

Would if be feasible for you to add another zone with a ridiculously long rate?  I have a client insisting on keeping AfrefBots but that thing even limited at 2r/s is hammering us at the rate of 10,000 request per day, every day.

I could add it myself, but likely the next update from you would break it.

Actual settings:
`bots.d/blockbots.conf:limit_req  zone=bot2_reqlimitip burst=10;`
`bots.d/ddos.conf:limit_req zone=flood burst=200 nodelay;`
`conf.d/botblocker-nginx-settings.conf:limit_req_zone $binary_remote_addr zone=flood:50m rate=90r/s;`
`conf.d/globalblacklist.conf:    limit_req_zone  $bot_iplimit zone=bot2_reqlimitip:16m  rate=2r/s;`

I was initially thinking of a new zone with a rate limit of 1 request per minute (rate=1r/m)

Best regards!

**Comment by mitchellkrogza** [comment]
Yes you could add a new zone with a limit of 1r/s actually. I'm AFK but will get back to you Wednesday

**Comment by i300220** [comment]
Thanks Mitchell.

Although it would be a 50% improvement on the actual settings, it would not be enough for our purposes.

Ahrefbots is so aggressive that rate=1r/m, which is currently supported by nginx is required here.

Until it's added, or I add it myself, afrefbots is being blocked (the default) so our website is working again.  It's that bad.  That thing is pulling several GB/mo.

**Comment by mitchellkrogza** [comment]
@i300220 combine 1r/s with burst=5 it should solve the issue. Rate limiting in Nginx is extremely powerful but takes tweaking to find the correct settings.

**Comment by i300220** [comment]
Cool, thank you very much!

**Comment by mitchellkrogza** [comment]
It would allow 1 request per second but if a burst of 5 suddenly comes in 1 Second they will be rate limited. Try it and let me know how it goes.

**Comment by i300220** [comment]
- Installed.

- Disabled /usr/sbin/update-ngxblocker cron job while it's being tested.

- Choose a $bad_bot value of 5 because I already use 4 for a custom action.

Settings:
```
limit_req zone=bot5_reqlimitip burst=5;      # in vhost config                                                                                                       
"~*\bAhrefsBot\b"       5; # in conf.d/blacklist-user-agents.conf
"~*\bahrefs\.com\b"    5; # in conf.d/blacklist-user-agents.conf
```
Diff file:

```
--- globalblacklist.conf.bak    2018-06-20 12:33:14.987927737 -0700
+++ globalblacklist.conf        2018-06-20 12:40:27.322491247 -0700                                                                                   @@ -7445,6 +7445,7 @@
        0    "";                                                                                                                                              1    "";                                                                                                                                              2    $binary_remote_addr;                                                                                                                     +       5    $binary_remote_addr;
        }                                                                                                                                                                                                                                                                                                    # ***********************
@@ -7462,6 +7463,12 @@                                                                                                                                        limit_conn_zone $bot_iplimit zone=bot2_connlimit:16m;                                                                                                 limit_req_zone  $bot_iplimit zone=bot2_reqlimitip:16m  rate=2r/s;
                                                                                                                                                      +# limits for Zone $bad_bot = 5                                                                                                                       +# this rate limiting will only take effect if you change any of the bots and change                                                                  +# their block value from 1 to 5.
+       limit_conn_zone $bot_iplimit zone=bot5_connlimit:16m;                                                                                         +       limit_req_zone  $bot_iplimit zone=bot5_reqlimitip:16m  rate=1r/s;                                                                             +
 ### *** MAKE SURE TO ADD to your nginx.conf ***                                                                                                       ### server_names_hash_bucket_size 64;                                                                                                                 ### server_names_hash_max_size 4096;
```

**Comment by i300220** [comment]
If it works, which I'm not certain, it's making 8.1 requests/min today.  Which means 12000 requests/day possible.  Same as I had with a setting of 2 for $bad_bot.  Still 10x too many.

Since it's not acceptable, I'm reblocking it.

**Comment by mitchellkrogza** [comment]
@i300220 that's why Ahrefs is blocked by default for all users of the blocker.

**Comment by mitchellkrogza** [comment]
@i300220 can we close this yet?

**Comment by i300220** [comment]
Sure, go ahead, thanks for your help!
