### ISSUE TITLE
Connection was reset

### ISSUE THREAD

**Issue by minimaluminium** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#187]
Getting "Connection was reset" on http://preview.themeforest.net/item/bokeh-photography-portfolio-theme-for-wordpress/full_screen_preview/20630093

But not getting any on http://bokeh.mondotheme.com/

Could this be related with bot blocker? The first one is showing the second URL in iFrame.

**Comment by mitchellkrogza** [comment]
The blocker won't affect loading of iframes content but not to say that maybe a false positive is being triggered. Can you monitor your logs of the first site when that connection reset occurs. You need to monitor both your access and error log. What browser are you using and have you tested with another browser?

**Comment by minimaluminium** [comment]
I’ve tested on all major browsers including iOS Safari. What is the best way to uninstall the blocker? Can I assume that the blocker is disabled if I simply comment out the two lines added by the blocker in a vhost config file?

**Comment by mitchellkrogza** [comment]
Yes indeed just comment out the following two lines in any vhost to disable it.

```
		include /etc/nginx/bots.d/blockbots.conf;
		include /etc/nginx/bots.d/ddos.conf;
```

Don't forget to reload nginx `nginx -t && nginx -s reload`
