### ISSUE TITLE
Bad IP?

### ISSUE THREAD

**Issue by Nirjonadda** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#188]
Do we need blocking this IP?

https://whatismyipaddress.com/ip/106.11.157.213

**Comment by mitchellkrogza** [comment]
Is that IP showing in your logs? Can you please post log excerpts so we can see what it's doing.

**Comment by Nirjonadda** [comment]
Yes this IP in log, One more bad IP: https://whatismyipaddress.com/ip/106.11.159.219
