### ISSUE TITLE
Content scrapers - Preventing Website Scraping?

### ISSUE THREAD

**Issue by Nirjonadda** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#193]
I am not getting this are block Content scrapers. Today I am get 2 site in google. This site “peloponesoa.tk” and “virtujre.tk” ? that site to scrap my content. It is scraping my content and publishing (live AJAX update) as their own. Please can you help me identify the scraper and block the false website?

**Comment by mitchellkrogza** [comment]
Unfortunately you can't block content scrapers without knowing either 
a) user-agent string (which can be faked)|
b) IP which can be changed

Questions:
1) Is your site running on https? Do you have a content security policy? (CSP) ????
2) Do you have X-Headers on your site? (X-Frame-Options ?)

**Comment by Nirjonadda** [comment]
> Is your site running on https?

Yes, you know my website URL?

> Do you have a content security policy? (CSP) ????

No because Xenforo are not compatible with Content-Security-Policy.

> Do you have X-Headers on your site? (X-Frame-Options ?)

Yes, See here what i am using for Security Headers.

![screenshot00085](https://user-images.githubusercontent.com/6899856/42894242-a6182a96-8ab6-11e8-8586-b8f57b561d45.png)

````
# Enable Support Forward Secrecy
SSLHonorCipherOrder On
SSLProtocol all -SSLv2 -SSLv3

# Security header Enable HSTS
Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" env=HTTPS

# Turn on IE8-IE9 XSS prevention tools X-XSS
Header always set X-XSS-Protection "1; mode=block"

# Referrer-Policy
Header always set Referrer-Policy "no-referrer-when-downgrade"

# X-Permitted-Cross-Domain-Policies
Header always set X-Permitted-Cross-Domain-Policies "none"
````

> Can you post log examples if you have.

What log? Apache/nginx error_log or nginx access_log?

> I looked at their site and it looks like they are pulling your site directly and making it look like porn.

Yes, That bad activity.

> A content security policy and X-headers should prevent that.

Only using X-Frame-Options are not help?

**Comment by Nirjonadda** [comment]
One log:

````
212.129.39.252 - - [19/Jul/2018:01:53:16 +0600] "GET /job.php HTTP/1.0" 200 14 "https://peloponesoa.tk/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"
````

**Comment by Nirjonadda** [comment]
````
location ~* \.*.php$ {
    internal;
	include fastcgi.conf;
	fastcgi_pass unix:/run/php/php7.0-fpm.sock;
       #any other php configurations here
}
````

Where can add this code? Also I am using PHP 7.2

**Comment by mitchellkrogza** [comment]
Php 7. 2 should be same file location but BEST to check and make sure where your fpm is located. This code goes in your host configuration not in nginx.conf

**Comment by mitchellkrogza** [comment]
That's FAKE googlebot go check the whois information on who owns that IP... Not Google

**Comment by mitchellkrogza** [comment]
@Nirjonadda any luck can I close this?

**Comment by Nirjonadda** [comment]
OK closing for now.
