### ISSUE TITLE
Block Vulnerability Scanners like WPSCAN?

### ISSUE THREAD

**Issue by robert1112** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#195]
Hi @mitchellkrogza 

I saw Vulnerability Scanners on the list and would like to double check if WPSCAN is included? Thank you so much.

**Comment by mitchellkrogza** [comment]
Yes they are

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/conf.d/globalblacklist.conf#L722

Hasn't been tested in a while though but keep in mind with a lot of open source projects like WPScan, one could download and modify the code and User-Agent string. So keep in mind this blocker will keep out 99% of rubbish, people who are intent on getting something will try other avenues. The rest of catching other offenders unfortunately comes down to regular monitoring of your logs.

**Comment by mitchellkrogza** [comment]
@robert1112 just remember something with Wordpress Vulnerability Scanners and Theme Detectors, all they are is a graphical user interface for those too lazy to look at the source code of your wordpress site. Anyone can visit your site > view source and quickly determine your wordpress version AND all plugins you are running simply by looking at the code, its all there.

**Comment by robert1112** [comment]
I think expert can easily change User-Agent right? Do you hear of https://www.webarxsecurity.com ?

**Comment by mitchellkrogza** [comment]
Very easily can modify any code to pass this as the User-Agent `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36` 😺 

not seen https://www.webarxsecurity.com/ but there is lots of similar one's out there

**Comment by mitchellkrogza** [comment]
@robert1112  
![wpscan](https://user-images.githubusercontent.com/9961541/43465095-e67a5886-94dc-11e8-980a-bf9244bac1ab.PNG)

**Comment by mitchellkrogza** [comment]
The only way you will ever stop everything is to simply `sudo shutdown -h now` 😁

**Comment by robert1112** [comment]
WOW, nice! Thank you so much for the lesson. Do you have WP site? Can you share how you protect your site? Do you WPSCAN your site to find the weakness and fix them? That is my next step.

**Comment by robert1112** [comment]
Can you also Kindly comment on my comment above? Thank you.

**Comment by mitchellkrogza** [comment]
I run about 24 wordpress sites, the blocker keeps most rubbish out, monitoring logs daily is the key to everything. I used wpscan once or twice but it's pretty much a waste of time as I make sure all my sites are always 100% up to date, plugins, themes and wordpress. 

Nginx can also be configured to spare yourself from lots of wordpress, php and other security risks simply by blocking such methods.

**Comment by mitchellkrogza** [comment]
Most automated bots are actually quite stupid. I have one that checks a fake wordpress site of mine every hour of every day for wp-login.php so I have a real (fake) wp-login.php for it to hit if it wants to and fall into a trap but the bots are not so intelligent because they query first on port 80, they get redirected to port 443 through a 301 redirect and then they do not even follow that redirect. I have Honey for them but they don't come eat it 😺 You'll notice I only know about this by watching my logs

**Comment by mitchellkrogza** [comment]
@robert1112 now that you have enabled logs go read the Readme section on how to monitor your logs through cron https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/README.md

**Comment by robert1112** [comment]
You mean this right?
**HOW TO MONITOR YOUR LOGS DAILY (The Easy Way)**

I am also thinking of trying Fail2Ban. Do you think it is very necessary? I never used it in docker and I think I need to learn how to do it. Thank you.

**Comment by mitchellkrogza** [comment]
Yes that's the way to monitor logs very easy and automated.

Fail2Ban essential too so learn it

**Comment by robert1112** [comment]
Thanks. I will do.  But I got problem sending email from NGIXN then! 😟

**Comment by mitchellkrogza** [comment]
Install a command line mailer

**Comment by mitchellkrogza** [comment]
`sudo apt-get install mailutils`

**Comment by robert1112** [comment]
That is it? After installing this,  Mail will send?
00 08 * * * tail -10000 /var/log/nginx/mydomain-access.log | awk '$11 !~ /google|bing|yahoo|yandex|mywebsite.com/' | awk '{print $11}' | tr -d '"' | sort | uniq -c | sort -rn | head -1000 | mail -s "Top 1000 Referers for Mydomain1.com" name@gmail.com

**Comment by robert1112** [comment]
Hi @mitchellkrogza I tried sSMTP - Simple SMTP and works well. Thank you so much.
