### ISSUE TITLE
Integrate fail2ban with CloudFlare

### ISSUE THREAD

**Issue by robert1112** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#197]
Hi @mitchellkrogza 

While studying Fail2Ban, I bumped into this and think it will greatly reduce the server loading if bad bots or attacks are blocked at proxy like Cloudflare before reaching server. Just for your reference and future plan for this already awesome tool. 👍 

https://guides.wp-bullet.com/integrate-fail2ban-cloudflare-api-v4-guide/

**Comment by mitchellkrogza** [comment]
Off topic for this repo please reopen in correct repo.

**Comment by robert1112** [comment]
Sorry I am very new to Github so I dont know what you mean by reopen in correct repo. 😭

**Comment by mitchellkrogza** [comment]
No worries we all have to Learn. Just open the fail2ban issues here https://github.com/mitchellkrogza/Fail2Ban-Blacklist-JAIL-for-Repeat-Offenders-with-Perma-Extended-Banning
