### ISSUE TITLE
I got blocked out.

### ISSUE THREAD

**Issue by robert1112** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#198]
Hi @mitchellkrogza 

I cannot ssh to my server and I check my iptables and found I got blocked by myself. 😢 

How to avoid this in future? Whitelist my ip? What if I on travel, I will have different ip? Thank you.
```
Chain f2b-nginxrepeatoffender (1 references)
 pkts bytes target     prot opt in     out     source               destination
   88  5804 DROP       all  --  any    any     121-254-111-144.veetime.com  anywhere
```

**Comment by mitchellkrogza** [comment]
Very important to whitelist your own IP's but what did you do to blacklist yourself?

**Comment by mitchellkrogza** [comment]
Can you move this issue to the correct repo and not here.
