### ISSUE TITLE
nginx: [emerg] "if" directive is not allowed here

### ISSUE THREAD

**Issue by revcomllc** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#2]
when testing we get this error:

nginx: [emerg] "if" directive is not allowed here in /etc/nginx/bots.d/blockbots.conf:16
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by mitchellkrogza** [comment]
Did you find what was wrong? It's possible you placed the blockbots.conf include in the wrong section. It must be included in a server block

server {
}

**Comment by mitchellkrogza** [comment]
Readme instructions have been updated to mention that includes must be added within a server {} block

**Comment by xcorat** [comment]
the files 
`conf.d/botblocker-nginx-settings.conf` and `conf.d/globalblacklist.conf` files have,

```
    # Bad Bot Blocker
    include /etc/nginx/bots.d/ddos.conf; 
    include /etc/nginx/bots.d/blockbots.conf;
```

which are not in server blocks, I guess it got automatically added when I ran the setup script twice

**Comment by mitchellkrogza** [comment]
That is very strange @xcorat can you describe which setup you used so we can see if there is a problem with it duplicating adding the includes.
