### ISSUE TITLE
Feature Request: Add switch for MAILFROM

### ISSUE THREAD

**Issue by rrosson** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#200]
Would it be possible to update the update script to have a switch and variable for "mail from". I had to modify my version on ubuntu since ubuntu does not support that environment variable in the cron that is installed with 18.04 and older.

TIA

**Comment by mitchellkrogza** [comment]
I'm sure @itoffshore can help with this

**Comment by itoffshore** [comment]
@rrosson - the `FROM` name is set by whatever you use to send email.

use `chfn` to change the display name in `/etc/passwd` & set an alias in `/etc/ssmtp/revaliases` if you use `ssmtp`.

a simple solution is to just [use `msmtp`](https://wiki.archlinux.org/index.php/Msmtp) which allows you to set a `FROM` address.

**Comment by markwbrown** [comment]
#261 adds a "from" email field for use with Mailgun. @itoffshore - if e-mails are sent with the -e flag, and a -f flag is also included, should the chfn and alias be set up to use the from address after the -f flag?

**Comment by itoffshore** [comment]
@markwbrown - I still think the helper scripts should not try & work around mail misconfiguration. 

- if someone is running the `bot-blocker` on multiple systems it is more useful to use the system set from address on that particular system.
- Alpine Linux (& containers based on it) - do not have `chfn`

**Comment by markwbrown** [comment]
@itoffshore Agreed. That's kind of why I added the Mailgun stuff -- nice to have an option for a transactional email API for use on systems with mail disabled.

**Comment by mitchellkrogza** [comment]
Closed in #262
