### ISSUE TITLE
IP whitelist not working?

### ISSUE THREAD

**Issue by ibantxo** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#201]
Our nginx-server is in 172.26.1.1

We have tested from 172.26.1.8:  curl -I http://172.26.1.1 -A "heritrix"
Received anser --> curl: (52) Empty reply from server
That's OK because "heritrix" bot is in the "bad bot list". OK

But, we have inserted next line in the bots.d/whitelist-ips.conf file:
172.26.1.8          0;

After restarting nginx server, we have tested again from 172.26.1.8:  curl -I http://172.26.1.1 -A "heritrix"
Received answer --> curl: (52) Empty reply from server
Is not working? Are user-agent "blacklist" and IP "whitelist" incompatible?
How could I add an exception (allow) for one "blacklisted" user-agent?

Many thanks!!

Iban

**Comment by mitchellkrogza** [comment]
Hi @ibantxo to whitelist a single user-agent simple add it like below to blacklist-user-agents.conf 

`
	"~*\bheritrix\b"			0;
`
Then reload Nginx

Take note of the comments in blacklist-user-agents.conf it's for whitelisting and blacklisting too.

**Comment by ibantxo** [comment]
Hi Mitchell, and many thanks for your fast answer!!

Sorry, but I want do that only for one client IP.
I want to globally blacklist heritrix, but allow for one IP address that is
using that bot.

**Comment by mitchellkrogza** [comment]
You could try nesting an if statement within that include file. I would have to test tomorrow but it should work.

**Comment by Xe1K3** [comment]
Hi, I have the same problem this conf in bots.d/blockbots.conf  work fine:

```
if ($remote_addr ~ "(myip1)|(myip2)" ) {
    set $bad_bot  '0';
  }
```

**Comment by mitchellkrogza** [comment]
Whitelisting of any blacklisted User-Agent is working and tested 100% in latest update
Blacklisting of any whitelisted User-Agents is working and tested 100% in latest version
Changes done in
blacklist-user-agents.conf
custom-bad-referrers.conf
Are global and work 100% as you can see in any of the latest build tests

**Comment by mitchellkrogza** [comment]
@ibantxo you can see the complete over-riding/whitelisting of any bad user-agents and bad-referrers in this latest build test > https://travis-ci.org/mitchellkrogza/nginx-ultimate-bad-bot-blocker/builds/550273277

My tests now run this whitelist test each and every time before a new version is released. In fact every single aspect and include file is tested during the builds now, this tests for false positives and to make sure every single feature works as expected. One single failure will fail a build from being released.

**Comment by mitchellkrogza** [comment]
@XelK IP whitelisting is also currently in the workflow for testing on new V4

**Comment by mitchellkrogza** [comment]
Ok I misread this. Firstly global over-riding did have an issue which is now tested and working. 
Whitelisting tests still in progress for allowing only your own IP to bypass anyting

**Comment by mitchellkrogza** [comment]
Correct way to handle this is as per @XelK suggestion.

This works great in blockbots.conf 

```
if ($remote_addr ~ "(127.0.0.1)" ) {
    set $bad_bot  '0';
    set $validate_client '0';
}
```

This above rules goes at the very top of blockbots.conf and also guarantee's even if you went and blacklisted 127.0.0.1 by giving it a value of 1 in whitelist-ips.conf this rule completely over-rides it.

I am adding this rule (commented out by default) to blockbots.conf with comments for users who want to be able to over-ride things completely.

Thanks @XelK

**Comment by mitchellkrogza** [comment]
@ibantxo @XelK whitelisting IPs is 100% fixed and working and pushed in version 4 updates today
