### ISSUE TITLE
Installation feedback / issues

### ISSUE THREAD

**Issue by GutHib** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#202]
I've installed the nginx-ultimate-bad-bot-blocker today and it seems to work fine - thanks for all the hard work you guys put into this useful tool!

I ran into a couple of issues, however (fixing them might make the life of me/others easier):

1. In STEP 1 of the automatic installation instructions ( https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/README.md ), the sbin path is used inconsistently. Replace the first, line, then it makes sense:

OLD:
Download install-ngxblocker to your /usr/sbin/directory and make the script executable.

NEW:
Download install-ngxblocker to your /usr/local/sbin directory and make the script executable.

2. In STEP 4 the instructions say:

"What this setup script has done has simply added the following include statements into your .vhost files for you."

That is actually not true - the setup script does more than that. For anyone running into issues here it would be important to understand what that is. (I learned it also adds /etc/nginx/conf.d/* to the includes, otherwise, the whole script will fail).

3. Speaking of failing... on my server, the following variables are already defined:

server_names_hash_bucket_size
server_names_hash_max_size

Defining them again in botblocker-nginx-settings.conf will keep nginx from starting, as it is impossible to define these variables twice. Maybe add some kind of "if not defined" condition?

Thanks!

**Comment by GutHib** [comment]
PS: Also, it would still be great to have the system's domains whitelisted automatically (either on the fly, or at least via an update script). On most Linux systems it is fairly easy to produce a list of active domains. Are there any plans to incorporate this into the actual whitelist-domains.conf?

**Comment by mitchellkrogza** [comment]
Thanks @GutHib readme updated, thanks for catching those errors. As far as checking for 
```
server_names_hash_bucket_size
server_names_hash_max_size
```
I was pretty sure that @itoffshore scripts checked for those if they exist.

**Comment by GutHib** [comment]
You are correct. I checked the log files again, and the error doesn't come up because your variable definitions, but because of the OTHER definitions that are loaded after yours. Hence, there is nothing you could possibly do to fix this.

**Comment by mitchellkrogza** [comment]
@itoffshore hope you are well, any possibility to auto whitelist all domains during setup as per comment above?

**Comment by itoffshore** [comment]
functionality already included:

see `-w` & `-n` options in `install-ngxblocker --help`

**Comment by mitchellkrogza** [comment]
Thanks so much Stuart, you're a star, you've already thought about and included everything, I really need to get our docs up to speed.

**Comment by itoffshore** [comment]
I think just emphasize the 3 helper scripts have a `-h` or `--help` switch that gives full details of the options & usage examples

**Comment by mitchellkrogza** [comment]
I will do thanks so much Stuart and thanks again for the most versatile scripts for this project

**Comment by GutHib** [comment]
After finally figuring out some server configuration issues, I ran my first update-nginxblocker today - works great!

Two more thoughts:

1. To accomodate for the ultimate bot blocker, I had to comment out the default configuration:
#server_names_hash_max_size 10240;

Instructions stress how important it is to define a high max. size, yet the script is slashing it to 4096 which is 1/3 of the default I had. Need I be concerned?

2. You have implemented auto-whitelist, which is fantastic, but it seems like, to run it, I would have to run the entire setup script, which I am afraid of doing (everything is working fine now, so why run the risk of breaking it?). If you could add more switches in the future so individual setup functions can be run separately (e.g. after adding a new domain), that would be the icing on the cake.

Thanks!

**Comment by GutHib** [comment]
Dry run is great - I wasn't aware of that. My flavor of nginx works with templates so I have my doubts the script will find the includes, but then I will just give it a try. Thanks for the quick reply!

**Comment by GutHib** [comment]
PS: The dry run didn't get me far - it ended with this:

find: '/etc/nginx/sites-available': No such file or directory

**Comment by itoffshore** [comment]
@GutHib - see `--help` or `-h` all paths are configurable

**Comment by GutHib** [comment]
Well like I said, my nginx works with templates. You edit the vhosts template just once, then run a rebuild_configs script and you're done. Future domains? Handled automatically.

What I wanted was the auto-whitelist, but it seems like I can't get there without somehow wrestling down the part of the script that wants to add includes. I'm afraid that's just not all that useful for my purposes.

**Comment by itoffshore** [comment]
@GutHib - if it's too complicated for you - please do not use it

**Comment by GutHib** [comment]
@itoffshore - I think I have made clear enough that my installation of nginx is very different from what you appear to assume as standard. Therefore, I wanted to know if I could somehow use the auto-whitelist without having to use the auto-include, which is both incompatible and unnecessary with my template-based setup.

If that is too complicated for you, a simple "no" would have sufficed - there was no need to insult me.

I am unsubscribing from this thread now.

**Comment by itoffshore** [comment]
@GutHib - I explained twice that paths are configurable. The scripts are used on many custom nginx setups without issue.

If you had run the scripts with `-h` you would have seen that running `setup-ngxblocker -v /my/custom/path` would have solved your issue. The scripts are written so they can be re-run without breaking configuration. They are also written so that by default you can see the changes they would make before they change anything.

You were asking for functionality that should be unnecessary. If you run the scripts correctly using the various command line options for the paths & there is breakage open an issue or propose a `PR`.

**Comment by GutHib** [comment]
Not sure why I am even getting this reply. I have unsubcribed from this thread - what more can I do.

I had already told you twice that my nginx works with templates. It is neither possible nor sensible to edit the individual files. Do I need to apologize for not having the nginx setup you want me to?

I made a custom template that will insert the necessary includes automatically. There is no sites-available file or directory on my server. Different concept, like I said. Hence, there is no place I could possibly point your configurable paths to.

You have chosen not to listen, fine. It's a free world and you're a grown-up man - suit yourself. Just stop insulting me, please. This is ridiculous.
