### ISSUE TITLE
Need some help to install the blocker within Bitnami WordPress with NGINX for Google Cloud Platform

### ISSUE THREAD

**Issue by yusheng123** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#203]
Hi All,

I am a newbie in NGINX. And I have some trouble in installing this software in Bitnami WordPress with NGINX for Google Cloud Platform. [Bitnami WordPress](https://docs.bitnami.com/google/apps/wordpress-pro/#first-steps-with-the-bitnami-wordpress-with-nginx-and-ssl-stack) uses non-standard directories. The Nginx configuration file is /opt/bitnami/nginx/conf/bitnami/bitnami.conf

In the folder /opt/bitnami/nginx/conf, the file structure is:

/opt/bitnami/nginx/conf
├── bitnami
│   ├── bitnami-apps-prefix.conf
│   ├── bitnami-apps-vhosts.conf
│   ├── bitnami.conf
│   ├── bitnami.conf.back
│   └── phpfastcgi.conf
├── botblocker-nginx-settings.conf
├── fastcgi.conf
├── fastcgi.conf.default
├── fastcgi_params
├── fastcgi_params.default
├── globalblacklist.conf
├── koi-utf
├── koi-win
├── mime.types
├── mime.types.default
├── nginx.conf
├── nginx.conf.default
├── privkey.pem
├── sample_domain_host.conf
├── scgi_params
├── scgi_params.default
├── server.crt
├── server.csr
├── server.key
├── uwsgi_params
├── uwsgi_params.default
├── vhosts
└── win-utf

I have download everything to local:

> $ sudo ./install-ngxblocker -c /opt/bitnami/nginx/conf -b /opt/bitnami/nginx/bots.d -x
> Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt
> Creating directory: /opt/bitnami/nginx/bots.d
> REPO = https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master
> Downloading [FROM]=>  [REPO]/conf.d/globalblacklist.conf            [TO]=>  /opt/bitnami/nginx/conf/globalblacklist.conf...OK
> Downloading [FROM]=>  [REPO]/conf.d/botblocker-nginx-settings.conf  [TO]=>  /opt/bitnami/nginx/conf/botblocker-nginx-settings.conf...OK
> REPO = https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master
> Downloading [FROM]=>  [REPO]/bots.d/blockbots.conf              [TO]=>  /opt/bitnami/nginx/bots.d/blockbots.conf...OK
> Downloading [FROM]=>  [REPO]/bots.d/ddos.conf                   [TO]=>  /opt/bitnami/nginx/bots.d/ddos.conf...OK
> Downloading [FROM]=>  [REPO]/bots.d/custom-bad-referrers.conf   [TO]=>  /opt/bitnami/nginx/bots.d/custom-bad-referrers.conf...OK
> Downloading [FROM]=>  [REPO]/bots.d/bad-referrer-words.conf     [TO]=>  /opt/bitnami/nginx/bots.d/bad-referrer-words.conf...OK
> Downloading [FROM]=>  [REPO]/bots.d/blacklist-domains.conf      [TO]=>  /opt/bitnami/nginx/bots.d/blacklist-domains.conf...OK
> Downloading [FROM]=>  [REPO]/bots.d/blacklist-ips.conf          [TO]=>  /opt/bitnami/nginx/bots.d/blacklist-ips.conf...OK
> Downloading [FROM]=>  [REPO]/bots.d/blacklist-user-agents.conf  [TO]=>  /opt/bitnami/nginx/bots.d/blacklist-user-agents.conf...OK
> Downloading [FROM]=>  [REPO]/bots.d/whitelist-domains.conf      [TO]=>  /opt/bitnami/nginx/bots.d/whitelist-domains.conf...OK
> Downloading [FROM]=>  [REPO]/bots.d/whitelist-ips.conf          [TO]=>  /opt/bitnami/nginx/bots.d/whitelist-ips.conf...OK
> REPO = https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master
> Downloading [FROM]=>  [REPO]/setup-ngxblocker      [TO]=>  /usr/local/sbin/setup-ngxblocker...OK
> Downloading [FROM]=>  [REPO]/update-ngxblocker     [TO]=>  /usr/local/sbin/update-ngxblocker...OK
> Setting mode: 700 => /usr/local/sbin/install-ngxblocker
> Setting mode: 700 => /usr/local/sbin/setup-ngxblocker
> Setting mode: 700 => /usr/local/sbin/update-ngxblocker

Then I am trying to run the step 4 "setup-ngxblocker":

> $ sudo ./setup-ngxblocker -c /opt/bitnami/nginx/conf -b /opt/bitnami/nginx/bots.d
> find: ‘/etc/nginx/sites-available’: No such file or directory
> find: ‘/etc/nginx/sites-available’: No such file or directory
> Configure every file above as a vhost ? [Y/N] : 

What should I do here? First of all, the nginx config is not in that directory /etc/nginx/. I can change it to /opt/bitnami/nginx/conf, but still there is no /opt/bitnami/nginx/conf/sites-available.

Many thanks!

**Comment by mitchellkrogza** [comment]
As per your directory structure your vhost are in the `vhosts` folder not in `sites-available`

**Comment by mitchellkrogza** [comment]
So @yusheng123 you would need to pass the command line argument `-v /opt/bitnami/nginx/conf /vhosts` to `setup-ngxblocker`

**Comment by yusheng123** [comment]
Thanks for your quick reply :-) To pass "-v /opt/bitnami/nginx/conf/vhosts" to setup-ngxblocker, I have two questions:

1. The directory "/opt/bitnami/nginx/conf/vhosts" is empty, is that fine?
2. The file "/opt/bitnami/nginx/conf/bitnami/bitnami-apps-vhosts.conf" seems to be related (as the filename, and it is also empty). Should I copy it to /opt/bitnami/nginx/conf/vhosts?

Much appreciated!

**Comment by yusheng123** [comment]
I am trying to find out a workaround with [this thread](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/150):
1.  Modify /opt/bitnami/nginx/conf/nginx.conf as:
```
http {
   # Other things

    # Bad Bot Blocker at the very end
    include "/opt/bitnami/nginx/conf/globalblacklist.conf";
    include "/opt/bitnami/nginx/conf/botblocker-nginx-settings.conf";
}
```

2. Update the paths in /opt/bitnami/nginx/conf/globalblacklist.conf, e.g. change /etc/nginx/bots.d/blacklist-user-agents.conf to /opt/bitnami/nginx/bots.d/blacklist-user-agents.conf

3. sudo nginx -t:
nginx: the configuration file /opt/bitnami/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /opt/bitnami/nginx/conf/nginx.conf test is successful

4. restart the server:
sudo /opt/bitnami/ctlscript.sh restart nginx

However, I was unable to pass the test:

For Bad Referers test, with ANY referer, it returns empty content.
```
$ curl -I https://mysite.com -e http://xxxrus.org
HTTP/1.1 200 OK
Server: nginx/1.14.0
Date: Mon, 13 Aug 2018 07:01:21 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: PHP/7.0.30
Link: <https://mysite.com/wp-json/>; rel="https://api.w.org/"
X-Frame-Options: SAMEORIGIN

$ curl -I https://mysite.com -e http://google.com
```

For Bad User Agents test, it always return the right content.

FYI, I can still access the website with my Firefox.

**Comment by mitchellkrogza** [comment]
@yusheng123 the blocker includes must only go inside a `server {}` block not in an `http {}` block

**Comment by mitchellkrogza** [comment]
@yusheng123 so you have the block includes but where are you adding the other includes in your vhost?
```
	# Block Bad Bots
	include /etc/nginx/bots.d/blockbots.conf;
	include /etc/nginx/bots.d/ddos.conf;
```

**Comment by yusheng123** [comment]
>> where are you adding the other includes in your vhost?
Sorry, I am currently using the default config from the Bitnami stacks. I did not find the right way to add other includes yet~

>> the blocker includes must only go inside a server {} block not in an http {} block
I tried to add the blocker includes in a server {} block, but it complains:
$ sudo nginx -t
nginx: [emerg] "map" directive is not allowed here in /opt/bitnami/nginx/conf/globalblacklist.conf:107
nginx: configuration file /opt/bitnami/nginx/conf/nginx.conf test failed

**Comment by yusheng123** [comment]
Here is the output:
```
$ sudo grep -R 'server_name' /opt/bitnami/nginx/*
/opt/bitnami/nginx/conf/globalblacklist.conf:### server_names_hash_bucket_size 64;
/opt/bitnami/nginx/conf/globalblacklist.conf:### server_names_hash_max_size 4096;
/opt/bitnami/nginx/conf/fastcgi_params:fastcgi_param  SERVER_NAME        $server_name;
/opt/bitnami/nginx/conf/fastcgi.conf:fastcgi_param  SERVER_NAME        $server_name;
/opt/bitnami/nginx/conf/nginx.conf.default:        server_name  localhost;
/opt/bitnami/nginx/conf/nginx.conf.default:    #    server_name  somename  alias  another.alias;
/opt/bitnami/nginx/conf/nginx.conf.default:    #    server_name  localhost;
/opt/bitnami/nginx/conf/botblocker-nginx-settings.conf:server_names_hash_bucket_size 128;
/opt/bitnami/nginx/conf/botblocker-nginx-settings.conf:server_names_hash_max_size 4096;
/opt/bitnami/nginx/conf/botblocker-nginx-settings.conf:#     #server_names_hash_bucket_size 128;
/opt/bitnami/nginx/conf/uwsgi_params:uwsgi_param  SERVER_NAME        $server_name;
/opt/bitnami/nginx/conf/scgi_params:scgi_param  SERVER_NAME        $server_name;
/opt/bitnami/nginx/conf/sample_domain_host.conf:  # server_name www.[engineyard].com [engineyard].com;
/opt/bitnami/nginx/conf/sample_domain_host.conf:  # server_name www.[engineyard].com [engineyard].com;
/opt/bitnami/nginx/conf/bitnami/bitnami.conf.back:        server_name  localhost;
/opt/bitnami/nginx/conf/bitnami/bitnami.conf.back:       server_name  localhost;
/opt/bitnami/nginx/conf/bitnami/bitnami.conf.back:    server_name local-stackdriver-agent.stackdriver.com;
/opt/bitnami/nginx/conf/bitnami/bitnami.conf:        server_name  localhost;
/opt/bitnami/nginx/conf/bitnami/bitnami.conf:        server_name  localhost;
/opt/bitnami/nginx/conf/bitnami/bitnami.conf:    server_name local-stackdriver-agent.stackdriver.com;
/opt/bitnami/nginx/conf/fastcgi.conf.default:fastcgi_param  SERVER_NAME        $server_name;
/opt/bitnami/nginx/conf/fastcgi_params.default:fastcgi_param  SERVER_NAME        $server_name;
/opt/bitnami/nginx/conf/uwsgi_params.default:uwsgi_param  SERVER_NAME        $server_name;
/opt/bitnami/nginx/conf/scgi_params.default:scgi_param  SERVER_NAME        $server_name;
```

According the the Bitnami document, Nginx configuration file is /opt/bitnami/nginx/conf/bitnami/bitnami.conf. The content is:

```
    # HTTP server

    server {
        listen       80;
        server_name  localhost;

	return 301 https://$host$request_uri;
	include "/opt/bitnami/nginx/conf/bitnami/bitnami-apps-prefix.conf";

        #include "/opt/bitnami/nginx/conf/bitnami/phpfastcgi.conf";
    }

    # HTTPS server

    server {
        listen       443 ssl;
        server_name  localhost;

	ssl_certificate	codesays.com.crt;
	ssl_certificate_key	codesays.com.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        #include "/opt/bitnami/nginx/conf/bitnami/phpfastcgi.conf";

        include "/opt/bitnami/nginx/conf/bitnami/bitnami-apps-prefix.conf";
    }


    include "/opt/bitnami/nginx/conf/bitnami/bitnami-apps-vhosts.conf";



# Status
server {
    listen 80;
    server_name local-stackdriver-agent.stackdriver.com;
    location /nginx_status {
      stub_status on;
      access_log   off;
      allow 127.0.0.1;
      deny all;
    }
    location / {
      root /dev/null;
    }
}
```

Thanks very much for your help!

**Comment by yusheng123** [comment]
PS: I did not config anything about my domain name in the nginx. I just update it in the Wordpress dashboard. And it works.

**Comment by yusheng123** [comment]
PPS: /opt/bitnami/nginx/conf/bitnami/bitnami-apps-vhosts.conf is empty.

**Comment by mitchellkrogza** [comment]
Ok great getting closer, where have you placed these files? `blockbots.conf` and `ddos.conf` ?

**Comment by yusheng123** [comment]
wow! Thanks @mitchellkrogza for your hints! Here is my solution:

1.  Modify /opt/bitnami/nginx/conf/nginx.conf as:
```
http {
   # Other things

    # Bad Bot Blocker at the very end
    include "/opt/bitnami/nginx/conf/globalblacklist.conf";
    include "/opt/bitnami/nginx/conf/botblocker-nginx-settings.conf";
}
```
2. Update /opt/bitnami/nginx/conf/bitnami/bitnami.conf, in each "server" section, add the following statements:
```
	# Block Bad Bots
	include /etc/nginx/bots.d/blockbots.conf;
	include /etc/nginx/bots.d/ddos.conf;

```
3. Update the paths in /opt/bitnami/nginx/conf/globalblacklist.conf, e.g. change /etc/nginx/bots.d/blacklist-user-agents.conf to /opt/bitnami/nginx/bots.d/blacklist-user-agents.conf

4. sudo nginx -t:
nginx: the configuration file /opt/bitnami/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /opt/bitnami/nginx/conf/nginx.conf test is successful

5. restart the server:
sudo /opt/bitnami/ctlscript.sh restart nginx

Finally, for my non-standard case, could you please tell me how to update the blocker? Thanks again!

**Comment by mitchellkrogza** [comment]
Great stuff, well done.
To update manually you can simply run a cron like this
`sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/globalblacklist.conf -O /opt/bitnami/nginx/conf/globalblacklist.conf && sudo nginx -t && sudo nginx -s reload`

**Comment by yusheng123** [comment]
Thanks! Here is my final version:
```
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/globalblacklist.conf -O /opt/bitnami/nginx/conf/globalblacklist.conf && sudo sed -i 's/\/etc\/nginx/\/opt\/bitnami\/nginx/g' /opt/bitnami/nginx/conf/globalblacklist.conf && sudo nginx -t && sudo nginx -s reload
```

sed command is executed to update the paths.

**Comment by mitchellkrogza** [comment]
For a newbie at Nginx you have done extremely well in such a short time, well done. You will no doubt become a master at Nginx through your sheer determination.
