### ISSUE TITLE
Ban sogou spider

### ISSUE THREAD

**Issue by Nirjonadda** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#206]
Please add ban sogou spider from china.

````
Robot: Sogou > IP: 123.126.113.130 (sogouspider-123-126-113-130.crawl.sogou.com)
````

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/14dbf10a2175c1041bae7b6e7ac27681dc047224 wait for build to complete then update and confirm the fix is working.

**Comment by mitchellkrogza** [comment]
@Nirjonadda did the latest update solve the problem?

**Comment by Nirjonadda** [comment]
Yes, I think this sogou spider banned?

````
[root@ra ~]# grep Version /etc/nginx/conf.d/globalblacklist.conf
### Version: V3.2018.08.1177
[root@ra ~]# curl -A "sogouspider" https://mysite.com
curl: (52) Empty reply from server
[root@ra ~]#
````

**Comment by mitchellkrogza** [comment]
Great.
