### ISSUE TITLE
Duplicate "limit_conn" & limit_req" in ddos.conf

### ISSUE THREAD

**Issue by supercharlez** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#210]
Hi There, I'm manually installing Bad Bot Blocker on Ubuntu / Nginx 1.15

I have 2 small isues 

1) In my vhost, as per your instructions, I added : (I added missing semi colon btw or it doesn't work)

```
server {
include /etc/nginx/bots.d/blockbots.conf;
include /etc/nginx/bots.d/ddos.conf;
}
```

And when I do 
`$ sudo nginx -t`

I still have the EMERG errors " "limit_conn" directive is duplicate in /etc/nginx/bots.d/ddos.conf:37"
& "limit_req" directive is duplicate in /etc/nginx/bots.d/ddos.conf:39

This lines are: 
```
limit_conn bot2_connlimit 10;
limit_req  zone=bot2_reqlimitip burst=10;
```
I double checked, I have all the 8 needed files in /bot.d/, as well as globalblacklist.conf & botblocker-nginx-settings.conf in /conf.d/.

I commented them out in the meantime to make the rest work.

2) I then tried 
`curl -I http://www.MyDomain.com -A "80legs"     `

It didn't give ma a "curl: (52)" but 
` curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.`

Is this error 56 ok ? (Fortunately, I do get a HTTP/1.1 200 OK with good bots like GoogleBot)

Can someone pleas tell me what did I do wrong ?

Thank so much for this awesome ressource

**Comment by mitchellkrogza** [comment]
Is it at all possible you are loading the contents of the `bots.d` directory somewhere else causing the duplicate? Do you perhaps have `include /etc/nginx/bots.d/*` in your main nginx.conf? You can post your config files so we can have a look.

**Comment by ItHurtsWhenIP404** [comment]
I too received same issue via 'manual' install.  I commented out the same two lines  @supercharlez, was having issues with and the the 'sudo nginx -t' succeeded. I did back out change and did not proceed further.
