### ISSUE TITLE
-bash: /usr/local/sbin/update-ngxblocker: No such file or directory [FeeBSD]

### ISSUE THREAD

**Issue by alsyundawy** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#212]
[root@xxx ~]# /usr/local/sbin/update-ngxblocker
-bash: /usr/local/sbin/update-ngxblocker: No such file or directory
[root@xxx ~]# /usr/local/sbin/setup-ngxblocker
-bash: /usr/local/sbin/setup-ngxblocker: No such file or directory

**Comment by itoffshore** [comment]
duplicate of https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/213
