### ISSUE TITLE
http 504 errors after installing nginx-ultimate-bad-bot-blocker

### ISSUE THREAD

**Issue by galp** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#215]
I set up this tool and i could get it to block bot traffic. Initially I tested with curl on a test environment  and I could get 444 for bot traffic from my machine and I was very happy with it. 
On my staging environment it worked fine but I had no real traffic to test with so I decided to
 to deploy  this on a production env. 
Our setup is amazon ELB >nginx  > php-fpm 
 and send it a small percentage of my live traffic to it. I could see that it does block a lot of the bot traffic as expect but I also get a small percentage of 504 errors. Occasionally  the health checks on the loadbalancer will trigger and the environment degrades.

I have been digging around for a while, changing nginx settings, timeouts, keepalive without getting anywhere. In my normal environment I rarely get those hence my assamption that is related to the blocker.

Any clues from your side would be really appreciated although I realize that this might not be a great bug report. It is not very clear for me to formulate it as the errors are intermittent and I can not make any correlations

Thank you

**Comment by mitchellkrogza** [comment]
504 "Gateway Timeout" is entirely related to a poorly setup Nginx not the blocker and that's 100% guaranteed. I run sites that go into several millions of hits per month and never ever get 504 errors.

**Comment by galp** [comment]
Ok thank you. I will close the issue and investigate further.
