### ISSUE TITLE
requires: 'curl' => cannot check remote version.

### ISSUE THREAD

**Issue by stevenmunro** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#216]
ubuntu 16.04

When I try to run update-ngxblocker manually on the command line. I get the following error.

`$ /usr/local/sbin/update-ngxblocker`

`ERROR: /usr/local/sbin/update-ngxblocker requires: 'curl' => cannot check remote version.`

`$ curl -V`

`curl 7.56.1 (x86_64-pc-linux-gnu) libcurl/7.56.1 OpenSSL/1.0.2g zlib/1.2.8 nghttp2/1.26.0
Release-Date: 2017-10-23
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy`

**Comment by stevenmunro** [comment]
This is happening because I compiled my own Curl.

The script expects to find curl at /usr/bin/curl
My location is /usr/local/bin/curl

Creating a symlink and marking this as resolved.

**Comment by itoffshore** [comment]
@stevenmunro - this should be fixed by last week's update https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/214
