### ISSUE TITLE
Amplify file access

### ISSUE THREAD

**Issue by ScrewLooseDan** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#222]
Not sure this is really an "issue", but figured I would ask...

I've been playing around with The NGINX team's [Amplify](https://amplify.nginx.com/).  It provides various stats about your NGINX, as well as makes an attempt at analyzing your configuration looking for potential issues.  It has an agent that runs locally to collect this information before putting it on their servers.

The nginx-amplify-agent runs as the www-data user (at least on Ubuntu systems).  This prevents the agent from accessing /etc/nginx/conf.d/globalblacklist.conf, since it is are owned as root:

`2018-10-17 00:55:52,371 [1727] nginx_config failed to read /etc/nginx/conf.d/globalblacklist.conf due to: IOError`

```
$ ps -efl | grep amplify
1 S www-data  1727     1  0  80   0 - 44447 -      Oct12 ?        00:27:39 amplify-agent
```
This note is on Amplify's [documentation](https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html):

> **Note**. The agent will drop root privileges on startup. It will then use the user ID of the user  `nginx` to set its effective user ID. The package install procedure will add the `nginx` user automatically unless it's already found in the system. If the user directive appears in the NGINX configuration, the agent will pick up the user specified in the NGINX config for its effective user ID (e.g. `www-data`).

I can change the permissions on the file to allow read access, but this obviously gets overwritten with any update since the update script changes permissions.  I did do this as a test and the agent was able to parse the `globalblacklist.conf` file.  The analyzer found no issue.

I'm not overly concerned with this, just curious if there's some other solution to allow access that I haven't considered that might work.

**Comment by itoffshore** [comment]
@ScrewLooseDan - this can be achieved with **ACL**:

`setfacl -m "g:group:permissions" <file/dir>`

**e.g:**

`setfacl -m "g:www-data:r--" /path/to/globalblacklist.conf`

see [Access Control Lists](https://wiki.archlinux.org/index.php/Access_Control_Lists)

**Comment by ScrewLooseDan** [comment]
@itoffshore - Perfect!  That was exactly what I was hoping to achieve.  Not sure how I hadn't run across ACL previously, but the more I learn the more I realize how little I know.
