### ISSUE TITLE
unknown "bad_bot" variable

### ISSUE THREAD

**Issue by hostingfuze** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#223]
# nginx -t
nginx: [emerg] unknown "bad_bot" variable
nginx: configuration file /etc/nginx/nginx.conf test failed

# nginx.conf 

user  www-data;
worker_processes  320;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;
events {
    worker_connections  1024;
}
http {
sendfile off;
directio 2m;
ssi on;
tcp_nodelay on;
types_hash_max_size 2048;
server_tokens off;
client_body_buffer_size    128k;
client_max_body_size 200M;
connection_pool_size  256;
client_header_buffer_size 4k;
large_client_header_buffers 4 32k;
request_pool_size  4k;
output_buffers   4 32k;
postpone_output  1460;
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
fastcgi_read_timeout 300;
fastcgi_send_timeout 300;
server_names_hash_max_size 256000;
server_names_hash_bucket_size 4096;

# Open File Cache
open_file_cache          max=4096 inactive=5m;
open_file_cache_valid    5m;
open_file_cache_min_uses 2;
open_file_cache_errors   on;

##DDoS setup
include /etc/nginx/blacklisted_ips.conf;
include /etc/nginx/cloudflare_settings.conf;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    keepalive_timeout  65;

#Gzip seting

  gzip on;
  gzip_http_version  1.1;
  gzip_disable "msie6";
  gzip_comp_level    6;
  gzip_min_length    256;
  gzip_proxied       any;
  gzip_vary          on;
  gzip_types  application/atom+xml application/x-javascript  application/json application/rss+xml application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/svg+xml image/x-icon tex$

# Brotli Settings
brotli on;
    brotli_comp_level 6;
    brotli_static on;
    brotli_types text/plain text/css application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript image/x-icon image/vnd.microsoft.icon image/bmp image/svg+xml;

 include /etc/nginx/ddos/*.conf;
 include /etc/nginx/sites-available/*;
}

**Comment by hostingfuze** [comment]
solved , add in nginx.conf 

include /etc/nginx/conf.d/botblocker-nginx-settings.conf;
include /etc/nginx/conf.d/globalblacklist.conf;

**Comment by mitchellkrogza** [comment]
@hostingfuze this bug has been fixed in latest releases I also have tests running on each build now to confirm includes are done in the correct place.
