### ISSUE TITLE
Can We Have a whitelist-user-agents.conf to Allow Some UA Blacklisted by Default

### ISSUE THREAD

**Issue by oldcai** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#225]
I'm trying to update the code regularly, but I've commented some of the `bad bots`, some of them brings real traffic to my site.
But it would be overwritten if I update this blocker maybe.

Lines I've commented:

```
        #"~*\bsogouspider\b"            3;
        #"~*\bSogou\ web\ spider\b"             3;
        #"~*\bSosospider\b"             3;
```

These bots are for 2 widely used Chinese search engines in mainland China, as Google is blocked there.

And, thanks for your awesome project.

**Comment by ScrewLooseDan** [comment]
Have you looked into using the `bots.d/blacklist-user-agents.conf`?  Despite the name, it should also allow you to whitelist any desired user agent, take a look at the comments of the file for further details:
```
# Even though this file is called blacklist-user-agents, as mentioned it can also be used to whitelist user agents
# By adding them below and setting the 3; to 0; this will permanently whitelist the User-Agent.
```

**Comment by oldcai** [comment]
@ScrewLooseDan 
Thank you for pointing that out.
It would be clearer if it can be put into the document.

**Comment by mitchellkrogza** [comment]
There was some bugs with this @oldcai @ScrewLooseDan which have been fixed and throughly tested in latest versions. You can over-ride anything now even block Googlebot outright if you don't like it.
