### ISSUE TITLE
Education Networks of America IP considered Spam

### ISSUE THREAD

**Issue by Globegitter** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#227]
Hi, 
first of all thanks for this great nginx extenstion, it has been very useful to us. In the last update we saw the IP 96.4.178.4 was added to the list, which seems to be associated with Education Networks of America, a company providing internet to schools and libraries. How come this has landed on the list?

**Comment by mitchellkrogza** [comment]
Sorry for very late reply to this issue. Lots of changes in progress and review of blacklisted IP's in the workflow. Will be addressed.
