### ISSUE TITLE
Global "Block Everything" option

### ISSUE THREAD

**Issue by zjagust** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#228]
I apologize if this was already addressed in some of the previous issues, and if it was, is there a global option to block everything?

Let me explain. Let's say I have a wiki page with business procedures in it and only my employees know the URL to wiki. Unfortunately wiki needs to be public; a VPN or adding entries to local hosts files is not an option. So I would like to see a global option that would block all access to that wiki page unless one knows a direct URL. Is this possible with Nginx Bad Bot Blocker?

**Comment by itoffshore** [comment]
you could [password protect the page](https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-nginx-on-ubuntu-14-04) & force the login page to be over `ssl`

it is probably also a good idea to have your `internal` wiki on a separate `subdomain`

**Comment by mitchellkrogza** [comment]
I agree with @itoffshore

You could also limit access to that url by allowing only your IP's access to the wiki and that's also easy to achieve in a location block but password protected access through SSL is best option

**Comment by zjagust** [comment]
Thanks guys, you can close this issue.

Just to mention, after I did some reading, I have two options which I find acceptable regarding this; first one is pretty simple. I can set up my sites in some "permanent maintenance mode" where first get will set 503 status which will tell bots not to index my sites. Second one; I will setuup OpenVPN and configure my sites to be available only over VPN connection.
