### ISSUE TITLE
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)

### ISSUE THREAD

**Issue by nsgoyat** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#229]
Hello there,

First of all, thanks a ton for the ultimate automated solution for blocking bad bots. Recently, I installed this script using the official steps provided on the main page.

**But there is just one issue.** 

As per the official thread, curl -A “Xenu Link Sleuth/1.3.8” http ://yourdomain.com or curl -I https ://yourdomain.com -e http ://zx6.ru should output the following line:

`curl: (52) Empty reply from server`

But in my case, there is the following output:

`curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)`

Am I doing something wrong or missing anything?

**Comment by mitchellkrogza** [comment]
Hi @nsgoyat is there any chance you are using Cloudflare?

**Comment by nsgoyat** [comment]
Hey Mate,
Yes, I am using Cloudflare but just for DNS purpose. All services from Cloudflare are disabled. The site is paused so it just serves as a DNS manager.

The SSL certificate is generated using acme.sh

**Comment by nsgoyat** [comment]
Also, I am using Custom Nginx with additional extensions and patches like Cloudflare Dynamic TLS Patch, HPACK Patch etc.

**Comment by mitchellkrogza** [comment]
Sorry for the late reply. Have you checked your Nginx logs for the 92 error? If you do not find the 92 error in local logs then it's happening elsewhere. If you find the error in your logs it may give a clue as to what is wrong
