### ISSUE TITLE
Everything installed but will not block any bots

### ISSUE THREAD

**Issue by Lockcuff** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#230]
Hello, I have installed per the directions, which seemed very easy, but I am not able to get a successful blocking test. Everything appears to be in order, but will not work. 
What can I look for to fix it? 
Thanks

**Comment by Lockcuff** [comment]
Hey, Sorry for the delay, just saw your answer. 
Here is the nginx.conf https://pastebin.com/njxWaJfy
Here is the vhost.conf https://pastebin.com/qP3QHDXW
I have multiple v-host configs that are identical to this. 
Is the reference in the wrong block maybe?
Thanks

**Comment by mitchellkrogza** [comment]
Add the two includes at line 14 of your vhost(s) and restart Nginx

**Comment by Lockcuff** [comment]
I did that to just one vhost and still am able to crawl the URL with a 200.

**Comment by mitchellkrogza** [comment]
I never looked at your Nginx.conf properly you have the wrong includes there. 

Please comment out line 145 and 146 and place these two include files in the /etc/nginx/conf.d folder
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/tree/master/conf.d 

Then make sure you have an /etc/nginx/bots.d folder with the following files in there

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/tree/master/bots.d

**Comment by Lockcuff** [comment]
Ok, now we're cooking with fire. How did I get so off on the config?
I am now seeing an returned code of 92 over 52, should this be correct?
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)

**Comment by mitchellkrogza** [comment]
👍🏻52 is the error you want, the 92 error seems to occur with people using Cloudflare and also an SSL setup that's not 100% correct or is conflicting somewhere. Best is to check your error log on that vhost to see if anything can be revealed. We've had some users with the 92 response each on with different setups but the blocker still works regardless by dropping the connection.

**Comment by Lockcuff** [comment]
Ok, It appears I get the #92 code only when using curl from Mac, when I use another server I get the #52 code. I think I am working as I should be now. I will watch logs and look or the blocks. 
Thanks

**Comment by mitchellkrogza** [comment]
Excellent thanks for reporting back so it seems macOS is the culprit. So glad its all working now.... Enjoy
