### ISSUE TITLE
Fail2ban nginx log failregex does not work.

### ISSUE THREAD

**Issue by ecsumed** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#235]
Here's a sample log line (notice the date): 
`<redacted-ip> - - [12/Dec/2018:10:47:04 +0000] "GET / HTTP/1.1" 444 0 "-" "Mozilla/5.0 (compatible; AhrefsBot/5.2; +http://ahrefs.com/robot/)"
`

failregex from repo filter.d that does not work: `failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) .* \S+\" (?:403|444) .+$`

**Comment by itoffshore** [comment]
@mitchellkrogza - feel free to amend the `PR` as you see fit.

These are the regexes I use on my servers

**Comment by ecsumed** [comment]
@itoffshore I ended up using:
`failregex = ^<HOST> \- \S+ \[.*\] \"(GET|POST|HEAD) .* \S+\" (?:403|444) .+$`

But yours is fine as well.
