### ISSUE TITLE
Mojeek

### ISSUE THREAD

**Issue by ricardoscotia** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#237]
Mojeek is a legitimate bot and is privacy sensitive, I don't see how it fits into any "bad bot" narrative.

https://www.mojeek.com/bot.html

(I'd mentioned this on your other repo for Apache bot blocking, thanks for acknowledging it's not a bad bot on there, though it's also still marked as one)

**Comment by mitchellkrogza** [comment]
@ricardoscotia Please send a PR on this file > https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/_generator_lists/bad-user-agents.list
