### ISSUE TITLE
How to install with Engintron

### ISSUE THREAD

**Issue by Nirjonadda** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#24]
Please let me know that How to install with Engintron?

https://github.com/engintron/engintron

**Comment by mitchellkrogza** [comment]
I've never seen or used Enginetron, you would simply have to follow the instructions for a normal nginx setup dropping the globalblacklist.conf and botblocker-nginx-settings.conf into /etc/nginx/conf.d and then dropping the other include files (as per instructions) into /etc/nginx/bots.d ..... then setup your default nginx host that is doing the proxying to do the include statements.

include /etc/nginx/bots.d/blockbots.conf;
include /etc/nginx/bots.d/ddos.conf;

Then you will need to make sure you main nginx.conf file has the default include statement

include /etc/nginx/conf.d/*;

do an nginx -t

and it it passes it should be loaded and running

**Comment by mitchellkrogza** [comment]
You can email me your main /etc.nginx/nginx.conf file and your default vhost.conf files (/etc/nginx/sites-available) to me on mitchellkrog@gmail.com and I will have a look for you.

**Comment by Nirjonadda** [comment]
@mitchellkrogza I am doing Installation with this Instructions, Does this Installation Instructions are correct? Also I will sending you /etc/nginx/nginx.conf and /etc/nginx/conf.d/default.conf

````
cd /etc/nginx/conf.d
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/globalblacklist.conf -O globalblacklist.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/botblocker-nginx-settings.conf -O botblocker-nginx-settings.conf
sudo mkdir /etc/nginx/bots.d
cd /etc/nginx/bots.d
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/blockbots.conf -O blockbots.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/ddos.conf -O ddos.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/whitelist-ips.conf -O whitelist-ips.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/whitelist-domains.conf -O whitelist-domains.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/blacklist-user-agents.conf -O blacklist-user-agents.conf
````
But I did not understanding where are adding vhost following lines, Where the vhost config file location in cPanel?

````
include /etc/nginx/bots.d/blockbots.conf;
include /etc/nginx/bots.d/ddos.conf;
````

**Comment by mitchellkrogza** [comment]
Thanks @Nirjonadda I got your email, will have a look and get back to you later today.

**Comment by Nirjonadda** [comment]
@mitchellkrogza Thanks, Does my Installation Instructions are correct?

**Comment by mitchellkrogza** [comment]
@Nirjonadda got your email have replied. Your installation instructions are correct, just look at the modified default.conf file I sent you which shows you where to do the includes in the vhost.

**Comment by mitchellkrogza** [comment]
Please report back to me so we can make sure you are up and running with the blocker 😄

**Comment by Nirjonadda** [comment]
@mitchellkrogza I will sending my /etc/nginx folder, Please let me know that where we need adding include vhost lines and let me know the files name with lines number.

**Comment by mitchellkrogza** [comment]
Sent you the modified nginx folder back. Have a look and let me know.

**Comment by Nirjonadda** [comment]
@mitchellkrogza Getting error with TESTING NGINX CONFIGURATION.

````
[root@na bots.d]# sudo nginx -t
nginx: [emerg] "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/conf.d/botblocker-nginx-settings.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed
[root@na bots.d]#
````

**Comment by mitchellkrogza** [comment]
Try with my latest zip I sent through.

**Comment by mitchellkrogza** [comment]
Remove line 31 from your nginx.conf and reload.

Remove this line form nginx.conf

`    server_names_hash_bucket_size  512;`

**Comment by mitchellkrogza** [comment]
Sent you a new zip with the fix to nginx.conf

**Comment by Nirjonadda** [comment]
@mitchellkrogza nginx are not loading.

````
[root@na bots.d]# sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
[root@na bots.d]# sudo service nginx reload
Redirecting to /bin/systemctl reload  nginx.service
Job for nginx.service invalid.
[root@na bots.d]#
````

**Comment by mitchellkrogza** [comment]
The blocker is working, I tested against your sites from outside, check your email.

What Distro of Linux are you running?

**Comment by mitchellkrogza** [comment]
What does `systemctl status nginx` give you ???

**Comment by Nirjonadda** [comment]
@mitchellkrogza I do Purge cache & temp files from nginx then reload the nginx service but blocker are not working.

````
[root@na bots.d]# sudo service nginx reload
Redirecting to /bin/systemctl reload  nginx.service
[root@na bots.d]# curl -A "googlebot" http://mysite.com
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://www.mysite.com/">here</a>.</p>
</body></html>
[root@na bots.d]# curl -A "80legs" http://mysite.com
curl: (52) Empty reply from server
[root@na bots.d]#
````

**Comment by mitchellkrogza** [comment]
It is working !!

`curl -A "googlebot" http://mysite.com` gives you the full output of the page which is correct as we do not block googlebot.

`curl -A "80legs" http://mysite.com` gives the correct response `curl: (52) Empty reply from server` which is the nginx 444 error we issue to bad bots.

so it IS working 100%

**Comment by mitchellkrogza** [comment]
Tests from my desktop in South Africa. It is working 100% as it should.

```curl -A "masscan" https://www.yoursite.com
curl: (52) Empty reply from server```

```curl -A "80legs" https://www.yoursite.com
curl: (52) Empty reply from server```

```curl -I https://www.yoursite.com -e http://zx6.ru
curl: (52) Empty reply from server```

```curl -A "googlebot" https://www.yoursite.com
<!DOCTYPE html>
<html id="XenForo" lang="en-US" dir="LTR" class="Public NoJs GalleryLazyLoader uix_javascriptNeedsInit LoggedOut Sidebar  Responsive pageIsLtr hasWelcomeBlock  hasTabLinks  hasSearch   is-sidebarOpen hasRightSidebar is-setWidth navStyle_0 pageStyle_0 hasFlexbox" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
......................................
```

**Comment by Nirjonadda** [comment]
How to work Preventing Website Scraping? How can i specifically block a site or any type of bot using by that site to scrap my content. It is scraping my content and publishing as their own.

**Comment by mitchellkrogza** [comment]
This will keep most content scrapers out. If you have any specific one's in your logs please submit them under issues with log excerpts so I can examine them.

There will a new update to the blocker this week which will allow you further customization using include files that do not get overwritten when you update.

for now you can custom blacklist bad bot you like by adding it to /bots.d/blacklist-user-agents.conf

**Later this week, probably tomorrow** there will be a new include file called

**/bots.d/blacklist-referrers.conf** which will allow you block any referrer of your own not on the main blocker list

there will also be a new

**/bots.d/blacklist-ips.conf** which will allow you blacklist your own IP' or ranges that you want to block out for good.

By using the new includes you can customize your blocker as you like and when you pull the updated globalblacklist.conf it will not overwrite what is in your custom include files.

**Comment by mitchellkrogza** [comment]
Now that you have it working you must monitor your logs daily. You will start to see lots of 444 errors in your logs now. It takes a few days before you start seeing how it is protecting you from all the rubbish out there. Remember this is a work in progress as you can see I commit new bad referrers and push out an update almost every second day.

**Comment by mitchellkrogza** [comment]
Closing this issue for now as the blocker is indeed working on your Enginetron system. I will post instructions for other Enginetron users to help them. Please log your other issues regarding bots scraping from your sites as separate issues here with log examples.

`grep 'word' /var/log/nginx/*.log`

**Comment by Nirjonadda** [comment]
@mitchellkrogza One more thing, Does all manual modification remove after doing the Enginetron update? Also does remove /etc/nginx/conf.d/ files?

**Comment by mitchellkrogza** [comment]
Enginetron configuration example introduced in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/03d91fea48d7c97b3f118d312dd0a78df360243d

**Comment by mitchellkrogza** [comment]
I do not know how Enginetron works when you update, never used it. You will have to test and find out if it goes and removes any of your files when you update it. CPanel is NOTORIOUS for doing this but I am not sure with Enginetron.

**Comment by Nirjonadda** [comment]
@mitchellkrogza Yes its remove files and manual modification /etc/nginx/conf.d/botblocker-nginx-settings.conf and globalblacklist.conf with Enginetron update but are not remove /etc/nginx/bots.d/ folder.

**Comment by mitchellkrogza** [comment]
Did it remove the includes from /etc/conf.d/default.conf and /etc/conf.d/default_https.conf?

You could just run the shell install script after you update Enginetron to reget the files for you.
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/install-ngxblocker

I really do not understand these silly Cpanel systems that take Nginx and Apache and completely mess them up.

Just remember if you do run the https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/install-ngxblocker it will wipe out any customizations of your include files so you will have to modify it like below.

```
#!/bin/bash
# Bash Script for Fixing EnginTron after update when it removes files
# Copyright - https://github.com/mitchellkrogza
# Project Url: https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker

# Save this file as /usr/sbin/fix-engintron
# Make it Executable chmod +x /usr/sbin/fix-engintron
# Run it from the command line using sudo /usr/sbin/fix-engintron

# LETS FIX NOW
 
cd /etc/nginx/conf.d
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/globalblacklist.conf -O globalblacklist.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/botblocker-nginx-settings.conf -O botblocker-nginx-settings.conf
exit 0


```

**Comment by Nirjonadda** [comment]
@mitchellkrogza Please let me know from this post: https://github.com/engintron/engintron/issues/523#issuecomment-294527765

**Comment by mitchellkrogza** [comment]
@Nirjonadda thanks I have asked on Engintron what the correct syntax is for doing that. As i said I've never used Enginetron so let me see when @bdtech responds to me on https://github.com/engintron/engintron/issues/523 then I will test and push it out as hopefully a permanent fix to the problem. 

How's the blocker working for you so far?
And Fail2Ban ???

**Comment by mitchellkrogza** [comment]
See fix to custom_rules in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/b43fc03e77ef69e6f31c15eeacaf90cace7030ba please test and report back to me if it work or not.

**Comment by Nirjonadda** [comment]
@mitchellkrogza I have reinstalled Engintron now how to install bot blocker? Please let me know the steps by step introduction.

**Comment by mitchellkrogza** [comment]
@Nirjonadda  For a fix when EnginTron deletes your custom files from /etc/nginx/conf.d/ when you update EnginTron see - https://github.com/engintron/engintron/issues/523

**Comment by ingenuitor** [comment]
It would seem I'm having an issue in Engintron 2.0 as well, how do I restore, as it's failed.  I thought this was a plugin of sorts, it would seem I was wrong about this, it's more complex than I was expecting to get into.  Please advise and thank you...

`Checking Nginx configuration...
nginx: [emerg] "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/conf.d/botblocker-nginx-settings.conf:16
nginx: configuration file /etc/nginx/nginx.conf test failed`
