### ISSUE TITLE
Reopen #238: your solution not good!

### ISSUE THREAD

**Issue by hucste** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#240]
you offer no real solution. Sorry to tell you!

**Comment by itoffshore** [comment]
@hucste - I reviewed your `PR` https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/242

- The main issue is your changes made the helper scripts less readable
- The helper scripts should not try to work around / hide system configuration errors

I you would like to redo your `PR` with the 3 commits I do think are valid you can see [my notes here for rebasing a `PR`](https://it-offshore.co.uk/code/81-alpine-linux-pull-requests-on-github).

**Comment by hucste** [comment]
@zjagust no comment!

@itoffshore thank for your notes. I appreciate. I hope to understand everything correctly. (sorry, for my poor english). 
In few days, i will recreate a new fork of your project, apply your notes and submit a new PR!

**Comment by itoffshore** [comment]
@hucste no problem - I've added some more comments on https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/242 to fix it
