### ISSUE TITLE
Need variable to identify if human or bot

### ISSUE THREAD

**Issue by thious** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#243]
Hi, it may be out of scope but i'd like to route traffic based on the fact that the request is made by a bot or a human.
Actually, default $bad_bot variable is set to 0 and allowed bot sets $bad_variable to 0 too.
Would be helpfull to have a value dedicated to humans requests.

**Comment by mitchellkrogza** [comment]
We treat humans as the default 0 as 0 is the default of allow them through
With the current logic of the blocker you could do something like, crude but it would work if you did it right 

if !0 then seen them here
else
send everyone human or good here
end if
