### ISSUE TITLE
Mediatoolkit bot to agressive

### ISSUE THREAD

**Issue by zjagust** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#245]
Hello,

In a past few days I discovered the following bot being to agressive in its scans. Snippet from the access log follows:

213.186.1.207 - - [12/Jan/2019:08:41:04 +0100] "GET / HTTP/1.1" 200 15561 "-" "Mediatoolkitbot (complaints@mediatoolkit.com)" "-" rt=0.450 uct="0.000" uht="0.400" urt="0.448"
213.186.1.206 - - [12/Jan/2019:08:54:44 +0100] "GET / HTTP/1.1" 200 4648 "-" "Mediatoolkitbot (complaints@mediatoolkit.com)" "-" rt=0.450 uct="0.000" uht="0.452" urt="0.452"
213.186.1.214 - - [12/Jan/2019:09:05:12 +0100] "GET /wp-login.php HTTP/1.1" 200 1123 "-" "Mediatoolkitbot (complaints@mediatoolkit.com)" "-" rt=1.350 uct="0.000" uht="1.348" urt="1.348"
213.186.1.214 - - [12/Jan/2019:09:06:56 +0100] "GET /?feed=rss2 HTTP/1.1" 301 0 "-" "Mediatoolkitbot (complaints@mediatoolkit.com)" "-" rt=0.350 uct="0.000" uht="0.348" urt="0.348"
213.186.1.214 - - [12/Jan/2019:09:06:57 +0100] "GET /feed/ HTTP/1.1" 200 445 "-" "Mediatoolkitbot (complaints@mediatoolkit.com)" "-" rt=0.300 uct="0.000" uht="0.300" urt="0.300"
213.186.4.78 - - [12/Jan/2019:09:15:06 +0100] "GET /?cat=1 HTTP/1.1" 301 0 "-" "Mediatoolkitbot (complaints@mediatoolkit.com)" "-" rt=0.350 uct="0.000" uht="0.352" urt="0.352"
213.186.4.78 - - [12/Jan/2019:09:15:07 +0100] "GET /category/uncategorized/ HTTP/1.1" 200 4793 "-" "Mediatoolkitbot (complaints@mediatoolkit.com)" "-" rt=0.400 uct="0.000" uht="0.400" urt="0.400"
213.186.1.214 - - [12/Jan/2019:09:21:29 +0100] "GET /?feed=comments-rss2 HTTP/1.1" 301 0 "-" "Mediatoolkitbot (complaints@mediatoolkit.com)" "-" rt=0.400 uct="0.000" uht="0.400" urt="0.400"
213.186.1.214 - - [12/Jan/2019:09:21:30 +0100] "GET /comments/feed/ HTTP/1.1" 200 412 "-" "Mediatoolkitbot (complaints@mediatoolkit.com)" "-" rt=0.311 uct="0.000" uht="0.308" urt="0.308"

Below are the IP addresses I managed to pull out from access_log related to bot:

213.186.1.201
213.186.1.206
213.186.1.207
213.186.1.208
213.186.1.213
213.186.1.214
213.186.4.78

**Comment by mitchellkrogza** [comment]
Looks like a fake bot @zjagust I emailed them asking for explanation and got this in return

```
Final-Recipient: rfc822; complaints@mediatoolkit.com
Original-Recipient: rfc822;complaints@mediatoolkit.com
Action: failed
Status: 5.1.1
Remote-MTA: dns; aspmx.l.google.com
Diagnostic-Code: smtp; 550-5.1.1 The email account that you tried to reach does
    not exist. Please try 550-5.1.1 double-checking the recipient's email
    address for typos or 550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1
    https://support.google.com/mail/?p=NoSuchUser n2si4015688qti.226 - gsmtp
```
