### ISSUE TITLE
Include directives fail outside nginx.conf

### ISSUE THREAD

**Issue by ovitech** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#248]
Dear Mitchell,
I'm trying to secure my nginx web server with your bots blocker, however I'm having difficulties getting nginx to load it. I've followed your manual config tutorial and I haven't had any probs
until step 10. 

However because I didn't want to include the 2 directives in nginx.conf , I pasted them in a new file in
/etc/nginx/badbotscall.conf then I tested nginx (all ok), and then I reloaded nginx - all ok as well.

Unfortunately the tests at your step 12 are failing because my domain is not loading the
block lists.  Your advice would be most appreciated. 

My  /etc/nginx/**badbotscall.conf**

    include /etc/nginx/bots.d/blockbots.conf
    include /etc/nginx/bots.d/ddos.conf

My /etc/nginx/**nginx.conf**:

    #user  nginx;
    worker_processes  1;
    #error_log  /var/log/nginx/error.log;
    #error_log  /var/log/nginx/error.log  notice;
    #error_log  /var/log/nginx/error.log  info;
    #pid        /var/run/nginx.pid;
    
    include /etc/nginx/modules.conf.d/*.conf;
    
    events {
    worker_connections  1024;
    }
    http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;
    #tcp_nodelay        on;

    #gzip  on;
    #gzip_disable "MSIE [1-6]\.(?!.*SV1)";

    server_tokens off;

    include /etc/nginx/conf.d/*.conf;
    }
    # override global parameters e.g. worker_rlimit_nofile
    include /etc/nginx/*global_params;

My **Vhost nginx.config** (Actual IP and domain not pasted)

        #ATTENTION!
        #
        #DO NOT MODIFY THIS FILE BECAUSE IT WAS GENERATED AUTOMATICALLY,
        #SO ALL YOUR CHANGES WILL BE LOST THE NEXT TIME THE FILE IS GENERATED.

        server {
        listen xx.xx.xx.:443 ssl http2;

        server_name mydomain.eu;
        server_name mydomain.eu;
        server_name ipv4.mydomain.eu;

        ssl_certificate             /opt/psa/var/certificates/scfnEUzKH;
        ssl_certificate_key         /opt/psa/var/certificates/scfnEUzKH;
        ssl_client_certificate      /opt/psa/var/certificates/scfDJeKgi;

        client_max_body_size 128m;

        root "/var/www/vhosts/mydomain.eu/httpdocs";
        access_log "/var/www/vhosts/system/mydomain.eu/logs/proxy_access_ssl_log";
        error_log "/var/www/vhosts/system/mydomain.eu/logs/proxy_error_log";

        if ($host ~* ^www\.mydomain\.eu$) {
                rewrite ^(.*)$ https://mydomain.eu$1 permanent;
        }

        #extension wp-toolkit begin
        location ~* wp-config.php { deny all; }

        location ~* ".*/cache/.*\\.ph(?:p[345]?|t|tml)" {
                access_log off;
                log_not_found off;
                deny all;
        }

        location ~* "(?:wp-config\\.bak|\\.wp-config\\.php\\.swp|(?:readme|license|changelog|-config|-sample)\\.(?:php|md|txt|htm|html))" {
                return 403;
        }

        #extension wp-toolkit end
        #extension letsencrypt begin
        location ~ ^/\.well-known/acme-challenge/ {
                root /var/www/vhosts/default/htdocs;

                types { }
                default_type text/plain;

                satisfy any;
                auth_basic off;
                allow all;

                location ~ ^/\.well-known/acme-challenge.*/\. {
                        deny all;
                }
        }
        #extension letsencrypt end
        location ~ ^/(plesk-stat|awstats-icon|webstat|webstat-ssl|ftpstat|anon_ftpstat) {
                auth_basic "Domain statistics";
                auth_basic_user_file "/var/www/vhosts/system/mydomain.eu/pd/d..httpdocs@plesk-stat";
                autoindex on;

                location ~ ^/plesk-stat(.*) {
                        alias /var/www/vhosts/system/mydomain.eu/statistics/$1;
                }

                location ~ ^/awstats-icon(.*) {
                        alias /usr/share/awstats/icon/$1;
                }

                location ~ ^/(.*)/(.*) {
                        alias /var/www/vhosts/system/mydomain.eu/statistics/$1/$2;
                }
        }

        location ~ ^/~(.+?)(/.*?\.php)(/.*)?$ {
                alias /var/www/vhosts/mydomain.eu/web_users/$1/$2;
                fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_pass "unix:///var/www/vhosts/system/mydomain.eu/php-fpm.sock";
                include /etc/nginx/fastcgi.conf;

        }

        location ~ \.php(/.*)?$ {
                fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_pass "unix:///var/www/vhosts/system/mydomain.eu/php-fpm.sock";
                include /etc/nginx/fastcgi.conf;

        }

        location ~ /$ {
                index "index.html" "index.cgi" "index.pl" "index.php" "index.xhtml" "index.htm" "index.shtml";
        }

        add_header X-Powered-By PleskLin;

        include "/var/www/vhosts/system/mydomain.eu/conf/vhost_nginx.conf";
        }

        server {
        listen xx.xx.xx.xx:80;

        server_name mydomain.eu;
        server_name www.mydomain.eu;
        server_name ipv4.mydomain.eu;

        client_max_body_size 128m;

        if ($host ~* ^www\.mydomain\.eu$) {
                rewrite ^(.*)$ https://mydomain.eu$1 permanent;
        }

        return 301 https://$host$request_uri;
        }

And finally my **vhost_nginx.conf** (with the permanent nginx custom directives)

        # WORDPRESS PERMALINKS
        if (!-e $request_filename) {
        rewrite ^(.+)$ /index.php?q=$1 last;
        }

        # NGINX Caching - Cache static files for as long as possible
        location ~* .(js|jpg|jpeg|gif|png|css|tgz|gz|rar|bz2|doc|pdf|ppt|tar|wav|bmp|rtf|swf|ico|flv|txt|woff|woff2|svg)$ {
        etag on;
        if_modified_since exact;
        add_header Pragma "public";
        expires max;
        access_log off;
        log_not_found off;
        }

        location = /favicon.ico {
        log_not_found off;
        access_log off;
        }
        location = /robots.txt {
        log_not_found off;
        access_log off;
        }

        ### SECURITY BEGIN ###

        # Restrict access to WordPress dashboard
        location /wp-admin {
        allow xx.xx.xx.xx;
        deny  all;
        }

        # Deny public access to wp-config.php
        location ~* wp-config.php { deny all; }

        # Deny access to plugins folder
        location ~* "^/wp-content/(?!plugins/).*\.php" { deny all; }

        # Deny access to uploads that aren ^ ^ t images, videos, music, etc.
        location ~* ^/wp-content/uploads/.*.(html|htm|shtml|php|js|swf)$ { deny all; }

        # Deny embedding in a frame or iframe
        add_header X-Frame-Options "DENY";

        # Tell browsers that should only be loading website over HTTPS !!!VERY IMPORTANT!!!
        add_header Strict-Transport-Security "max-age=63072000; preload; includeSubdomains; ";

        # Block bots and download agents ##
        # **include mitchellkrogza directives are not accepted here**!

        ## Only allow these request methods ##
        if ($request_method !~ ^(GET|HEAD|POST)$ ) {
        return 444;
        }
        ## Do not accept DELETE, SEARCH and other methods ##

        ## block any attempted XML-RPC requests
        location = /xmlrpc.php {
        deny all;
        }

        ### SECURITY END ###

Thank you.

**Comment by mitchellkrogza** [comment]
@ovitech you've misread the instructions.

This include
```
	# Block Bad Bots
	include /etc/nginx/bots.d/blockbots.conf;
	include /etc/nginx/bots.d/ddos.conf;
``
ONLY gets placed into your vhost configuration (not nginx.conf) the above include must be inside the `server {}` block of every vhost on your server where you want the blocker to operate.

Make sure you also have the two main blocker files in your `/etc/nginx/conf.d/` folder, those are `botblocker-nginx-settings.conf` and `globalblacklist.conf`

Make sure you have all the other includes in your `/etc/nginx/bots.d` folder

**Comment by ovitech** [comment]
@mitchellkrogza Thank you for your quick reply.
I haven't misunderstood your instructions, I am stuck because of an incompatibility between my Plesk and your guide.

I'm on Plesk Onlyx CP and as you've seen from **Vhost nginx.config** (I know that this is the nginx.config that you're reffering to), if I paste the 2 directives there, they will be gone by the next nginx restart.

And if I paste them in vhost_nginx.conf (the only file where Plesk allows me to paste custom nginx directives) then nginx -t won't validate...

So do you understand why I had to use a workaround with that new file /etc/nginx/badbotscall.conf ?
I was hoping that nginx will load the directives from this file, but it doesn't.  
Or if it does, they don't apply to the vhost nginx.conf as well.

**Comment by ScrewLooseDan** [comment]
I believe Plesk uses templates to dynamically create the server config files.  I'm not sure if this applies to Plesk Onlyx CP, but [this document](https://docs.plesk.com/en-US/onyx/advanced-administration-guide-linux/virtual-hosts-configuration/changing-virtual-hosts-settings-using-configuration-templates.68693/) gives some instructions on modifying the Plesk templates.  And, [this page](https://docs.plesk.com/en-US/onyx/administrator-guide/web-servers/apache-and-nginx-web-servers-linux/apache-and-nginx-configuration-files.68678/) shows the file layout.

It doesn't look straightforward as it appears the templates are php files using variables, but that seems like it would be the correct way?

**Comment by mitchellkrogza** [comment]
Ok @ovitech now I understand. I've never written instructions for Plesk yet, I did however write some for the Apache blocker and the same steps should apply for the nginx blocker, give this a read https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/_Plesk_Onyx_Instructions/PLESK-ONYX-APACHE-CONFIGURATION.md

**Comment by mitchellkrogza** [comment]
@ovitech any luck with the above?

**Comment by ovitech** [comment]
Thank you @ScrewLooseDan for your answer. Indeed you are correct and your links to the PLesk documentation are spot on. However while I could do modify my vhost template and integrate the blocklist, I was advised by other Pleskians to not implement @mitchellkrogza solution that way. 

The advice I received was to not implement this solution at all in Plesk (because it requires vhost template custom modification) and to implement the following instead:

1) Config Nginx + custom Fail2Ban actions (+ 1 cronjob to reload Nginx config)  -this (combined) solution uses (custom) Fail2Ban actions to :
- identify offenders and block them for a short period of time via Nginx deny directives,
- identify repeat offenders and block them for a period of one year via Nginx deny directives,
- identify notorious offenders - read: bad IPs that return even after a ban period of one year - via firewall rulesets.

2) Secure Plesk as per Advisor's recommendation 
+ https://support.plesk.com/hc/en-us/articles/115000626925-How-to-secure-a-Plesk-server
+ https://support.plesk.com/hc/en-us/articles/213928005-Plesk-security-best-practices
+ https://docs.plesk.com/en-US/onyx/administrator-guide/plesk-administration/securing-plesk.59464/
+ https://docs.plesk.com/en-US/onyx/advanced-administration-guide-linux/enhancing-security.68755/
+ other custom focused config to balance security & performance.

3) Since I'm on AWS, config AWS Shield and CloudFront:
https://aws.amazon.com/shield/ 

Thank you both for your replies and for sharing your work on blocklists!

**Comment by mitchellkrogza** [comment]
No worries @ovitech just keep in mind none of the above security solutions for Plesk will in any way help you deal with referrer spam or to block our extensive list of bad boots  which is a big part of this blocker. Have a number of people using it on Plesk with said modifications and without problems

**Comment by ovitech** [comment]
I'm sure lots of Plesk admins have successfully integrated your blocklist @mitchellkrogza , however I must mention this small note: **I'm a Plesk newbie**. And if I learned something in all my years of xp in IT, is that I prefer to not do something which may lead to a big _"ups I didn't know that"_ later... 

In a few month's time or maybe a year, when I'm much more confortable customising plesk to my linking (and fully understanding the reprecussions of my customization), then I'll come back to this and integrate your trully brilliant blocklist into my Plesk and Nginx. 

I'm also a user and big fan of @StevenBlack ' blocklist on my machines and I know blocklists work wonders agains ads, spam, bots and other malware. Now I just need to learn some more and then integrate yours into my webserver. 
Cheers!

**Comment by mitchellkrogza** [comment]
It's refreshing @ovitech to see someone not attempt complex things early on that could break their servers, good on you :+1:  you are learning the right way :smile_cat: 

 - also check out our [Ultimate Hosts project](https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist)
