### ISSUE TITLE
Vote for plesk extension?

### ISSUE THREAD

**Issue by Daijobou** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#249]
I use plesk onyx https://en.wikipedia.org/wiki/Plesk to manage my server, like thousand other customers. I'm very interested in this "bad bot blocker"-feature and found this topic on "Feature Suggestions" for plesk:
https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/37023244-block-bad-bots-by-default

So somebody here use plesk too? You can vote for it. ;-)

@mitchellkrogza 
Perhabs https://www.plesk.com/extensions/ is a option for you to generate money or easier integration?

**Comment by Daijobou** [comment]
Maybe you can add a notice for plesk user to use for step 3+4, because this is identical for all plesk servers:
`sudo ./setup-ngxblocker -v /etc/nginx/plesk.conf.d/vhosts -e conf`

default: /etc/nginx/**sites-available**/mydomain1.com.**vhost**
plesk: /etc/nginx/**plesk.conf.d/vhosts**/mydomain1.com.**conf**

**Comment by mitchellkrogza** [comment]
@Daijobou did you ever work through this guide I wrote? 
I wrote it for the Apache version of the blocker but the same would apply for Nginx 

https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/_Plesk_Onyx_Instructions/PLESK-ONYX-APACHE-CONFIGURATION.md

I will re-test my above solution on a Plesk Onyx Nginx installation, will have to see if Plesk will grant me another trial.

**Comment by Daijobou** [comment]
Thanks for this hint! Using nginx makes a little more sense as it is "frontend" and apache is "backend". Stop badbots in nginx have a _little_ performance benefit. Source https://docs.plesk.com/en-US/onyx/administrator-guide/web-servers/apache-and-nginx-web-servers-linux/apache-with-nginx.70837/ (see first image)

And plesk can work with nginx only https://support.plesk.com/hc/en-us/articles/213924385-How-to-switch-on-nginx-only-hosting-without-Apache-for-a-domain-in-Plesk

Thank you very much for your effort! ;-)

**Comment by mitchellkrogza** [comment]
Hope it's all working now. Closing feel free to reopen.
