### ISSUE TITLE
Question: Source for user agent bad bots?

### ISSUE THREAD

**Issue by Daijobou** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#250]
What is the source of bad bots(user agents) See https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/conf.d/globalblacklist.conf#L208 ?
I'd like to know how up-to-date the list is. I found tons of sites with google with tons of user agents from crawlers/scraper, but each list have tons of different agents. Unfortunately, most pages do not give any information where the string(user agent) comes from and which type of bot it is.

**Comment by mitchellkrogza** [comment]
My source comes from real logs and other use contributions. There are indeed many lists out there which list a lot more but many of them are just scraped and never tested or proven to be really bad. We keep this up to date with new bots but the bad bots list grows a lot slower than the bad referrers which grows rapidly.
