### ISSUE TITLE
[INSTALLATION] How to install bot blocker to jwilder/nginx based container

### ISSUE THREAD

**Issue by bilalbayasut** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#251]
**Question #1
I have one docker-compose.yaml file that has `jwilder/nginx` service included there. I wonder what is the concrete and clear step by step to incorporate this amazing bot blocker to it ?

**Question #2
I have tried to follow the step by step installation with custom directory in my project, and that directory will be mounted directly to `jwilder/nginx` container through volume. However what I don't yet understand is `jwilder/nginx` will automatically reload and generate new `default.conf` which will interfere the bot blocker.

**Server
 - ubuntu
 - `jwilder/nginx` based image : latest

Thank you in advance

**Comment by mitchellkrogza** [comment]
Hi @bilalbayasut I've not used jwilder/nginx but I do see on his README there is sections for adding custom configurations that don't get wiped out when you pull his latest containers. See the sections `Per-VIRTUAL_HOST default configuration` and `Per-VIRTUAL_HOST location configuration` which may get you in the right direction.

**Comment by bilalbayasut** [comment]
thanks for your response @mitchellkrogza , however, Im totally newbe here, I have followed all the steps but can't pass the test, is there any step by step explanation for incorporating `jwilder/nginx` here ?

**Comment by bilalbayasut** [comment]
@mitchellkrogza ok I think I have installed it correctly now the only thing Im confusing I think is which conf should I use , `per-virtual host config` or `per-virtual-host location default config` or `per-virtual-host location config` ?

**Comment by bilalbayasut** [comment]
@mitchellkrogza I have solved this issue. Running ultimate botblocker behind `jwilder/nginx` successfully, would like to PR if its fine

**Comment by mitchellkrogza** [comment]
Thanks for the update @bilalbayasut please submit any PR for review as these things always help other users.
