### ISSUE TITLE
[BUG] Referrer Not Blocked Despite Custom Rule

### ISSUE THREAD

**Issue by goxmedia** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#257]
**Describe the bug**
`custom-bad-referrers.conf` is not blocking an entered referrer, in this case, `site.ru`.

**To Reproduce**
Enter the following into `custom-bad-referrers.conf` and check `Top 1000 Referers` report. This referrer still shows up routinely as hitting the site:

> `"~*\bsite\.ru\b"    1;`

**Expected behavior**
Referrer blocked from site.

**Screenshots**
N/A

**Server (please complete the following information):**
 - Amazon Linux 2
 - Nginx Version 1.12.2

**Additional information**
N/A

**Comment by mitchellkrogza** [comment]
Hi @goxmedia I tested now and get the desired result. See below. On the right is the TEST entry in my custom-bad-referrers.conf file, to the left is the test against the server which shows the referrer was blocked.

![Screenshot_2019-05-27_10-05-54](https://user-images.githubusercontent.com/9961541/58405301-653d1700-8067-11e9-949c-139e39382ac3.png)

You can also see my log excerpt showing the `444` error

`- - - mysite [27/May/2019:10:07:56 +0200] "HEAD / HTTP/2.0" 444 0 "http://site.ru" "curl/7.64.1" "-"PORT:443 0.000 - . "GZIP:-"
`
`- - - mysite [27/May/2019:10:08:23 +0200] "HEAD / HTTP/2.0" 444 0 "http://my.site.ru" "curl/7.64.1" "-"PORT:443 0.000 - . "GZIP:-"
`
`- - - mysite [27/May/2019:10:10:07 +0200] "HEAD / HTTP/2.0" 444 0 "http://anything.site.ru/somethingelse.htm" "curl/7.64.1" "-"PORT:443 0.000 - . "GZIP:-"
`

**Comment by goxmedia** [comment]
Hi @mitchellkrogza Thanks for your reply. Yes, my curl shows the same thing as yours. Is it desired behavior then that this domain still shows up in the daily referrer report as hitting the site despite being blocked via `444`?

**Comment by mitchellkrogza** [comment]
Hi @goxmedia yes indeed you can never stop them trying to keep accessing your site(s) but you can take solace knowing the blocker is working and they were issued a `444` meaning they got nothing but an empty reply in return.

**Comment by goxmedia** [comment]
Hi @mitchellkrogza  Thanks. Didn't realize that the bot(s) still hit the log(s) despite being blocked. Thanks for all of your hard work in maintaining this repository. I know it's not easy.

**Comment by mitchellkrogza** [comment]
:+1: Thanks @goxmedia  and glad you are finding the benefits using the blocker.
