### ISSUE TITLE
Link in Main page step 10 not working

### ISSUE THREAD

**Issue by Eckybrazzz** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#263]
Just got a question from somebody else to help him with the installation, but with testing the domains in step 10 are for sale or not working/redirecting.

Should respond with: curl: (52) Empty reply from server
curl -I http://yourdomain.com -e http://100dollars-seo.com
curl -I http://yourdomain.com -e http://zx6.ru

**Comment by mitchellkrogza** [comment]
Hi @Eckybrazzz you need to replace `http://yourdomain.com` with your own domain / web site 
Instructions say `Run the following commands one by one from a terminal on another linux machine against your own domain name. substitute yourdomain.com in the examples below with your REAL domain name` but I will highlight it better for future

**Comment by Eckybrazzz** [comment]
@mitchellkrogza Guess your understood me wrong. For security, I did not post my real domain here,

**Comment by mitchellkrogza** [comment]
Hi @Eckybrazzz a lot of the referrer spamming domains often show for sale, they are still very much in use for spamming, hidden behind the for sale message are scripts running referrer spamming. 

For what reason are you visiting the above sites in a browser?

**Comment by mitchellkrogza** [comment]
@Eckybrazzz here you can see from one of my logs this morning the referrer spamming from 100dollars-seo.com

![100dollars](https://user-images.githubusercontent.com/9961541/59746006-400e8380-9276-11e9-91b4-9e30bd7cc447.png)

**Comment by Eckybrazzz** [comment]
@mitchellkrogza and hide their activities on a subdomain. http://www6.100dollars-seo.com
![image](https://user-images.githubusercontent.com/30936842/59761307-d63cac80-926a-11e9-9e38-5601edfe8e0f.png)
