### ISSUE TITLE
[BUG] update-ngxblocker (Fails reload on Ubuntu 18.04)

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#265]
@itoffshore  in update-ngxblocker `reload nginx.service` is giving me 

```
nginx.service is not active, cannot reload.
Reloading NGINX configuration...[FAILED]
```

In all build tests.

We need to reload rather using `nginx -s reload`

**Comment by itoffshore** [comment]
I've made a 'PR' to fix this - but it does look like build environment does not have `nginx` started
