### ISSUE TITLE
[INSTALLATION] 504 Gateway Timeout

### ISSUE THREAD

**Issue by jacobcrp** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#268]
I believe I have the add-on installed properly.

When I run:
`curl -I https://www.mysite.org -e http://zx6.ru`

I get a `HTTP/1.1 504 GATEWAY_TIMEOUT
Connection: keep-alive` 

message instead of:

- curl: (52) Empty reply from server
- curl: (56) TCP connection reset by peer
- curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

When I comment out the include statements in my nginx.conf Server{} block, it responds with a 200 properly.

It's working... just want to make sure I didn't mess something else up.

Oh, the network is set up like this:

Cloudflare -> AWS ELB -> nginx

Cheers!

**Comment by mitchellkrogza** [comment]
Hi @jacobcrp it depends on how things are configured but you should not be seeing a 504 error. Please can you post your nginx.conf and vhost config.

**Comment by jacobcrp** [comment]
Good morning!

According to this: https://support.cloudflare.com/hc/en-us/articles/218378978-What-should-I-do-after-seeing-a-502-or-504-gateway-error-on-my-site-

A 504 from Cloudflare makes sense. We're blocking the request and Cloudflare is interpreting it as a 504 and responding with that.

I'd paste my nginx.conf and config but they are 5,000 lines long and I don't want to remove all the PII from it.

**Comment by mitchellkrogza** [comment]
Great thanks for letting us know you use Cloudflare, this does indeed make sense. Glad you got it all working.
