### ISSUE TITLE
[User-Agent] (False positive - Matomo app on Android)

### ISSUE THREAD

**Issue by dlford** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#277]
## Paste the full User-Agent String here

```

Appcelerator Titanium/7.5.1 (Pixel 2 XL; Android API Level: 28; en-US;), Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1

```

## Is this for Addition / Removal?

 - [ ] Addition
 - [x] Removal
 - [ ] Keep a watch on this one

## Did the User-Agent request robots.txt first?

 N/A

## Post Log Excerpt to show User-Agent behavior (10-20 lines is enough)

N/A

## Additional information

This is the user agent for the Matomo app on Android, I believe it's being blocked because it matches with the "Titan" user agent that is legitimately blocked in the master list.  In testing if I remove "Titan" from "Titanium" it doesn't get blocked.  Matomo is like a self-hosted Google Analytics in case you've never heard of it.

By the way thank you for sharing your great work!

**Comment by mitchellkrogza** [comment]
Thanks @dlford for reporting this. New false positives tests introduced in BETA and MASTER both passing. MASTER fix will be out in next build so your next update pull will fix this. 

Additional false positive tests busy being added to test false positives on referrers too.

Many thanks for helping make the blocker better.

**Comment by mitchellkrogza** [comment]
:heart: Thank you so much for the :coffee: Ko-Fi @dlford truly appreciated.

**Comment by dlford** [comment]
You are very welcome @mitchellkrogza!

Thank you for the speedy patch! 😁
