### ISSUE TITLE
Version 2.2017.07 - Major Update (Nginx EMERG)

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#28]
Please read updated configuration instructions.
New include files are now required failing which Nginx will EMERG on reload.

**Comment by mitchellkrogza** [comment]
@itoffshore new include files I mentioned have now been introduced in V2.2017.07. 
Maybe you can make the update script check for these files now and if missing download them from the repo.

**Comment by itoffshore** [comment]
ok - will update today

**Comment by Nirjonadda** [comment]
@mitchellkrogza nginx.conf test failed

````
[root@na bots.d]# sudo nginx -t
nginx: [emerg] "map" directive is not allowed here in /etc/nginx/conf.d/globalblacklist.conf:122
nginx: configuration file /etc/nginx/nginx.conf test failed
[root@na bots.d]#
````

**Comment by itoffshore** [comment]
@Nirjonadda - I think you have put the includes in the wrong place.

in my main `nginx.conf` I use:

```
http {
   ...
        # include vhosts after http settings    
        include /etc/nginx/conf.d/default.conf;       
        include /etc/nginx/sites-enabled/*.vhost;

        # Bad Bot Blocker
        include /etc/nginx/conf.d/globalblacklist.conf;
        include /etc/nginx/conf.d/botblocker-nginx-settings.conf;
}

```

the `setup-ngxblocker` script put things in the right place.

**Comment by Nirjonadda** [comment]
@itoffshore Are you using Engintron?

**Comment by itoffshore** [comment]
@Nirjonadda - no - but context for the 2 includes needs to be inside an `http` stanza in the main `nginx.conf`

https://nginx.org/en/docs/http/ngx_http_map_module.html

**Comment by Nirjonadda** [comment]
@itoffshore This is my /etc/nginx/nginx.conf files, please let me know that where we can add?

````
# /**
#  * @version    1.8.3
#  * @package    Engintron for cPanel/WHM
#  * @author     Fotis Evangelou
#  * @url        https://engintron.com
#  * @copyright  Copyright (c) 2010 - 2017 Nuevvo Webware P.C. All rights reserved.
#  * @license    GNU/GPL license: https://www.gnu.org/copyleft/gpl.html
#  */

user nginx;
pid /var/run/nginx.pid;

worker_processes auto;
worker_rlimit_nofile 65535;

events {
    multi_accept on;
    use epoll;
    worker_connections 65535;
}

http {
    ## Basic Settings ##
    client_body_buffer_size        128k;
    client_body_timeout            30s; # Use 5s for high-traffic sites
    client_header_timeout          30s; # Use 5s for high-traffic sites
    client_max_body_size           1024m;
    keepalive_timeout              20s;
    port_in_redirect               off;
    sendfile                       on;
    # server_names_hash_bucket_size  512;
    server_name_in_redirect        off;
    server_tokens                  off;
    tcp_nodelay                    on;
    tcp_nopush                     on;
    types_hash_max_size            2048;

    ## DNS Resolver ##
    # If in China, enable the OpenDNS entry that matches your network connectivity (IPv4 only or IPv4 & IPv6)
    # OpenDNS (IPv4 & IPv6)
    #resolver                      208.67.222.222 208.67.220.220 [2620:0:ccc::2] [2620:0:ccd::2];
    # OpenDNS (IPv4 only)
    #resolver                      208.67.222.222 208.67.220.220;
    # Google Public DNS (IPv4 & IPv6)
    #resolver                      8.8.8.8 8.8.4.4 [2001:4860:4860::8888] [2001:4860:4860::8844];
    # Google Public DNS (IPv4 only) [default]
    resolver                       8.8.8.8 8.8.4.4;

    ## Real IP Forwarding ##
    set_real_ip_from 127.0.0.1;

    # CloudFlare IPs
    # List from: https://www.cloudflare.com/ips-v4
    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 104.16.0.0/12;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 131.0.72.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;
    set_real_ip_from 199.27.128.0/21;
    # List from: https://www.cloudflare.com/ips-v6
    set_real_ip_from 2400:cb00::/32;
    set_real_ip_from 2405:8100::/32;
    set_real_ip_from 2405:b500::/32;
    set_real_ip_from 2606:4700::/32;
    set_real_ip_from 2803:f800::/32;
    set_real_ip_from 2c0f:f248::/32;
    set_real_ip_from 2a06:98c0::/29;

    # Replace with correct visitor IP
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    ## MIME ##
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ## Logging Settings ##
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    ## Gzip Settings ##
    gzip on;
    gzip_buffers 16 8k;
    gzip_comp_level 5;
    gzip_disable "msie6";
    gzip_min_length 256;
    gzip_proxied any;
    gzip_types
        application/atom+xml
        application/javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rss+xml
        application/vnd.geo+json
        application/vnd.ms-fontobject
        application/x-font-ttf
        application/x-javascript
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/opentype
        image/bmp
        image/svg+xml
        image/x-icon
        text/cache-manifest
        text/css
        text/javascript
        text/plain
        text/vcard
        text/vnd.rim.location.xloc
        text/vtt
        text/x-component
        text/x-cross-domain-policy
        text/x-js
        text/xml;
    gzip_vary on;

    # Proxy Settings
    proxy_cache_path /tmp/engintron_dynamic levels=1:2 keys_zone=engintron_dynamic:20m inactive=10m max_size=500m;
    proxy_cache_path /tmp/engintron_static levels=1:2 keys_zone=engintron_static:20m inactive=10m max_size=500m;
    proxy_temp_path /tmp/engintron_temp;

    ## Virtual Host Configs ##
    include /etc/nginx/conf.d/*.conf;
}
````

**Comment by itoffshore** [comment]
@Nirjonadda at the end of `nginx.conf` before the last `}` add:

```
include /etc/nginx/conf.d/globalblacklist.conf;
include /etc/nginx/conf.d/botblocker-nginx-settings.conf;
```
& remove these 2 includes from `/etc/nginx/custom_rules`

**Comment by Nirjonadda** [comment]
@itoffshore what does adding these 2 includes files, If not added then does blocker are working? I am installed with this introduction https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/29

**Comment by Nirjonadda** [comment]
@mitchellkrogza How to check what Version I am using?

**Comment by mitchellkrogza** [comment]
Check the contents of globalblacklist.conf right at the top

```
### **********************************
### THE ULTIMATE NGINX BAD BOT BLOCKER
### **********************************

### Version 2.2017.07

### Last Updated
### Sun Apr 23 10:52:45 SAST 2017
### End Last Updated
```

**Comment by itoffshore** [comment]
@Nirjonadda - you can:

`grep Version /etc/nginx/conf.d/globalblacklist.conf`

**Comment by mitchellkrogza** [comment]
New updates coming will soon use the Release/Build Numbers in the Version Field. Then it will be easier to see a Version Number Like Version: 2017-04-23.Build-365 instead of 2.2017.07 ..... hope to have that fixed soon.

**Comment by mitchellkrogza** [comment]
You can now as of today do `grep 'Updated:' /etc/nginx/conf.d/globalblacklist.conf` and you will get output like below.

`### Updated: Tue Apr 25 11:54:28 SAST 2017`

**Comment by itoffshore** [comment]
fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/37

`update-ngxblocker` & `install-ngxblocker` both now have `-v` switches to print the blacklist version.

**Comment by Nirjonadda** [comment]
@mitchellkrogza Still are not added Build no ? Version Number Like Version: 2017-04-29.Build-404?

**Comment by itoffshore** [comment]
@Nirjonadda - `setup-ngxblocker -v` or `install-ngxblocker -v`

**Comment by itoffshore** [comment]
@Nirjonadda - to see the command line options:

```
update-ngxblocker -h
install-ngxblocker -h
setup-ngxblocker -h
```

**Comment by Nirjonadda** [comment]
@itoffshore @mitchellkrogza command not work. I am using MANUAL INSTALLATION for cPanel with [Engintron Nginx](https://github.com/engintron/engintron)

````
[root@na conf.d]# install-ngxblocker -v
-bash: install-ngxblocker: command not found
[root@na conf.d]#
````

**Comment by mitchellkrogza** [comment]
@Nirjonadda I am busy with some major updates to documentation and TravisCI testing. This unfortunately takes many hours of pre-testing before I put the changes into this live repo.

The new changes to TravisCI will make use of @itoffshore install, update and setup scripts as part of the testing and build environment. Travis will also then write the build number into globalblacklist.conf after each build so once I am done with these updates, probably tomorrow. you will then be able to do a simple `grep 'Release:' /etc/nginx/conf.d/globalblacklist.conf` and `grep 'Updated:' /etc/nginx/conf.d/globalblacklist.conf` to check date last updated and release number.

**Comment by itoffshore** [comment]
@Nirjonadda - `update-ngxblocker -v` or `install-ngxblocker -v`

 to see the command line options:

```
update-ngxblocker -h
install-ngxblocker -h
setup-ngxblocker -h
```

**Comment by mitchellkrogza** [comment]
@Nirjonadda for now simply run `grep 'Updated:' /etc/nginx/conf.d/globalblacklist.conf` from your command line

**Comment by Nirjonadda** [comment]
@mitchellkrogza OK but does AUTO INSTALLATION scripts work for cPanel with Engintron Nginx? Also work AUTO UPDATING in cPanel with Engintron Nginx?

**Comment by itoffshore** [comment]
@Nirjonadda - read the command line options above `^^^`

**Comment by mitchellkrogza** [comment]
@Nirjonadda the setup and install scripts will probably work for Engintron but have not been tested because as I said before CPanel and other systems like Engintron don't follow the same rules of file and directory layouts as standard Nginx and standard Nginx is the focus of this repo although you have seen I do my best to support other systems as much as possible. 

As @itoffshore said you can run the install and setup scripts in dry-mode which does no changes but shows you what changes will be done. 

Then if you are happy with what the output shows you add the -x flag and it will physically make the changes. 

I do believe for Engintron there will be some changes necessary to the install, setup and update scripts as Engintron likes to keep deleting files when you update it. I have asked on Engintron for their documentation regarding their "extras" folder but they have not responded if you can find that I can sooner give you a better working solution for Engintron 

Kind Regards
Mitchell Krog
Visit me at https://mitchellkrog.com

License or buy my images at http://www.gettyimages.com/search/photographer?excludenudity=true&family=creative&page=1&photographer=mitchell%20krog&sort=best#license

**Comment by Nirjonadda** [comment]
@itoffshore not work this command line.

````
[root@na ~]# update-ngxblocker -h
-bash: update-ngxblocker: command not found
[root@na ~]# install-ngxblocker -h
-bash: install-ngxblocker: command not found
[root@na ~]# setup-ngxblocker -h
-bash: setup-ngxblocker: command not found
[root@na ~]#
````

**Comment by mitchellkrogza** [comment]
Did you actually download setup-ngblocker and install-ngblocker to /usr/sbin as per the instructions??? You can't run scripts that do not exist on your system and that's what those errors are saying to you 

Kind Regards
Mitchell Krog
Visit me at https://mitchellkrog.com

License or buy my images at http://www.gettyimages.com/search/photographer?excludenudity=true&family=creative&page=1&photographer=mitchell%20krog&sort=best#license

**Comment by Nirjonadda** [comment]
@mitchellkrogza I am using MANUAL INSTALLATION.

**Comment by mitchellkrogza** [comment]
```
cd /usr/sbin
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/install-ngxblocker -O install-ngxblocker
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/setup-ngxblocker - O setup-ngxblocker
sudo chmod +x install-ngxblocker
sudo chmod +x setup-ngxblocker
```

then run them from /usr/sbin

`./install-ngxblocker`

and 

`./setup-ngxblocker`

**Comment by itoffshore** [comment]
@Nirjonadda - the command line switches are exactly for users like you who need to install the scripts in non standard custom places:

`install-ngxblocker -b /my/custom/path/bots.something -c /my/custom/path/conf.whatever`

& the script will print where it will install the files to. just add `-x` to actually install the files.

& then use `setup-ngxblocker` with your non standard custom locations:

`setup-ngxblocker -b /my/custom/path/bots.something -c /my/custom/path/conf.whatever -m /where/ever/my/main/nginx/conf.is -v /where/ever/my/vhost/files/are -w /where/my/www/files/are`

you can also change the `vhost` file extension the script looks for on the command line if you need to.

again add `-x` to actually make the changes.

for updating run:

`update-ngxblocker -c /my/custom/path/conf.whatever`

to check the blacklist version:

`update-ngxblocker -v`

you just need to test & work out the `cron` jobs for updating

**Comment by mitchellkrogza** [comment]
Thanks @itoffshore for the rundown on using custom paths,  to be honest I'd actually not even read that part of the setup and install scripts command line switches properly. Once again great work on these scripts. I hope to have all documentation updated by tomorrow latest. 

Kind Regards
Mitchell Krog
Visit me at https://mitchellkrog.com

License or buy my images at http://www.gettyimages.com/search/photographer?excludenudity=true&family=creative&page=1&photographer=mitchell%20krog&sort=best#license
