### ISSUE TITLE
[User-Agent]Anomaly:Header:User-Agent - Fake Google Bot 	Cloudflare Specials

### ISSUE THREAD

**Issue by Eckybrazzz** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#282]
"country": "US",
  "ip": "34.228.80.247",
  "protocol": "HTTP/2",
  "method": "GET",
  "user_agent": "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
  "uri": "/",
  "request_duration": 5999872,
  "triggered_rule_ids": [
    "100035"
  ],
  "action": "block",
  "cloudflare_location": "IAD",
  "occurred_at": "2019-07-27T17:18:27.76Z",
  "rule_detail": [
    {
      "id": "",
      "description": "REMOTE_ADDR"
    }

```

## Is this for Addition / Removal?

 - [x] Addition
 - [ ] Removal
 - [ ] Keep a watch on this one

Add any other context about the problem here.
CLOUDFLARE WAF BLOCK

**Comment by mitchellkrogza** [comment]
Thanks @Eckybrazzz I've always wanted to get to building my own list of fake GoogleBots I have many in my logs too but I just don't get time to get to them so these are a great start. I'll be introducing the list for these soon and then we can keep building on it.

**Comment by mitchellkrogza** [comment]
@Eckybrazzz introduced in latest release. Many thanks for the contributions. New additions to the Fake GoogleBots ranges can be now added with Pull Requests on https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/_generator_lists/fake-googlebots.list
