### ISSUE TITLE
Not reloading NGINX when run from cron?

### ISSUE THREAD

**Issue by SanderM2** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#284]
Running update-ngxblocker from the console works perfectly fine, and is restarting nginx after the update.

Running it from cron (as root) it always emails me with the message "NGINX is not running: not reloading NGINX config "

Any ideas?

**Comment by itoffshore** [comment]
[add `PATH` to your `root` crontab](https://stackoverflow.com/questions/2388087/how-to-get-cron-to-call-in-the-correct-paths)

the update script should probably be changed to use full paths from `find_binary()` when I have more time.

**Comment by itoffshore** [comment]
@SanderM2 - if you still have problems feel free to re-open
