### ISSUE TITLE
[BUG] Running ./setup-ngxblocker with the ability to not modify vhosts

### ISSUE THREAD

**Issue by tristanbes** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#286]
Hello,

When managing the vhost with Ansible for example, we shouldn't modify/update the managed vhost.

So when the `./setup-ngxblocker -x` script asks me if I want to update the listed vhost, I reply no ("N"), and then the script exit without executing the rest of what he has to do

Steps not executed: 
```
setup will fix conflict from: 'server_names_hash_bucket_size' in /etc/nginx/conf.d/botblocker-nginx-settings.conf
disabling 'server_names_hash_bucket_size' in: /etc/nginx/conf.d/botblocker-nginx-settings.conf
#server_names_hash_bucket_size 256;
#     ##server_names_hash_bucket_size 128;
 disabled OK

setup will fix conflict from: 'server_names_hash_max_size' in /etc/nginx/conf.d/botblocker-nginx-settings.conf
disabling 'server_names_hash_max_size' in: /etc/nginx/conf.d/botblocker-nginx-settings.conf
#server_names_hash_max_size 4096;
 disabled OK


Whitelisting ip:  xxxxx => /etc/nginx/bots.d/whitelist-ips.conf

Checking for missing includes:

Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt

Nothing to update for directory: /etc/nginx/conf.d
Nothing to update for directory: /etc/nginx/bots.d
Nothing to update for directory: /usr/local/sbin
Setting mode: 700 => /usr/local/sbin/install-ngxblocker
Setting mode: 700 => /usr/local/sbin/setup-ngxblocker
Setting mode: 700 => /usr/local/sbin/update-ngxblocker
```

I think the script should have an option to skip any vhost modification and just do stuff for himself;

**Comment by udanieli** [comment]
Hello @tristanbes, `setup-ngxblocker` does not modify anything unless you set the `-x` option, so what is the desired behavior?

**Comment by itoffshore** [comment]
All of the helper scripts by `default` do nothing without `-x`

**Comment by virgilwashere** [comment]
> Hello @tristanbes, `setup-ngxblocker` does not modify anything unless you set the `-x` option, so what is the desired behavior?

He's wanting to make changes to the system, so `-x` is OK, but _**doesn't**_ want to update the vhost config files.

**Comment by tristanbes** [comment]
Yes, that's exactly that; sorry for the delay;
