### ISSUE TITLE
NUBBB Integration with Engintron Nginx Plugin

### ISSUE THREAD

**Issue by Nirjonadda** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#29]
Nginx Ultimate Bad Bot Blocker full integration introduction with [Engintron Nginx](https://github.com/engintron/engintron) on your cPanel/WHM server.

STEP 1:

````
cd /etc/nginx/conf.d
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/globalblacklist.conf -O globalblacklist.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/botblocker-nginx-settings.conf -O botblocker-nginx-settings.conf
sudo mkdir /etc/nginx/bots.d
cd /etc/nginx/bots.d
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/blockbots.conf -O blockbots.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/ddos.conf -O ddos.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/whitelist-ips.conf -O whitelist-ips.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/whitelist-domains.conf -O whitelist-domains.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/blacklist-user-agents.conf -O blacklist-user-agents.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/blacklist-ips.conf -O blacklist-ips.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/bad-referrer-words.conf -O bad-referrer-words.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/bots.d/custom-bad-referrers.conf -O custom-bad-referrers.conf
````
STEP 2:
````
Remove this line from nginx.conf (/etc/nginx/nginx.conf)

server_names_hash_bucket_size 512;
````
STEP 3:
````
Add include line to /etc/nginx/conf.d/default.conf (Lines: 61-62) and /etc/nginx/conf.d/default_https.conf (Lines: 20-21, 57-58, 77-78, 97-98, 117-118) and /etc/nginx/utilities/https_vhosts.php (Lines: 53-54)

include /etc/nginx/bots.d/blockbots.conf; 
include /etc/nginx/bots.d/ddos.conf;
````
STEP 4:
````
TESTING YOUR NGINX CONFIGURATION

sudo nginx -t

If you get no errors then you followed my instructions so now you can make the blocker go live with a simple.

sudo service nginx reload

The blocker is now active and working so now you can run some simple tests from another linux machine to make sure it's working.
````

You need re-do STEP 2, 3 and below STEP after every update of  Engintron !!!

````
cd /etc/nginx/conf.d
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/globalblacklist.conf -O globalblacklist.conf
sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/botblocker-nginx-settings.conf -O botblocker-nginx-settings.conf
````

**Comment by Nirjonadda** [comment]
@mitchellkrogza Please let me know that does my installation steps are correct?

**Comment by mitchellkrogza** [comment]
Did you download the new include files to /bots.d/ ???

Did you download latest globalblacklist.conf file to /conf.d/ ???

Di you put the "2" includes into your default.conf as per the example ???

Did you `sudo nginx -t` ??? ...... did it complain ????

**Comment by Nirjonadda** [comment]
I have all done From yesterday update but today I haven't updated.

**Comment by mitchellkrogza** [comment]
Ok so you did all the updates yesterday and your `nginx -t` was okay ???
and did you do `service nginx reload` ???

Then today if you want to update ALL you do is pull the latest globalblacklist.conf file nothing else. That's the only file that needs to be updated daily.

**Comment by Nirjonadda** [comment]
@mitchellkrogza Yes, I have successfully completed installation with following introduction. Now also updated successfully. I hope this install tutorial will help for [Engintron Nginx](https://github.com/engintron/engintron) user?
````
[root@na ~]# cd /etc/nginx/conf.d
[root@na conf.d]# sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/globalblacklist.conf -O globalblacklist.conf

2017-04-21 21:45:55 (13.1 MB/s) - ‘globalblacklist.conf’ saved [131878/131878]

[root@na conf.d]# sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
[root@na conf.d]# sudo service nginx reload
Redirecting to /bin/systemctl reload  nginx.service
[root@na conf.d]#
````

**Comment by mitchellkrogza** [comment]
Perfect then all you need to do from now is only pull the daily updates of globalblacklist.conf and not any of the other files

**Comment by Nirjonadda** [comment]
@mitchellkrogza How to setup auto updater script?

**Comment by mitchellkrogza** [comment]
Instructions are inside https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/update-ngxblocker

**Comment by mitchellkrogza** [comment]
`cd /usr/sbin`

`sudo wget https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/update-ngxblocker -O update-ngxblocker`

Make it Executable 

`sudo chmod 700 /usr/sbin/update-ngxblocker`

Run it

`sudo /usr/sbin/update-ngxblocker`

add it to cron to run daily at 8am (example):

`00 22 * * * /usr/sbin/update-ngxblocker`

**Comment by ingenuitor** [comment]
Hello guys, do you follow the same guide for Engintron 2+. With many years gone by, I want to make sure I do not bring down the entire working world. Thanks so much, seems like a great much needed solution that even paid solutions don't offer. 

I know this as I have a paid solution and it not even close to this powerful in theory. I can't even add a simple Bot block list, it has to be ip by ip, one by one, "quoted direct from their tech support" No way to import and or just hard overwrite to make lifer easier. 

I'm excited to try this and perhaps drop the other solution, if I can get it to work, while being stable and limit false positives.

**Comment by itoffshore** [comment]
@ingenuitor - it's always recommended to [read the changelog](https://engintron.com/docs/#/pages/Changelog) whenever you upgrade software.

You will probably need to change the configuration paths to point to wherever they live under `/opt/engintron`
