### ISSUE TITLE
[User-Agent] Anomaly:Header:User-Agent - Fake Google Bot

### ISSUE THREAD

**Issue by Eckybrazzz** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#290]
"country": "FR",
  "ip": "164.132.119.83",
  "protocol": "HTTP/1.1",
  "method": "GET",
  "user_agent": "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
  "uri": "/",
  "request_duration": 24999936,
  "triggered_rule_ids": [
    "100035"
  ],
  "action": "block",
  "cloudflare_location": "CDG",
  "occurred_at": "2019-08-08T05:25:58.01Z",
  "rule_detail": [
    {
      "id": "",
      "description": "REMOTE_ADDR"

  "rule_message": "Anomaly:Header:User-Agent - Fake Google Bot",

**Comment by mitchellkrogza** [comment]
Thank you the contribution @Eckybrazzz slowly but surely we are building a nice reliable list of fake Googlebots :+1:

**Comment by mitchellkrogza** [comment]
I wrote a script today which does this automatically from all my server logs and emails me once a day. So will be interesting to see what Fake GoogleBots I find. Going to expand the script tomorrow to include Fake Bing and others too

**Comment by Eckybrazzz** [comment]
Well, that would be great. I hope it can scan the log files of each domain, as my log files are separated from each other.
/home/nginx/domain1/log
/home/nginx/domain2/log
......
......

**Comment by mitchellkrogza** [comment]
@Eckybrazzz yes it is in fact very easy. 

You can even start right now to start collecting the Google and Bing Data as follows.

Add the following code snippet to every web site's main `Location /` block.

```
    # LOG All GoogleBots to File
    if ($http_user_agent ~* googlebot) {
        access_log /var/log/nginx/googlebots.log findbots;
    }
    # LOG All BingBots to File
    if ($http_user_agent ~* bingbot) {
        access_log /var/log/nginx/bingbots.log findbots;
    }
```

Then in your nginx.conf add the log format for findbots

```
	log_format  findbots  '$remote_addr - $host - $http_user_agent';
```

Then reload nginx and you will quickly see all your web sites now log all IP's of everything claiming to be Googlebot or Bingbot into those two log files. 

NOTE: The Log File contains Geniune and Fake Bots

My script then performs the rest of the magic from these logs.

**Comment by mitchellkrogza** [comment]
REF: #291
