### ISSUE TITLE
How to disable IP blocking

### ISSUE THREAD

**Issue by jeroenpraat** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#292]
How do I disable IP blocking? 

I found out that users of my site have problems accessing it via Tor Browser and this tool is the problem. I only need this for the (scrape and search) bots blocking, although anti-DDoS is also good to have.

**Comment by mitchellkrogza** [comment]
I'll have a look at making an option to switch off IP blocking. For now use the latest globalbacklist.conf disable any auto updating and switch all IP entries from their value of 1; to 0; a simple sed / awk can sort that for now until I can try figure out if we can have an on off switch

**Comment by jeroenpraat** [comment]
Thanks!

**Comment by mitchellkrogza** [comment]
Morning @jeroenpraat I should have known I had made things like this easy from the onset and indeed I did.

All you need to do is simply edit your blockbots.conf file and change this section as follows.

```
if ($validate_client) {
  return 200;
}
```

That will disable IP blocking by returning 200 OK to all IP's declared.

You can then re-enable daily updates as the updates do not ever modify the blockbots.conf file

Please test and confirm this sorts out your problems.

**Comment by jeroenpraat** [comment]
Perfect! Thanks!

**Comment by jeroenpraat** [comment]
Unfortunately there is now another problem. Sometimes (not always) the Tor Browser wants to download a 0 byte BIN file. See screenshot. 

I had to disable this blocker again to give people access via the Tor Browser.

![15c476d7f866d2dd](https://user-images.githubusercontent.com/41594439/62838847-bbdaea00-bc81-11e9-9881-48ea7515166b.png)

**Comment by mitchellkrogza** [comment]
Can you post all the log lines from start to finish of one connection from a TOR browser so I can see the request sequence and what may cause that.

**Comment by jeroenpraat** [comment]
Unfortunately Tor Browser didn't produce any helpful log.

**Comment by mitchellkrogza** [comment]
I mean your log from Nginx, TOR session start until Nginx responds with the BIN file.

**Comment by jeroenpraat** [comment]
OK, that wasn't clear to me. I only get one line in the access log, not in the error log. It's not a PHP site, but a Ruby on Rails site (a Mastodon server). Here is an example:

`144.217.166.26 - - [12/Aug/2019:22:40:16 +0200] "GET / HTTP/2.0" 200 98 "-" "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"`

I noticed that 144.217.166.26 is indeed the last IP in the Tor circuit.

**Comment by mitchellkrogza** [comment]
OK @jeroenpraat I have managed to replicate it.  Busy testing for a workaround.

**Comment by mitchellkrogza** [comment]
OK @jeroenpraat the correct way to disable any part of the blocker is as follows. For your case to disable the IP blocking change the section of blockbots.conf as follows.

```
if ($validate_client) {
  #return 444;
}
```

Just comment out the return line, thats it. Same applies for other sections of blockbots.conf

**Comment by jeroenpraat** [comment]
@mitchellkrogza Thank you for your help! Great that you could replicate it. This workaround works great. I tested it many times, so this is resolved. Thanks again!
