### ISSUE TITLE
Just installed and the first thing it blocks is a legitimate Google bot

### ISSUE THREAD

**Issue by svpn** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#3]
Nevermind, this was a mistake, the block was from something else.

**Comment by mitchellkrogza** [comment]
No problem, glad you found what was wrong. I was very careful creating this to make 100% sure nothing Google or Bing ever gets blocked. Hope the script is working well for you.

**Comment by svpn** [comment]
It's very helpful, as is the fail2ban stuff.  I greatly appreciate you sharing it, thanks!

**Comment by mitchellkrogza** [comment]
That's great to hear. Enjoy it and feel free to submit any bad bots or referers of your own that you find in your own logs.
