### ISSUE TITLE
[BUG] setup-ngxblocker doesn't work on /sites-enabled

### ISSUE THREAD

**Issue by TheITJuggler** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#327]
BUG: setting -v /etc/nginx/sites-enabled does not find vhosts

Reproduce:

# /usr/local/sbin/setup-ngxblocker -v /etc/nginx/sites-enabled

Configure every file above as a vhost ? [Y/N] : n

whereas

# /usr/local/sbin/setup-ngxblocker -v /etc/nginx/sites-available
/etc/nginx/sites-available/default
/etc/nginx/sites-available/static.theitjuggler.com.conf
/etc/nginx/sites-available/store.fouracresstudio.com.conf
/etc/nginx/sites-available/www.theitjuggler.com.conf

## Expected behavior

Pointing setup-ngxblocker to _/sites-enabled_ should enable ngxblocker ONLY on enabled vhosts, not configured vhosts, and arguably could be considered a more optimal default. Regardless, manually setting _/sites-enabled_ does not list / find `enabled' vhosts at all.

## Server (please complete the following information):
 
 - Operating System: 

 - [X] Ubuntu
 - [ ] Alpine
 - [ ] Arch Linux
 - [ ] Debian
 - [ ] CentOS
 - [ ] Fedora
 - [ ] Deepin
 - [ ] Windows
 - [ ] Other

- Specify Exact Version of OS: 

Linux ssdnodes-16790 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - Nginx Version [post output of sudo nginx -v]

nginx version: nginx/1.16.1

Paste output of `sudo nginx -V` here (paste in between the ```     ``` markers)

```
nginx version: nginx/1.16.1
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-4jYSyN/nginx-1.16.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-mail=dynamic --with-mail_ssl_module --add-dynamic-module=/build/nginx-4jYSyN/nginx-1.16.1/debian/modules/http-auth-pam --add-dynamic-module=/build/nginx-4jYSyN/nginx-1.16.1/debian/modules/http-dav-ext --add-dynamic-module=/build/nginx-4jYSyN/nginx-1.16.1/debian/modules/http-echo --add-dynamic-module=/build/nginx-4jYSyN/nginx-1.16.1/debian/modules/http-upstream-fair --add-dynamic-module=/build/nginx-4jYSyN/nginx-1.16.1/debian/modules/http-subs-filter
'''
 - Other Environments [include Version information]
-  [X] None
 - [ ] Plesk
 - [ ] CPanel
 - [ ] Synology NAS
 - [ ] Other
 - Specify Other / Specific Version Information Here: 

 - Any other applicable log / error messages that may help us to help you.

```

Paste any log / error messages here (paste in between the ```     ``` markers)

```

## Additional information
VPS

**Comment by itoffshore** [comment]
This is not a bug

You can manually set the `vhost` file extension at the top of the helper script

alternatively `setup-ngxblocker` needs to be run with `-e conf` to find vhost files with a `.conf` extension rather than the default `.vhost`

This is shown in the error message when no `vhost` files are detected

It is also shown when running the helper script with `--help`
