### ISSUE TITLE
No entries in initial config files?

### ISSUE THREAD

**Issue by sburkett** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#333]
Hi all! Running the latest version (I guess) ... V4.2020.01.1925. I just followed the automated install instructions on the README.md here. No errors during the install process.

So, I looked at one of the config files (`nginx/bots.d/blacklist-user-agents.conf`), and I don't see any actual entries in it. Just what looks like the boilerplate comments, etc. Did I miss a step, or is this normal? 

Thanks!

**Comment by mitchellkrogza** [comment]
Hi @sburkett that file and others in the bots.d folder are for your own customization of the blocker. So blacklist-user-agents.conf serves as both a custom **white & blacklist** of any user agents you DO or do NOT want to allow. Even if something is allowed in my defaults, you can override it in this file, so if you don't like Googlebot for some reason, adding in this file would block it. Similarly if something is blocked in my defaults, whitelisting it in this file will override that.

**Comment by sburkett** [comment]
Ok, I think I understand. So the package doesn't come with any sort of pre-packaged blocked user agents, etc? So I would need to construct those myself, if I understand things correctly, right? Thanks!

**Comment by mitchellkrogza** [comment]
Yes it does - all these lists - https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/tree/master/_generator_lists are the defaults of what is blocked, allowed or limited. 

These are what can be over-ridden using the include files in bots.d allowing full customization if you disagree with anything that is restricted / allowed by default.

**Comment by sburkett** [comment]
Ah ok, I was just a bit confused as I didn't see them in the conf files directly. Makes sense now, Thanks!

**Comment by mitchellkrogza** [comment]
These are the totals of what is blocked by default.
![2020-01-07_13-32](https://user-images.githubusercontent.com/9961541/71892666-35540700-3152-11ea-978f-ee155d3fcd37.png)
