### ISSUE TITLE
[INSTALLATION] (set up whitelist-ips)

### ISSUE THREAD

**Issue by Tealk** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#337]
Hello,

thanks for a great job.
Do I have to enter all subdomians in the whitelist-domains.conf or is it automatically a wildcard entry?

**Comment by mitchellkrogza** [comment]
If you use setup-ngxblocker it should do it all for you otherwise yes make sure all your domains are whitelisted.

**Comment by Tealk** [comment]
Unfortunately, I can't use the setup, and I like to set them all manually so that I can see what is happening.

Ok then I write down all my domains, thanks for the quick answer.

**Comment by Tealk** [comment]
So I just did the tests which can be found under STEP10. I get on all 6 tests respond with 200 OK.

The setup script does not show anything that I have forgotten.
```
./setup-ngxblocker -e conf
Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt

** Dry Run ** | not updating files | run  as 'setup-ngxblocker -x' to setup files.


Checking for missing includes:

Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt

Nothing to update for directory: /etc/nginx/conf.d
Nothing to update for directory: /etc/nginx/bots.d
Nothing to update for directory: /usr/local/sbin
Setting mode: 700 => /usr/local/sbin/install-ngxblocker
Setting mode: 700 => /usr/local/sbin/setup-ngxblocker
Setting mode: 700 => /usr/local/sbin/update-ngxblocker
```
In each vhost I have inserted the following:
```
	include bots.d/ddos.conf;
	include bots.d/blockbots.conf;
```
