### ISSUE TITLE
False Positives / Incorrectly Blacklisted Domains?

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#34]
If you ever find any false positives or blacklisted domains that you believe should not be blacklisted on this blocker please list them separately as issues here explaining why they should not be on the blocker and they will be investigated and promptly removed if found to be valid removals.

Unfortunately this list started over a year ago which was originally based on a few other lists which did contain a few false positives. Most have been ironed out over the past few months thanks to issues noted on this and other repo's I run or contribute to. 

The original list from where this began had a mere 200+ listings which now has grown into over 3800+ strong which has been built day by day through monitoring of my servers logs of 18 very busy web sites. So yes there may be a few remnants from the original list which do not belong here. I have spent into the thousands of hours building this blocker and maintaining this list.

It is NOT the intention of this blocker to block out valid domains and services and I maintain a very clean list which is also regularly tested for dead domains and expired domains which are also removed every now and again to keep the list clean and functional as it should be.

So if you find anything being blocked that you believe is unwarranted, kindly list it here under issues and the matter will be looked into and promptly attended to.

**Comment by saschadd** [comment]
hi mitchell,

"~*suche\.t\-online\.de" 	1; 

should be removed because it is the site of a common german ISP who sets his homepage as the starting page in the browser which causes the people to use their search site and get to the resulting page with this referrer. They also provide an modified browser which might also send this referrer.
I had this issue now and got it solved by removing this line from the list.

**Comment by mitchellkrogza** [comment]
Thanks @saschadd fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/8d22368e64bef297b74f236fda06b24818195b98 👍

**Comment by mitchellkrogza** [comment]
@saschadd Please add any further false positives as their own issue, it helps us to keep track of the removals through the Issues system. Thanks for contributing and helping 👍

**Comment by miraserver** [comment]
Mail.ru Bot - its russian search engine with usual bot, he not very active so i dont think block him
all YandexBot and Yandex service use agents - its most popular search engine in Russia so also not any reason for limit 2; i think here can be 0; (allowed).

I am not sure but why here is not possible use exception list?
if i change globalblacklist.conf - iv lost uptodate function.
So how i can make exception list for good bots?
