### ISSUE TITLE
Not getting Emails

### ISSUE THREAD

**Issue by RealSuprim** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#342]
Hi there,

For some reason I am not getting any emails to my account. This is what it looks like on my setup 

```
MAILTO=support@mydomain.net
15 3 * * 7 certbot renew --post-hook "service nginx restart"
00 22 * * * sudo /usr/local/sbin/update-ngxblocker -e support@mydomain.net

00 08 * * * tail -10000 /var/log/nginx/mydomain-access.log | awk '$11 !~ /google|bing|yahoo|yandex|mywebsite.net/' | awk '{print $11}' | tr -d '"' | sort | uniq -c | sort -rn | head -1000 | mail -s "Top 1000 Referers for Mydomain.com" support@mydomain.net

00 08 * * * tail -50000 /var/log/nginx/mydomain-access.log | awk '{print $12}' | tr -d '"' | sort | uniq -c | sort -rn | head -1000 | mail -s "Top 1000 Agents for Mydomain.net" support@mydomain.net
```

Thanks

**Comment by itoffshore** [comment]
To diagnose this issue send an email from a `shell` manually & check your mail logs:

`mail -s "Top 1000 Agents for Mydomain.net" support@mydomain.net`

**Comment by RealSuprim** [comment]
hmm for some reason my port 25 and port 487 are blocked. I contacted my service provider and they said it is open on their side and told me to check on server side firewall but I don't use any firewall except this ultimate bot blocker. Could it have blocked my port?

Thanks

**Comment by mitchellkrogza** [comment]
Hi @RealSuprim not possible at all. The blocker does nothing to block any ports whatsoever.

**Comment by RealSuprim** [comment]
Hi mittchell,
Yes for some reason looks like it is installed. I don't remember adding it but while using this command `sudo iptables -S`

It did give me the ips.

How do i delete this iptables firwall?

Thanks

**Comment by mitchellkrogza** [comment]
I do not advise disabling it. Rather learn to configure it and open the ports you need and close the ones you do not need.

But for now if you want to disable it > https://www.cyberciti.biz/faq/turn-on-turn-off-firewall-in-linux/

**Comment by itoffshore** [comment]
@RealSuprim - if you are using gmail as your `relay` you probably want something like

`iptables -A OUTPUT -p tcp --dport 587`

Note port `587` (TLS) not `487`

- if you are using Ubuntu read up on `ufw`
- if on Centos lookup `firewalld`

**Comment by RealSuprim** [comment]
Hi @itoffshore  this is what I get when I put `sudo iptables -S `command. I am really sorry guys I am new to all this and struggling.
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N f2b-nginx-botsearch
-N f2b-nginx-limit-req
-N f2b-ssh
-N f2b-sshd
-A INPUT -p tcp -m multiport --dports 80,443 -j f2b-nginx-botsearch
-A INPUT -p tcp -m multiport --dports 80,443 -j f2b-nginx-limit-req
-A INPUT -p tcp -m multiport --dports 22 -j f2b-ssh
-A INPUT -p tcp -m multiport --dports 22 -j f2b-sshd
-A INPUT -p tcp -m multiport --dports 22 -j f2b-sshd
-A OUTPUT -p tcp -m tcp --dport 25 -j LOG --log-prefix "mail connection"
-A OUTPUT -p tcp -m tcp --dport 25 -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 587 -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 25 -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 587 -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 25 -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 587 -j ACCEPT
```

Thanks

**Comment by RealSuprim** [comment]
I am using zoho mail service

**Comment by itoffshore** [comment]
you need to look at the logs of whatever you use to send mail from your web server
