### ISSUE TITLE
Update script returning error

### ISSUE THREAD

**Issue by cesar-castro** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#35]
Hello Mitchell,

Update script (b919876) is returning an error on line 82:

./update-ngxblocker: 82: local: --: bad variable name

Can you please look into it?

Thanks in advance,

Cesar

**Comment by mitchellkrogza** [comment]
@itoffshore can you have a look into this?

**Comment by itoffshore** [comment]
yes which distro ?

**Comment by mitchellkrogza** [comment]
@itoffshore I just tested latest update-ngxblocker on Ubuntu 16.04 and get same error.
`
./update-ngxblocker: 82: local: --: bad variable name`

**Comment by itoffshore** [comment]
ok - give me a little while to install an ubuntu lxc container - it's ok with an `ASH` shell in Alpine Linux:

```
Connecting to raw.githubusercontent.com (151.101.192.133:443)
globalblacklist.conf 100% |*******************************|   129k  0:00:00 ETA


 * Reloading nginx configuration ... [ ok ]

Emailing report to: 
```
perhaps it's due to `bash`

**Comment by mitchellkrogza** [comment]
I am using bash ad my default shell, still gives me `82: local: --: bad variable name` my Ubuntu installs are all standard

**Comment by itoffshore** [comment]
change line 1 to `/bin/bash` - ubuntu's `/bin/sh` points to `dash` which does not seem to support `getopts`

**Comment by itoffshore** [comment]
I'll re-write the scripts to use `getopts` for the menu which all shells should support

**Comment by cesar-castro** [comment]
I'm using _bash_ on a _Ubuntu 16.04_ box, and it's now working like a charm after changing sh to bash on line 1.

Thank you @itoffshore  and @mitchellkrogza!
:-)

**Comment by mitchellkrogza** [comment]
Yip can confirm changing it to `/bin/bash` works fine again

**Comment by itoffshore** [comment]
will fix the scripts to use `getopts` & send a new `PR` later on today

**Comment by mitchellkrogza** [comment]
Thanks Stuart 👍

**Comment by mitchellkrogza** [comment]
Confirmed fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/312ee8bdb567bce45b0da6ee9ce5bb3c8ed605c4
