### ISSUE TITLE
Not working while Nginx is configured with Google PageSpeed

### ISSUE THREAD

**Issue by MrJohnDo** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#354]
**Test fails, returns 200 for bot request.**

<img width="1214" alt="Screen Shot 2020-02-12 at 11 33 08 AM" src="https://user-images.githubusercontent.com/44501274/74307633-d8b8bd00-4d8b-11ea-8518-0dc5603e50d0.png">

**Comment by MrJohnDo** [comment]
Im using Certbox to manage SSL certificates.

**Comment by MrJohnDo** [comment]
### Fixed It### 

The problem was in vhost config file.

The default configuration goes to server block managed by Certbot.

 include /etc/nginx/bots.d/ddos.conf;
 include /etc/nginx/bots.d/blockbots.conf;

This has to be moved to your own server block.


<img width="1125" alt="Screen Shot 2020-02-12 at 11 54 14 AM" src="https://user-images.githubusercontent.com/44501274/74308671-cc822f00-4d8e-11ea-8cb5-d6c6d6471bfc.png">
<img width="1679" alt="Screen Shot 2020-02-12 at 11 55 15 AM" src="https://user-images.githubusercontent.com/44501274/74308682-d4da6a00-4d8e-11ea-9ab6-969a639ec7e2.png">

**Comment by itoffshore** [comment]
I used to use `certbot` - but now use `getssl` which is pure `shell`
