### ISSUE TITLE
error installing + still seeing AhrefsBot and SemrushBot requests coming in

### ISSUE THREAD

**Issue by dblado** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#36]
I am still seeing AhrefsBot requests coming in. I haven't added AhrefsBot to my robots file. I thought these conf additions would take care of it?
```
[26/Apr/2017:15:56:26 +0000] "GET /vendor/abx-engineering-inc/reviews/ HTTP/1.1" 444 0 "-" "Mozilla/5.0 (compatible; AhrefsBot/5.2; +http://ahrefs.com/robot/)" "164.132.161.58"

[26/Apr/2017:15:58:33 +0000] "GET /locations/indio-ca/pallets/ HTTP/1.1" 444 0 "-" "Mozilla/5.0 (compatible; SemrushBot/1.2~bl; +http://www.semrush.com/bot.html)" "46.229.168.70"
```
I tried using the scripts to do the install, but got errors:
```
$ sudo ~/install-ngxblocker 
Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt

** Dry Run ** | -x or --exec to download files

awk: {$1="",$2=""; print}
awk:       ^ syntax error
Nothing to update for directory: /etc/nginx/conf.d
awk: {$1="",$2=""; print}
awk:       ^ syntax error
Nothing to update for directory: /etc/nginx/bots.d
```

I went through the manual installation.

**Comment by mitchellkrogza** [comment]
The requests will always still come in, but note your server is issuing them with a 444 response code which simply drops the connection. That's how the blocker works. You cannot stop anybody trying to access your site but when they do and they are blacklisted Nginx simply drops the connection immediately and they do not even reach your site. So to those sites trying to access your site it appears to them hat either your site is down or offline. So rest assured the blocker is doing the job it is designed to do. Now have a look at the fail2bam filter and action I wrote which monitors your logs for excessive 444 and 403 errors and then bans them at firewall level too.

**Comment by dblado** [comment]
thx...didn't notice the 444 response in there
