### ISSUE TITLE
Add From: address to Mail

### ISSUE THREAD

**Issue by RudyStebih** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#369]
Hello,

Is it possible to add a 'From:' address to the Mail line in the 'update-ngxblocker' file. For example:

mail -s 'Some Subject' -r 'First Last <you@example.com>' $EMAIL

As I'm using AWS SES, I need to send the 'From:' email address along with the mail packet for authentication.

Maybe also add a '-f' flag to set the 'From:' address from the command line.

I've already updated my copy and things are working well.  I just thought this might come in handy with someone else.

Cheers,
Rudy

**Comment by itoffshore** [comment]
the latest `update-ngxblocker` should work now with `-f` switch
