### ISSUE TITLE
[BUG] Whitelisting User Agents don't work and still get blocked with 444

### ISSUE THREAD

**Issue by disaster123** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#372]
## Describe the bug

A customer is using the service from Host-Tracker.com but the service is blocked with 444 in the nginx Logfile.

## To Reproduce

Setup an Account at Host-Tracker.com and let it visit your website.

## Expected behavior

I should be able to whitelist HostTracker with:
"~*(?:\b)HostTracker(?:\b)"         0;

inside 
/etc/nginx/bots.d/blacklist-user-agents.conf

Paste any log / error messages here (paste in between the ```     ``` markers)
just replaced some hex code with XXXX

```
37.221.113.21 - - [15/Apr/2020:20:05:13 +0200] "GET / HTTP/1.1" 444 0 "http://www.host-tracker.com/UptimeGraph/Graph/2ae3e3c2-d111-4a34-XXXX-9362e70bd2d9" "Mozilla/5.0 (compatible;HostTracker/2.0;+http://www.host-tracker.com/)"
```

@mitchellkrogza any way to whitelist these?

**Comment by disaster123** [comment]
I've the same problem with whitelisting:
```
"~*(?:\b)SISTRIX(?:\b)"         0;
```

but log still says:
```
X.A.Y.X - - [15/Apr/2020:20:19:48 +0200] "GET / HTTP/2.0" 444 0 "-" "Mozilla/5.0 (compatible; SISTRIX Optimizer; Uptime; +https://www.sistrix.com/faq/uptime)"
```

tested with:
```
 curl -A "Mozilla/5.0 (compatible; SISTRIX Optimizer; Uptime; +https://www.sistrix.com/faq/uptime)" https://domain.com
```

**Comment by mitchellkrogza** [comment]
Morning @disaster123 whitelisting does work and all over-rides are fully tested during every build - here you can see Sistrix being whitelisted perfectly - https://travis-ci.org/github/mitchellkrogza/nginx-ultimate-bad-bot-blocker/jobs/675311633#L7195-L7196 and host-tracker.com https://travis-ci.org/github/mitchellkrogza/nginx-ultimate-bad-bot-blocker/jobs/675311633#L7730-L7731

**Comment by disaster123** [comment]
Ah OK Sistrix did not work due to nginx map cache i only did a reload instead of restart.

Regarding Host-Tracker i tried to whitelist the User Agent - but it seems i need to whitelist the domain or referrer?

**Comment by mitchellkrogza** [comment]
Always need to reload nginx `sudo nginx -t && sudo nginx -s reload`

With host-tracker you will need to whitelist the User-Agent and Referrer/Domain
