### ISSUE TITLE
custom value for bot2_reqlimitip

### ISSUE THREAD

**Issue by disaster123** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#373]
Is there a way to change the request rate for bot2_reqlimitip to a custom value?

**Comment by mitchellkrogza** [comment]
The value are customizable in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/bots.d/blockbots.conf#L56-L57 that file does not get changed during updates.

**Comment by disaster123** [comment]
Ok thanks
