### ISSUE TITLE
[Blacklist-IP] Ithemes Security

### ISSUE THREAD

**Issue by gutitti** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#375]
Hello sir, i found ithemes security plugin using ip for scan website

35.175.205.111
34.229.141.32
52.203.142.240 -> blocked
52.87.213.12 -> blocked
184.73.140.53
18.206.213.51

## Is this for Addition / Removal?
 - [ ] Addition

## Additional information
https://help.ithemes.com/hc/en-us/articles/360007145634-What-Do-The-Malware-Scan-Errors-Mean-

i can't add it to custom whitelist.conf because nginx: [warn] duplicate network "52.87.213.12", value: "0", old value: "1"

so i manually edit globalblacklist.conf, but every update i must re edited again

**Comment by mitchellkrogza** [comment]
Hi @gutitti you should still be able to whitelist, the duplicate entry is a [warn] and not an [emerg] error. Please try whitelist, reload nginx and confirm.
