### ISSUE TITLE
[BUG] (Add a descriptive title here)

### ISSUE THREAD

**Issue by temp12cyber** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#379]
## Describe the bug

the `mail_path` variable not checking correctly in `send_mail` function in the **update script**.

## To Reproduce

....

## Expected behavior

the braces in the if clause should be replaced with curly brackets.

**Comment by itoffshore** [comment]
this was fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/377
