### ISSUE TITLE
How to uninstall this thing?

### ISSUE THREAD

**Issue by Bluscream** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#387]
It breaks my nginx so i want to get rid of it!

**Comment by 9mido** [comment]
I was about to make another issue to ask the same question

**Comment by Bluscream** [comment]
https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/256

**Comment by 9mido** [comment]
@itoffshore 

Thanks for that commit but how do we make a backup and then restore it?

**Comment by dwisiswant0** [comment]
Commit referencing this issue has just been merged, that means if you haven't backed up there won't be an old nginx config file.

**Comment by 9mido** [comment]
What do you mean @dwisiswant0 ? Are you implying that another commit should be made forcing a backup every time before someone tries to install this?

**Comment by dwisiswant0** [comment]
I mean, the backup option for original config file is just released now _(after this issue was made)_. In other words, your original/old config file will be lost if you don't manually prepare the backup. That's what I think, @9mido.

**Comment by itoffshore** [comment]
@9mido - by default the scripts do not change anything - changes have to be forced by the user with `-x` (& the scripts first print the changes that are made during the dry run)

When `setup-ngxblocker` is run now with `-x` it first backs up `nginx` configuration as [shown in the commit](https://github.com/itoffshore/nginx-ultimate-bad-bot-blocker/commit/e7288e4e4aeef2df9318bcbd2bc186eaf0ca292e).

**Comment by mitchellkrogza** [comment]
Never had the blocker ever break any nginx. Each build is tested against all versions from 1.10 > mainstream including config files of all different formats from different linux distributions. A simple `nginx -t` would easily point to where it was misconfigured.

**Comment by Bluscream** [comment]
Haven't you seen the issue i referenced?

**Comment by mitchellkrogza** [comment]
@Bluscream yes, did you see how many commits and tests spanning several days were added to fix that initial issue? Without a copy of your original nginx.conf file from your OS (unmodified) so I can add it to the tests it's very hard to provide any fix.

These are the current config files against which setup-ngxblocker is tested on every single build - https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/tree/master/.dev-tools/setup-ngxblocker/original

**Comment by Bluscream** [comment]
the problem maybe is that i don't and can't use .vhost extensions because other software relies on these files differently (webmin)

**Comment by itoffshore** [comment]
all of the scripts can be run with `--help` to show usage:
```
sudo ./setup-ngxblocker --help
setup-ngxblocker: SETUP Nginx Bad Bot Blocker configuration in [ /etc/nginx/nginx.conf ] [ /etc/nginx/sites-available/* ]

Usage: setup-ngxblocker [OPTIONS]
	[ -w ] : WWW path                      (default: /var/www)
	[ -e ] : Vhost file extension          (default: .vhost)
	[ -v ] : Vhost directory               (default: /etc/nginx/sites-available)
	[ -b ] : Bot rules directory           (default: /etc/nginx/bots.d)
	[ -c ] : NGINX conf directory          (default: /etc/nginx/conf.d)
	[ -m ] : NGINX main configuration      (default: /etc/nginx/nginx.conf)
	[ -i ] : Change installer path         (default: /usr/local/sbin/install-ngxblocker)
	[ -l ] : Manual whitelist of domain    (default: none)
	[ -n ] : NO whitelist of .names only   (default: Y)
	[ -d ] : NO insert of DDOS rule        (default: Y)
	[ -z ] : NO configuration of vhosts    (default: configure files in /etc/nginx/sites-available)
	[ -x ] : Actually change the files     (default: don't change anything)
	[ -h ] : this help message

Examples:
 setup-ngxblocker -n    (Whitelist all directory names in /var/www as domains: not just dot.name directories)
 setup-ngxblocker -l domain1.com -l domain2.com (Whitelist these manual domain name args)
 setup-ngxblocker -d    (Do not insert DDOS rule: these may clash with existing 'limit_conn addr' rules)
 setup-ngxblocker       (Don't change anything: display results on stdout)
 setup-ngxblocker -x    (Change / update config files)
```
to use a different vhost extension specifiy it with the `-e` switch - e.g `setup-ngxblocker -e .de -x` (in your particular case)

**Comment by Bluscream** [comment]
not every file has the .de extension:
```
blu@domain:/etc/nginx/sites-enabled $ ls
blacklist2.teamspeak.com     exagear.domain.de  rss.domain.de
blacklist.teamspeak.com      fdroid.domain.de   ts.domain.de
bs.domain.de                mail.domain.de     vrchat.domain.de
default                      domain.de
escapefromtarkov.domain.de  quest.domain.de

```

**Comment by itoffshore** [comment]
read `find_vhosts()` in `setup-ngxblocker` lines `101 - 113`

if no vhost files are found the script gives you the option configure every file as a vhost - run `setup-ngxblocker` **from a proper shell**.

`-e *` does the same thing
```
~/tmp]$ find ./test -type f -name "*.*"
./test/test.com
./test/test.org
./test/test.uk
./test/test.de
./test/test.be

 ~/tmp]$ ls test
default  test.be  test.com  test.de  test.org  test.uk
```
