### ISSUE TITLE
[BUG] nginx: [warn] duplicate network "167.99.233.123", value: "1", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:7893

### ISSUE THREAD

**Issue by marvinhipex** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#388]
## Describe the bug

After the last update of global blacklist we receive the following warning:

**# nginx -t**
nginx: [warn] duplicate network "167.99.233.123", value: "1", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:7893

On the line wee see: 

        167.99.233.123          1; #https://gochyu.com/
        167.99.233.123          1; #https://scanwp.net/

## Server (please complete the following information):
 
 - Operating System: 

 - [ ] Ubuntu
 - [ ] Alpine
 - [ ] Arch Linux
 - [ ] Debian
 - [ x ] CentOS
 - [ ] Fedora
 - [ ] Deepin
 - [ ] Windows
 - [ ] Other

- Specify Exact Version of OS: 

CentOS 7.8

 
 - Nginx Version [post output of sudo nginx -v]

```

nginx version: nginx/1.15.8

```

**Comment by mitchellkrogza** [comment]
Thanks @marvinhipex I also noticed it. Fixed in latest commit due shortly after build completes.
