### ISSUE TITLE
[INSTALLATION] ./install-ngxblocker requires 'pidof'

### ISSUE THREAD

**Issue by weiqj** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#399]
- Operating System: Amazon Linux

sudo yum install sysvinit-tools
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main                                                | 2.1 kB     00:00     
amzn-updates                                             | 3.8 kB     00:00     
No package sysvinit-tools available.
Error: Nothing to do

**Comment by itoffshore** [comment]
`yum provides pidof`

& install the correct package

**Comment by weiqj** [comment]
> `yum provides pidof`
> 
> & install the correct package

I believe it is an Amazon Linux specific issue. The installation breaks with wrong error message.

**Comment by weiqj** [comment]
I just checked the code, 
```
find_binary() {
        local x= path= binary=$1 bin_paths='/bin /usr/bin /usr/local/bin /usr/sbin /usr/local/sbin /root/bin /root/.bin'
```
On Amazon Limux, pidof is located in /sbin, which doesn't seem to be in the list.

**Comment by weiqj** [comment]
I can confirm that adding /sbin to the bin_paths solved the problem.

However, the two include lines below were added to the wrong location. I had to manually correct it.

```
  include /etc/nginx/bots.d/ddos.conf;
  include /etc/nginx/bots.d/blockbots.conf;
```

**Comment by itoffshore** [comment]
the code that controls where the includes are inserted is around line `460` of `setup-ngxblocker`:

`line=$(find_includes $MAIN_CONF sendfile last http first '\}' last )`

different distributions use different style `nginx.conf` so it is difficult to cover every use case
