### ISSUE TITLE
[INSTALLATION] testing - not expected output 

### ISSUE THREAD

**Issue by true2thepen** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#406]
## Describe the bug
Does not work unless added includes are moved to top of server block of vhost files.

## To Reproduce
Follow install as described for automatic install

## Expected behavior
curl should return error(52)
returns Http error 403 instead.

## Server (please complete the following information):
 
 - Operating System: 

 - [ ] Ubuntu 18.04

 
 - Nginx Version [post output of sudo nginx -v]

```
nginx version: nginx/1.14.0 (Ubuntu)

```

Once the includes are moved to top of vhost output from curl returns error 52 as expected. When the includes are at the bottom of the vhost file, they are seemingly ignored as the output returned is the output from WordPress 5.5.3.

**Comment by mitchellkrogza** [comment]
The includes must always precede ANY location blocks.
