### ISSUE TITLE
Avoiding Nginx EMERG errors when Major Updates Take Place / Notifications Mailing List

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#41]
I apologize for some people's auto update scripts having broken in the past week due to a major update that was released that required several new include files to exist in your /etc/nginx/bots.d folder. 

Users that have not updated to the latest release will notice they are getting an Nginx EMERG error on an nginx reload due to the missing new include files.

This was a very necessary and very overdue update and should have been done much earlier in the development stages of the blocker but as they say better late than never. It was not intentional to break anyone's blocker from updating and causing Nginx to EMERG in the process but I knew the new new changes would do exactly that.

I do suggest you please subscribe to the mailing list to be notified of all new updates, builds and any major changes.

Simply send a blank email to **nginx-ultimate-bad-bot-blocker+subscribe@googlegroups.com**
and you will be subscribed to the mailing list, google will send you an email  asking you to confirm your addition so please check for that or you won't actually be added.

Thanks everyone for your patience and understanding of the new changes and how much more power they bring to you as a user of the blocker, allowing you much more self customization  than ever before and even more important your customized include files never get overwritten when pulling the (almost) daily updates of globalblacklist.conf

Thank you all for your support of this project and also to the great work @itoffshore Stuart Cardall is doing to the install, setup and update scripts. Assuring you this blocker will only go from strength to strength.

**Comment by pjv** [comment]
I took a look at the google groups mailing list and (unless I was looking at the wrong thing) it looks like there is a lot of noisy traffic on there with an email being generated for each commit that would make it hard to differentiate what is really important to pay attention to. Or at least make you deal with several extra emails a day that you don't really need to know about.

What about setting up a twitter announcement account for the project and just tweeting out announcements when there is something important for current users to know about?

**Comment by mitchellkrogza** [comment]
Thanks @pjv I agree it is rather noisy. I have turned off git commit and push notifications going to the mailing list and will keep that for major announcements and keep email on that list to a minimum. 

I use my @ubuntu101za account for tweeting out announcements but perhaps I will set up a dedicated one just for the Nginx Bot Blocker and Apache Blocker's. Thanks for your feedback and please stay subscribed to the list as I have removed the email integration hook this morning so it wil not longer be emailing out constantly on commits, pulls and pushes.
