### ISSUE TITLE
Letsencrypt certbot renew fails due to duplicate directive

### ISSUE THREAD

**Issue by logicfish** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#414]
`nginx: [emerg] "server_names_hash_bucket_size" directive is duplicate in /etc/nginx/conf.d/botblocker-nginx-settings.conf:16`

**Comment by mitchellkrogza** [comment]
Just comment out `server_names_hash_bucket_size` in your /etc/nginx/conf.d/botblocker-nginx-settings.conf file
