### ISSUE TITLE
Travis-CI > Github Actions

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#419]
Any members that have migrated any of their travis-ci.org repo's to Github actions?

If so could any of you offer assistance to see how easy it would be for this repo to migrate as Travis-CI is going South which I have been expecting for some time now.

Any assistance appreciated I'm not really into reading through guides and things at the moment as I am busy on some other projects.

**Comment by doomedraven** [comment]
nop, sorry just normal python actions

**Comment by SeePrashanth** [comment]
#425

**Comment by mitchellkrogza** [comment]
Never mind I have figured out actions on another repo so will be moving this one day soon to Github Actions.
