### ISSUE TITLE
[BUG] probe-image-size UA blocked although requesting IP is in whitelist-ips.conf

### ISSUE THREAD

**Issue by baumkirchner** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#433]
## Describe the bug

The UserAgent [**probe-image-size/4.1.1**](https://github.com/nodeca/probe-image-size) is being used by the [BigBlueButton Video Conference System](https://bigbluebutton.org/) (which uses nginx as a reverse proxy) to display its whiteboard, but had been added to the global blacklist some time ago.
Since then the whiteboard ist not displayed correctly as long as the mentioned user agent is not listed in custom whitelist, although the servers IP _from which the requests come_ is listed in the whitelist-ips.conf.
As soon as i add this UA to my custom UA white list, everything is fine.
But i'm wondering because shouldn't the whitelist-ips.conf avoid such problems?
Is it the intended behavior that the global blacklist overwrites the whitelist-ips.conf's settings?

## To Reproduce

- Install **[nginx-ultimate-bad-bot-blocker](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker#linux)** on your BigBlueButton-Server
- Add your server's IP to the whitelist-ips.conf
- Reload nginx's configuration
- Start a BigBlueButton meeting. **The white board will not show up**

- Add _probe-image-size_ to your custom UA white list
- Reload nginx's configuration
- Start a BigBlueButton meeting. **The white board will show up correctly**

## Expected behavior

With an IP whitelisted i expected not to block any requests coming from that IP

## Server (please complete the following information):
 
 - Operating System: 

 - [X] Ubuntu

```16.04```
 
```nginx/1.16.1```

nginx access log
```... HTTP/1.1" 444 0 "-" "probe-image-size/4.1.1(+https://github.com/nodeca/probe-image-size)"```

**Comment by mitchellkrogza** [comment]
Whitelist the UA in addition to the IP add this UA to the blacklist-user-agents file which is a white & blacklist
