### ISSUE TITLE
[Question] No update since 4.2021.06.2438

### ISSUE THREAD

**Issue by bolorino** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#439]
None of my Debian 10.10 servers gets an update after 4.2021.06.2438.

```
# /usr/local/sbin/update-ngxblocker -n

LOCAL Version: 4.2021.06.2438
Updated: Mon Jun 21 15:32:20 SAST 2021

REMOTE Version: 4.2021.06.2438
Updated: Mon Jun 21 15:32:20 SAST 2021

Latest Blacklist Already Installed: 4.2021.06.2438
```
Expected to get the latest release V4.2021.07.2445.

Getting the current globalblacklist.conf in master (V4.2021.06.2438) instead.
```
https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/globalblacklist.conf
```
```
### Version: V4.2021.06.2438
### Updated: Mon Jun 21 15:32:20 SAST 2021
### Bad Referrer Count: 7063
### Bad Bot Count: 615
```
Is there any reason why the globalblacklist.conf wasn't updated after 4.2021.06.2438 yet?

I'm sorry if this is intended and simply there is no public update yet.

Thank you so much.

**Comment by mitchellkrogza** [comment]
Sorry builds were moved from Travis-ci.org to Travis-ci.com and there is clearly something wrong. :cry:  I will look into this tomorrow.

**Comment by mitchellkrogza** [comment]
@bolorino should be fixed now try update please

**Comment by bolorino** [comment]
It is working now.
Thank you very much.
