### ISSUE TITLE
[INSTALLATION]"if" directive is not allowed

### ISSUE THREAD

**Issue by rafalohaki** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#440]
I installed fresh nginx.
Was copy pasting step 1-6
root@vmi547555:/usr/local/sbin# sudo nginx -t
nginx: [emerg] "if" directive is not allowed here in /etc/nginx/bots.d/blockbots.conf:58
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by mitchellkrogza** [comment]
Some default nginx.conf files with different distro's are formatted differently, the setup tool tries to cater for most but it cannot cater for all. Just follow manual installation for such cases.
