### ISSUE TITLE
What does the numerical limit below mean?

### ISSUE THREAD

**Issue by ycolor** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#447]
###	3 = block completely

This setting is the option of nginx?

Why the limit of others is 1
### Note that: 0 = allow 1 = deny

https://github.com/mariusv/nginx-badbot-blocker/blob/master/blacklist.conf

**Comment by mitchellkrogza** [comment]
It was built allowing 1 and 2 to limit certain bots more restrictively than others

**Comment by ycolor** [comment]
Thank you, I have been using it without problems
