### ISSUE TITLE
duplicate network "107.189.14.76"

### ISSUE THREAD

**Issue by cuiyang000** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#453]
In globalblacklist.conf there're 2 lines of 107.189.14.76:

- Line #8474
- Line #9166

**Comment by mitchellkrogza** [comment]
Fix in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/a32c9f3f0c70cb854850bea04be327cbbb8bd21c
