### ISSUE TITLE
[BUG] (Googlebot/2.1 444) [HELP NEEDED]

### ISSUE THREAD

**Issue by MaximeMichaud** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#455]
Hi,

66.249.66.11 - - [09/Jan/2022:05:48:58 +0100] "GET /robots.txt HTTP/1.1" 444 0 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

Thank you :)

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/764771dd1770d4ce20a66b6c3948f318a5a709c1 apologies.

**Comment by MaximeMichaud** [comment]
Thank you :)
