### ISSUE TITLE
[INSTALLATION] Testing using curl, is this error ok?

### ISSUE THREAD

**Issue by prettyvoid** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#456]
Hello,

I managed to install everything successfully but while testing using curl (to make sure bots are being blocked) the error I get is different from the one specified in the installation guide.

What I get is
`curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.`

This is a different error from the ones specified in the guide
```
    curl: (52) Empty reply from server
    curl: (56) TCP connection reset by peer
    curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

Is this OK or does that mean I have something wrong in my setup?

Thanks,

**Comment by mitchellkrogza** [comment]
Yes it looks fine you can see the same (56) error just named differently by your OS. 
Always tail your log file when testing you will see the ```444``` error when bots etc are being dropped.
