### ISSUE TITLE
[INSTALLATION] Im using the manual approach and i have couple questions

### ISSUE THREAD

**Issue by initd0** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#470]
I just want to confirm that im understanding how this program works exactly.

1.
Will it be ok to move the config files in a different dir?
eg.
Placing the 2 config files in a dir like this instead:
```
/etc/nginx/botsConf.d/botblocker-nginx-settings.conf
/etc/nginx/botsConf.d/globalblacklist.conf
```

and including them in nginx.conf like this:
```
include /etc/nginx/conf.d/*.conf;
include /etc/nginx/botsConf.d/*.conf;
```

Since i like having my nginx files a little bit more organized and want to be able to just comment out
`include /etc/nginx/botsConf.d/*.conf;` instead of moving out the configs from `conf.d/` in-case i need to do debugging or tests by disabling BadBotBlocker easily.

Shouldnt have any negative side effects right?

2.
You say that the files from `bots.d/` dir dont need to be updated because its our own custom files, but what if there is a future update in your repo of the structure of them, do we have to copy-paste and move the custom edits we've done into the new files?

3.
It seems `botblocker-nginx-settings.conf` is not part of the update script, should we regularly check to see if this script has an updated version?

**Comment by initd0** [comment]
@mitchellkrogza some kind of feedback please?

**Comment by initd0** [comment]
@mitchellkrogza can you please reply?

**Comment by mitchellkrogza** [comment]
> @mitchellkrogza can you please reply?
You can change both folder locations, the setup script caters for this too, you will just need to add your includes into your vhosts pointing to where you have the files.
