### ISSUE TITLE
[INSTALLATION] (nginx: [emerg] unknown directive)

### ISSUE THREAD

**Issue by hafidzaini** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#472]
installed on FreeBSD 13.0-RELEASE-p11 amd64
blocking script working great
but i get problem when whitelist my own domain.

`nginx: [emerg] unknown directive "~*(?:\b)mywebsite\.com(?:\b)" in /usr/local/etc/nginx/bots.d/whitelist-domains.conf:42`

`~*(?:\b)mywebsite\.com(?:\b) 0; `
not working
`!~* ^(.+\.)?mywebsite\.com$ 0;`
still not working

how's the right regex ?
thank you very much.

![nginx](https://i.imgur.com/Z38qmPz.png)

**Comment by hafidzaini** [comment]
problem solve moving the conf from server block to http block

**Comment by killmasta93** [comment]
hi @hafidzaini im having same issue i put 
` include /etc/nginx/bots.d/whitelist-ips.conf;`

in the nginx.conf below the http block but keep getting the same issue?
