### ISSUE TITLE
python / python-requests

### ISSUE THREAD

**Issue by worldsdream** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#495]
I do see a lot of "python" and "python-requests" on the server. Can this also be added to the list?

## Paste the full User-Agent String here

```

Paste the full User-Agent String here (paste in between the ```     ``` markers)
Example: (serpstatbot/1.0 (advanced backlink tracking bot; http://serpstatbot.com/; abuse@serpstatbot.com)

```

## Is this for Addition / Removal?

 - [X ] Addition
 - [ ] Removal
 - [ ] Keep a watch on this one

## Did the User-Agent request robots.txt first?

 - [ ] Yes
 - [ ] No

## Post Log Excerpt to show User-Agent behavior (10-20 lines is enough)

```

Post log excerpt here (paste in between the ```     ``` markers)

```

**Comment by mitchellkrogza** [comment]
I block these in my own custom blacklist a lot of users may not want this blocked by default. Will consider addition into mainstream and users can whitelist but could break a LOT of people's own web sites who use python internally. For now add to your own custom blacklist.
