### ISSUE TITLE
Qwant blocked

### ISSUE THREAD

**Issue by crumblingwalls** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#5]
Why did you decide to block the Qwant-bot? It's a legitimate search engine which reads and obeys the robots.txt.

**Comment by mitchellkrogza** [comment]
I assume you are referring to Qwantify? Must have lingered in there since my original lists, removed with next Commit coming shortly.

**Comment by eurobank** [comment]
Qwant/Qwantify doesn't read/respect robots.txt.

**Comment by chrisastley** [comment]
I'm having big issues with a group of Useragents/bots that don't respect robots.txt and are crawling the same URL's over and over.

Qwantify
VelenPublicWebCrawler
CCBot
ZoominfoBot
Seekport

They appear to be linked as they all crawl the same handful of pages at the same rates and all ignore robots.txt and I'm often finding 3-4 of the above bots hitting the same page on the same seconds continually.
