### ISSUE TITLE
[User-Agent] Add user-agent dataforseobot to block list

### ISSUE THREAD

**Issue by mapcarta** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#504]
```dataforseobot```

Please add "dataforseobot" to the bad SEO bots list. They have been heavily accessing our site, causing load issues. You already have "dataforseo.com" on your list, but DataForSEO are not minding that one. I have contacted DataForSEO and they replied with the following:

"Thanks for your email. I can see that you have added 'User-agent: dataforseo.com' to your robots.txt. But our bot is called 'dataforseobot'. :)"

Thank you!

**Comment by CyberCr33p** [comment]
`Mozilla/5.0 (compatible; DataForSeoBot/1.0; +https://dataforseo.com/dataforseo-bot)`
