### ISSUE TITLE
[User-Agent] Remove Not rule

### ISSUE THREAD

**Issue by jonathanribas** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#505]
## Paste the full User-Agent String here

```Mozilla/5.0 (Linux; Android 12; Redmi Note 9 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36```

## Is this for Addition / Removal?

Remove rule `Not` https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/_generator_lists/bad-user-agents.list#L320

 - [ ] Addition
 - [X] Removal
 - [ ] Keep a watch on this one

## Additional information

Rule `Not` https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/_generator_lists/bad-user-agents.list#L320 is actually refusing connection to the Redmi Note devices.

**Comment by mitchellkrogza** [comment]
Thanks will look into this I do not remember adding Not as an agent
