### ISSUE TITLE
[ISSUE] Duplicate Networks included in globalblacklist.conf

### ISSUE THREAD

**Issue by H-e-ro** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#510]
## Describe the bug

It is probably not a bug, but on nginx -t after ./setup-ngxblocker -x, I get some warnings about duplicate networks, I won't ignore:

nginx: [warn] duplicate network "138.199.57.151", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:18880
nginx: [warn] duplicate network "143.244.38.129", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:18896
nginx: [warn] duplicate network "195.181.163.194", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:18991
nginx: [warn] duplicate network "5.188.120.15", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:19118
nginx: [warn] duplicate network "89.187.173.66", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:19165

Server is running after installing, but I am not sure, if those duplicates may occurs errors or a conflict anywhere. So I report this as an issue to you.

## To Reproduce

On installing nginx-ultimate-bad-bot-blocker, right behind step ./setup-ngxblocker -x, testing nginx configuration with "nginx -t" these warnings appears.

## Expected behavior

You should notice and solve those conflicts on (probably automatic) creation of the globalblacklist.conf file.

## Screenshots

![2023-03-31 08_25_30-192 168 178 33 - PuTTY](https://user-images.githubusercontent.com/75077979/229042159-3c59159d-aec2-4955-a97a-d835db1ecd10.png)

**Comment by alexlii1971** [comment]
oh, same issue, fixed yet please?

**Comment by mitchellkrogza** [comment]
Not a bug, merely a [WARN] and can be ignored does NOT affect Nginx or the operation of the blocker. Some IP's may be whitelisted and then later blacklisted OR blacklisted and later whitelisted further down the change. This is normal behaviour and changed frequently based on daily bad IP range updates.
