### ISSUE TITLE
Adding useragent & scanners

### ISSUE THREAD

**Issue by infernusec** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#512]
Mozilla/5.0 [en] (X11, U; OpenVAS-VT 21.4.3)
OpenVAS is an opensource scanner project..

There are more scanners that are not blocked yet..
https://hostedscan.com/ (https://hostedscan.com/openvas-vulnerability-scan) (I tested they scanner, his ip is 45.33.88.234)

https://sitecheck.sucuri.net/api/v3/?scan=[URL_TO_SCAN]&clear
https://www.immuniweb.com/websec/

**Comment by mitchellkrogza** [comment]
Thanks will look into this

**Comment by mitchellkrogza** [comment]
Unfortunately VALID Googlebots still use in their UA
```"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/102.0.5005.115 Safari/537.36"```

You will have to block this in your custom blacklist or provide a more detailed UA
