### ISSUE TITLE
nginx: [emerg] unknown directive "20.213.20.213" in /etc/nginx/bots.d/blacklist-ips.conf:96

### ISSUE THREAD

**Issue by serg-avens** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#538]
Hello!  I would like to thank you for such a useful script!
I have an issue with blacklist-ips.conf.
Any help would be very apreciated.

I've read [here](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/102) but wouldn't like to reinstall nginx from the scratch.

After adding the third string into vhost.d file

   ```
  include /etc/nginx/bots.d/ddos.conf;
  include /etc/nginx/bots.d/blockbots.conf;
  include /etc/nginx/bots.d/blacklist-ips.conf;
```

 NGINX doesn't start with message 
``` nginx: [emerg] unknown directive "20.213.20.213" in /etc/nginx/bots.d/blacklist-ips.conf:97```

There is only one uncommented line  "20.213.20.213      1;"

The same error appears when i include the non modified original blacklist-ips.conf, saying "wrong directive" on 
` 38.0.0.0/8                      0;`

 CentOS  nginx version: nginx/1.20.2

**Comment by mitchellkrogza** [comment]
Do not add the include ```include /etc/nginx/bots.d/blacklist-ips.conf;``` it is already loaded in the main blocker file ```conf.d/globalblacklist.conf``` simply make changes to blacklist-ips.conf and reload nginx.

**Comment by serg-avens** [comment]
Thank you very much!
Great script.  The site became very fast after kicking bots out!  MySQL was too overloaded before.
