### ISSUE TITLE
Update script generating error after trying to reload Nginx configuration

### ISSUE THREAD

**Issue by cesar-castro** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#54]
I don't know why, but after I updated the update script to the latest version it fails to reload Nginx configuration. It doesn't happen all the time, so if I run script twice it normally works after the second one. 

Now I set my crontab to run updates three times per day to circumvent this issue. Here goes the output:

1 - _Latest Blacklist Already Installed: 3.2017.06.569_

2 - _Update Available => 3.2017.06.570_

_2017-06-19 11:20:03 URL:https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/conf.d/globalblacklist.conf [154957/154957] -> "/etc/nginx/conf.d/globalblacklist.conf" [1]_

_Reloading NGINX configuration...[FAILED]_

3 - _Latest Blacklist Already Installed: 3.2017.06.570_

Oh well, it looks like the second round did work this time despite the bad output. But it normally doesn't.

And yes, everything is OK with my _nginx.conf_ and _nginx -t_ won't output any error. My environment is an Ubuntu 16.04 box.

Any clue?

Thanks in advance.

**Comment by mitchellkrogza** [comment]
Are you 100% sure you are running the script with sudo ? That's the only
reason it ever fails is when it does not have appropriate rights to reload
Nginx

**Comment by cesar-castro** [comment]
Yup, the update script is run through **crontab** as root.

**Comment by mitchellkrogza** [comment]
Weird, have you checked your syslog for any errors?

**Comment by cesar-castro** [comment]
Yes, and no errors.

**Comment by mitchellkrogza** [comment]
Sure your crontab entry looks like this? `00 */12 * * * sudo /usr/sbin/update-ngxblocker`

**Comment by cesar-castro** [comment]
Do I have to put sudo if I'm running crontab as root? If yes, it was missing. Just included it right now to see how it goes.

**Comment by mitchellkrogza** [comment]
That's how I run it on Ubuntu 16.04 otherwise it fails reloading Nginx. Let me know if it goes ok next time the cron runs.

**Comment by cesar-castro** [comment]
Yup, it worked! Thanks a lot, bro!

**Comment by mitchellkrogza** [comment]
Excellent, glad it's sorted now. Enjoy 👍
