### ISSUE TITLE
END KNOWN BAD IP ADDRESSES in globalblacklist.conf 

### ISSUE THREAD

**Issue by eggercomputerchaos** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#547]
Dear All ,

what is the reason that "END KNOWN BAD IP ADDRESSES" is written in seven lines (line 18565 to 18571) in nginx globalblacklist.conf? 

best

**Comment by mitchellkrogza** [comment]
Just ignore for now they're only comment lines, will fix
