### ISSUE TITLE
Duplicate mappings and directives preventing from using the bad bot blocker configs

### ISSUE THREAD

**Issue by karlisk** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#55]
I wanted to add a layer of security to my NGINX by blocking malicious bots, so I followed the step-by-step instructions provided to set-up the configuration but I'm facing errors every time I try to start my server. Trying to fix one error leads to a new error. My nginx version: nginx/1.10.3.

Some of the console outputs:
`nginx: [emerg] "server_names_hash_max_size" directive is duplicate in /etc/nginx/conf.d/botblocker-nginx-settings.conf:2
nginx: [emerg] limit_req_zone "flood" is already bound to key "$binary_remote_addr" in /etc/nginx/conf.d/botblocker-nginx-settings.conf:3
nginx: [emerg] limit_conn_zone "bot2_connlimit" is already bound to key "$bot_iplimit" in /etc/nginx/conf.d/globalblacklist.conf:5895`

**Comment by mitchellkrogza** [comment]
Please can you post your /etc/nginx/nginx.conf contents here

**Comment by karlisk** [comment]
Sorry to bother you but the issue was solved - I was at fault by having a left-over config that pointed towards the 'config.d/*.conf' resulting in duplicate configs (it was late and I was tired - didn't even notice it at first).

```user www-data;
worker_processes 1;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
error_log /var/log/nginx/nginx_error.log error;

events {
	worker_connections 1024;
	multi_accept on;
	use epoll;
}

http {
	##
	# Server Configs
	##
	include /etc/nginx/mime.types;
	# include /etc/nginx/hashes.conf;
	include /etc/nginx/logging.conf;
	include /etc/nginx/timeouts.conf;
	include /etc/nginx/maps/*.conf;
	include /etc/nginx/http.conf;

	##
	# Bad Bot Blocker
	##
	include /etc/nginx/conf.d/botblocker-nginx-settings.conf;
	include /etc/nginx/conf.d/globalblacklist.conf;

	##
	# Virtual Host Configs
	##
	include /etc/nginx/sites-enabled/*.conf;
}
```

As you might notice, first thing I did was to disable my hashes config, I also moved the bot configs, that were automagically added during the setup process, to be placed before the VHost configs to avoid them being referenced in the VHost configs before they're loaded by NGINX.

**Comment by mitchellkrogza** [comment]
@karlisk great, glad you found the problem. Enjoy. 👍
