### ISSUE TITLE
duplicate network 

### ISSUE THREAD

**Issue by FlowLaGit** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#552]
Hello,

sorry i am not sure if this is a bug or not. 

I get the [warn] message when starting nginx.

2024/02/07 21:01:01 [warn] 2767352#2767352: duplicate network "138.199.57.151", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:18896
2024/02/07 21:01:01 [warn] 2767352#2767352: duplicate network "143.244.38.129", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:18912
2024/02/07 21:01:01 [warn] 2767352#2767352: duplicate network "195.181.163.194", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:19007
2024/02/07 21:01:01 [warn] 2767352#2767352: duplicate network "5.188.120.15", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:19134
2024/02/07 21:01:01 [warn] 2767352#2767352: duplicate network "89.187.173.66", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:19181

LOCAL Version: 4.2024.02.4291
Updated: Wed Feb  7 10:03:06 UTC 2024

REMOTE Version: 4.2024.02.4291
Updated: Wed Feb  7 10:03:06 UTC 2024

Latest Blacklist Already Installed: 4.2024.02.4291

is this a normal behavior?

**Comment by tradenet** [comment]
> Hello,
> 
> sorry i am not sure if this is a bug or not.
> 
> I get the [warn] message when starting nginx.
> 
> 2024/02/07 21:01:01 [warn] 2767352#2767352: duplicate network "138.199.57.151", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:18896 2024/02/07 21:01:01 [warn] 2767352#2767352: duplicate network "143.244.38.129", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:18912 2024/02/07 21:01:01 [warn] 2767352#2767352: duplicate network "195.181.163.194", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:19007 2024/02/07 21:01:01 [warn] 2767352#2767352: duplicate network "5.188.120.15", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:19134 2024/02/07 21:01:01 [warn] 2767352#2767352: duplicate network "89.187.173.66", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:19181
> 
> LOCAL Version: 4.2024.02.4291 Updated: Wed Feb 7 10:03:06 UTC 2024
> 
> REMOTE Version: 4.2024.02.4291 Updated: Wed Feb 7 10:03:06 UTC 2024
> 
> Latest Blacklist Already Installed: 4.2024.02.4291
> 
> is this a normal behavior?

See: https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/548

**Comment by sainikbiswas** [comment]
Hi there, the following IPs below are not a bug but this needs fixing.

138.199.57.151
143.244.38.129
195.181.163.194
89.187.173.66
5.188.120.15

They are listed under "BunnyCDN" as to be allowed and under "Start SEO Analysis Tools" to be blocked in the globalblacklist.conf file if I understand correctly. To fix this remove the ip addresses from BunnyCDN and check using the command 

`nginx -t`

It should fix the problem for now. Here is the latest IP address list from BunnyCDN that you can add in globalblacklist.conf.

[https://bunnycdn.com/api/system/edgeserverlist/](https://bunnycdn.com/api/system/edgeserverlist/)

Hope this helps.

**Comment by tradenet** [comment]
Actually it's working as designed.You might submit a PR if you have a "fix".

**Comment by mitchellkrogza** [comment]
Not a bug please read the README

![Screenshot_2024-03-03-06-56-13-408_com android chrome-edit](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/assets/9961541/21c8e6de-2dbe-4775-91ae-951323e4483d)
