### ISSUE TITLE
https://www.letsencrypt.org (CertBot renewal is being blocked 444)

### ISSUE THREAD

**Issue by arhyneRWU** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#554]
## Paste the full Domain name / Referrer String here

``` 
GET /.well-known/acme-challenge

Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)

Paste the full Referrer String here (paste in between the ```     ``` markers)

```

## Is this for Addition / Removal?

 - [ ] Addition
 - [X] Removal

## Post Log Excerpt to show User-Agent behavior (10-20 lines is enough)

```
 
 [21/Feb/2024:23:11:49 -0500] "GET /.well-known/acme-challenge/ HTTP/1.1" 444 0 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "-"


```

## Additional information

Not sure how long this has been occurring.

**Comment by mitchellkrogza** [comment]
Please paste a full section of log file. The blocker never has and never will block Lets Encrypt thousands of people use this including myself and no such blocking of LE occurs

**Comment by arhyneRWU** [comment]
Hi, I just commented out `deny.conf` in the nginx conf and got it to renew.  

Perhaps the issue is how I have the certbot .well-known pathed my file conf file. 

```
    # Include bot blocker configuration
    include /etc/nginx/bots.d/blockbots.conf;
    include /etc/nginx/bots.d/ddos.conf;
    include /etc/nginx/deny.d/deny.conf;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot/;
    }
```

in deny.conf the root is set up this way:
```
        location /.well-known/acme-challenge {
        allow all;
        default_type "text/plain";
        root         /tmp/letsencrypt;
        autoindex    on;
        }

```

**Comment by mitchellkrogza** [comment]
Closing 
Feel free to reopen if needed
