### ISSUE TITLE
[User-Agent] Axios is a popular http library used in Nodejs

### ISSUE THREAD

**Issue by isieo** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#555]
## Paste the full User-Agent String here

```
axios/1.6.7

```

## Is this for Addition / Removal?

 - [ ] Addition
 - [ X] Removal
 - [ ] Keep a watch on this one

## Did the User-Agent request robots.txt first?

 - [ ] Yes
 - [X ] No

## Additional information

Axios is a popular http library used in Nodejs, i am not sure if its a good idea to block the entire library all together

**Comment by mitchellkrogza** [comment]
Thanks @isieo Calvin, change has been reverted. Users are to use their own custom blacklist to block it should they desire.
