### ISSUE TITLE
[User-Agent] AwarioBot

### ISSUE THREAD

**Issue by robwent** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#560]
## Paste the full User-Agent String here

```

Mozilla/5.0 (compatible; AwarioBot/1.0; +https://awario.com/bots.html)

```

## Is this for Addition / Removal?

 - [ ] Addition
 - [x] Removal
 - [ ] Keep a watch on this one

## Did the User-Agent request robots.txt first?

 - [ ] Yes
 - [x] No

## Post Log Excerpt to show User-Agent behavior (10-20 lines is enough)

```

46.4.108.51 - - [28/Mar/2024:06:11:19 +0000] "GET /yachts-for-sale-by-model/lagoon-450-s/ HTTP/2.0" 200 31238 "-" "Mozilla/5.0 (compatible; AwarioBot/1.0; +https://awario.com/bots.html)"
46.4.108.51 - - [28/Mar/2024:06:11:23 +0000] "GET /yachts-for-sale/pilot-lounge-name-reserved-2/ HTTP/2.0" 200 38904 "-" "Mozilla/5.0 (compatible; AwarioBot/1.0; +https://awario.com/bots.html)"
46.4.108.51 - - [28/Mar/2024:06:11:31 +0000] "GET /yachts-for-sale/riva-ariston/ HTTP/2.0" 200 30524 "-" "Mozilla/5.0 (compatible; AwarioBot/1.0; +https://awario.com/bots.html)"
46.4.108.51 - - [28/Mar/2024:06:11:35 +0000] "GET /yachts-for-sale-by-model/lagoon-450/ HTTP/2.0" 200 31121 "-" "Mozilla/5.0 (compatible; AwarioBot/1.0; +https://awario.com/bots.html)"
46.4.108.51 - - [28/Mar/2024:06:11:38 +0000] "GET /yachts-for-sale/gatsby/ HTTP/2.0" 200 32968 "-" "Mozilla/5.0 (compatible; AwarioBot/1.0; +https://awario.com/bots.html)"

```

## Additional information

A brand monitoring company scanning billions of pages a day: https://awario.com/

**Comment by mitchellkrogza** [comment]
Hi @rogerdz companies that do brand surveillance do thousands of scans on people's sites and are generally considered a nuisance and the intention on this blocker is to block nuisances. 

Companies that also use this data to sell services (see their pricing pages) are again using people's bandwidth and resources to earn money selling a service. Never had any complaints of these being blocked so whitelisting them for your own purposes is as simple as adding their User Agent names to your whitelist 

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/bots.d/blacklist-user-agents.conf

**Comment by mitchellkrogza** [comment]
Brand monitoring bots are no different to SEO company bots all of which are banned and will continue to be banned as they change UA, IP and domain names.

**Comment by robwent** [comment]
Were the comments meant for #559?

I see 2 related useragents in the global blacklist, but maybe they recently changed it?

https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/conf.d/globalblacklist.conf#L182-L183
