### ISSUE TITLE
[INSTALLATION] nginx -t return warn

### ISSUE THREAD

**Issue by mactrash** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#564]
nginx: [warn] duplicate network "138.199.57.151", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:18949
nginx: [warn] duplicate network "143.244.38.129", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:18965
nginx: [warn] duplicate network "195.181.163.194", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:19060
nginx: [warn] duplicate network "5.188.120.15", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:19187
nginx: [warn] duplicate network "89.187.173.66", value: "0", old value: "1" in /etc/nginx/conf.d/globalblacklist.conf:19234

I am new to this, just first try this today

Is this normal, or do I need to do something to fix it?

**Comment by mitchellkrogza** [comment]
Hi @mactrash please refer to the README
![read](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/assets/9961541/2020ac00-f2e4-4588-8655-daca4086fe0e)
