### ISSUE TITLE
Travis Build Errors (In Progress)

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#58]
Travis CI decided to stop playing nice today and started failing on generating the globalblacklist.conf file. Relates to cat and sed errors which did not exist before, perhaps something has changed in Travis CI without users knowing about it?

At the moment a globalblacklist.conf file being generated with no bad bot or referrer information printed into it. 

Working on the issue right now, will have working blocker back on track shortly.

**Comment by mitchellkrogza** [comment]
Reverted all commits to last commit from this morning, all seems ok now. Travis did report issues of "Apt failures" earlier today which is probably what caused this. Those using auto update should get working copy of latest globalblacklist.conf shortly or you can try force an update to make sure you didn't get the empty file version that occured earlier today.

**Comment by mitchellkrogza** [comment]
Will check this again in the morning on my test repo before doing any more updates.

**Comment by mitchellkrogza** [comment]
No updates until Travis fixes their docker containers. Bash has been totally messed up their latest updates to Travis. Any "n" character in the output of any echo or printf statements or even variable name is being seen by Travis as a `\n` line break. What a mess. 

https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch

**Comment by itoffshore** [comment]
:black_large_square: oh dear - one step forward 2 steps back

**Comment by mitchellkrogza** [comment]
Yip, something has gone horribly wrong with Travis. Hope they respond to me
soon.

**Comment by mitchellkrogza** [comment]
@itoffshore, finally found the culprit pushing out new generator scripts tomorrow and updates will commence.

**Comment by mitchellkrogza** [comment]
@itoffshore we are back online, did some major changes to scripts, all tested and working again. Can you believe in the end a simple IFS="\n" in the generate script caused all the headaches. In the end it led to some much better and cleaner scripting, so all good in the end 😄
