### ISSUE TITLE
[INSTALLATION] Improve logs with reason for block

### ISSUE THREAD

**Issue by rsmith4321** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#590]
I noticed in the Nginx connection logs that I can't see what is being blocked, however the firewall is working. Is there a way to add into the logs the reason for the block, such as "fake google bot" etc similar to the way the 8G firewall does? Or, at a minimum, if the log could just say blocked by ngxblocker. It's just hard for me to tell what the blocker is actually doing by looking at the log file. Unless I'm just completely missing something. Thanks! 

Doing some more research, I found a nice way to highlight log entries with a 444 status, I believe those are the ones blocked. It would be nice if there was a way to make a separate log file just for blocked events.
```shell
tail -f /path/to/nginx/access.log | grep --color=always -E '444|$'
```

**Comment by mitchellkrogza** [comment]
Yes grabbing the 444 errors is the only way, there's no easy way whatsoever to intercept the nginx logging system.

Here's a neat one liner that will give you IP - HITS - USER AGENT you will need to adjust the $10 field to whatever field number your 444 falls under in your log format

```sudo awk '$10 == 444 { print $1, "-", $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24 }' /var/log/nginx/my-access.log | sort | uniq -c | sort -rn```
