### ISSUE TITLE
Bad bots are defined recursively in a way that doesn't make sense

### ISSUE THREAD

**Issue by marbens-arch** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#596]
The issue lies [here](https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker?tab=readme-ov-file#bad-bots-are):

> Bad bots are:
> * Bad Referrers
> * Bad User-Agent Strings
> * Spam Referrers
> * Spam Bots and ***Bad Bots***

Bad Bots being defined as Bad Bots doesn't make sense.

**Comment by mitchellkrogza** [comment]
I'm only human 😉 writing docs can lead to things like this. Why not send a PR and contribute by correcting or enhancing the README ?
