### ISSUE TITLE
Google Analytics - Segments Not Saving

### ISSUE THREAD

**Issue by nwentling5** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#60]
Hi Mitchell,

After adding the first "google-exclude-01.txt" to the filter under the segment, Google does not allow me to save the Segment. These are intended to be all under the same Segment, correct? Maybe Google is further reducing the limit for adding keywords/filters to a segment?

**Comment by mitchellkrogza** [comment]
Hi Nic @nwentling5 

Please see the updated instructions in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/blob/master/README.md pushed out this morning.

This now gives you a visual guide to adding the segments.

**Comment by nwentling5** [comment]
Oh. Yep. I misunderstood that part. The guide works perfectly. Thanks for the clarification!

**Comment by mitchellkrogza** [comment]
Perfect and no problem at all. Thanks for reporting it as it helped to improve documentation for other users. So thanks for the issue leading to becoming a contribution 👍 Have a great weekend.
