### ISSUE TITLE
Dots should be escaped

### ISSUE THREAD

**Issue by stefanobaldo** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#61]
I understand that all the regular expressions should have its dots escaped, as follows:

This:
`"~*ico.re"		1;`

Should become this:
`"~*ico\.re"		1;`

The problem is that the "." from the expression is being interpreted as "any single character", and we are getting some false positives, like this:

    curl -I http://xxx -e http://locatellicorretor.com.br
    curl: (52) Empty reply from server

**Comment by mitchellkrogza** [comment]
Thanks @stefanobaldo for reporting this. I can confirm this with a curl test against my site.

```
curl -I https://mitchellkrog.com -e http://locatellicorretor.com.br
curl: (52) Empty reply from server
```

I will push out an update tomorrow after testing escaping the dots fixes it.

**Comment by mitchellkrogza** [comment]
Confirmed, I changed `~*ico.re" 1;` to "~*ico\.re" 1; and now perfect. Will have updated regex formatting shortly and a new version pushed out. Thank for reporting this.


```
curl -I https://mitchellkrog.com -e http://locatellicorretor.com.br
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 Jul 2017 15:20:42 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
```

**Comment by mitchellkrogza** [comment]
@stefanobaldo fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/f0f4af312132c7b82b925b68ddc66777b906fb21 please update and test and let me know.

**Comment by mitchellkrogza** [comment]
I've tested with V3.2017.07.666

```
curl -I https://mitchellkrog.com -e http://ico.re
curl: (52) Empty reply from server
```
and

```
curl -I https://mitchellkrog.com -e http://locatellicorretor.com.br
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 Jul 2017 15:58:18 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding

```

Thanks @stefanobaldo for reporting this.

**Comment by mitchellkrogza** [comment]
@itoffshore note new changes to regex formatting of domains in bad referrers section. Will update other include files and docs tomorrow

**Comment by mitchellkrogza** [comment]
I will log a bug report with Nginx tomorrow as this has always been done according to their docs and examples. I don't think they are aware of the possibility of false positives without escaping dots and special characters.
