### ISSUE TITLE
nginx: [emerg] "if" directive is not allowed

### ISSUE THREAD

**Issue by makorne** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#63]
nginx: [emerg] "if" directive is not allowed here in /etc/nginx/bots.d/blockbots.conf:22

nginx version: nginx/1.6.2

**Comment by mitchellkrogza** [comment]
@makorne that's a very old version of Nginx. This has only been developed and tested on Nginx 1.10.0 > 1.10.3 there is probably missing modules in your version of Nginx.

**Comment by makorne** [comment]
nginx: [emerg] "if" directive is not allowed here in /etc/nginx/bots.d/blockbots.conf:22
nginx: configuration file /etc/nginx/nginx.conf test failed
nginx -v
nginx version: nginx/1.12.1

**Comment by mitchellkrogza** [comment]
Please paste your vhost config(s) here and also your nginx.conf

**Comment by makorne** [comment]
I moved
```
# Bad Bot Blocker
include /etc/nginx/bots.d/blockbots.conf;
include /etc/nginx/bots.d/ddos.conf;
```
inside server block { ... }
and the error was gone!
Thank you!

**Comment by mitchellkrogza** [comment]
Perfect glad you got it sorted. You should use the install, setup and update scripts as they work like a charm and @itoffshore Stuart Cardall did some really excellent work on those. Happy bot and spam blocking and let me know how it goes. Remember to monitor your logs as per my examples on the main README.md file.
