### ISSUE TITLE
globalblacklist.conf directory errors on self compiled nginx

### ISSUE THREAD

**Issue by semaf** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#68]
Thanks for the great solution. There is problem with the globalblacklist.conf file. It seems after an update it gets back the file directories like:

`include /etc/nginx/bots.d/whitelist-domains.conf;`

My installation of nginx is at:

`include /usr/local/nginx/bots/whitelist-domains.conf;`

The directory should be taken from a static file instead to overwrite it everytime after an update.

**Comment by mitchellkrogza** [comment]
Hi @semaf use of the blocker relies on using standard Nginx locations which on almost any distro is in `/etc/nginx`.

This does not matter however for you, even though your Nginx is installed at `/usr/local/nginx` you need to create the folders `/etc/nginx/conf.d` and `/etc/nginx/bots.d` and all the files for the blocker must be in those locations.

Your vhosts includes must then just point to the file locations in `/etc/nginx/bots.d` and your main nginx.conf file must include this line `include /etc/nginx/conf.d/*.conf;`

This way the blocker will always work and always update correctly.

**Comment by mitchellkrogza** [comment]
@semaf I have logged an issue with @itoffshore to get the update-ngblocker to do this automatically using the `-c` parameter. 

see: https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/pull/52

Let's see if he can update the update-ngxblocker to fix this for all users using custom locations.

**Comment by itoffshore** [comment]
there does not seem to be a way to use any of `map set env` to set a variable that can be read in `globalblacklist.conf`.

I will add a `BOTS_DIR` variable & `-b` command line switch to `update-ngxblocker`

**Comment by itoffshore** [comment]
@semaf - you can try the new `update-ngxblocker` at from [my branch](https://github.com/itoffshore/nginx-ultimate-bad-bot-blocker/blob/alpine/update-ngxblocker)

**Comment by mitchellkrogza** [comment]
@semaf latest update-ngxblocker now merged into the main repo. I have tested it and it works 100% when using non-standard nginx locations. I have also added testing of this to the Travis build process before it deploys a new version. 

So all your scripts would be run like this:

`sudo ./install-ngxblocker -x -c /usr/local/nginx/conf.d -b /usr/local/nginx/bots.d`

`sudo ./setup-ngxblocker -x -c /usr/local/nginx/conf.d -b /usr/local/nginx/bots.d`

`sudo ./update-ngxblocker -c /usr/local/nginx/conf.d -b /usr/local/nginx/bots.d -e yourname@youremail.com`

You can see Travis CI pass these tests successfully at: https://travis-ci.org/mitchellkrogza/nginx-ultimate-bad-bot-blocker/builds/257252208

Thanks to you and @itoffshore the project improves once again with an additional round of testing using the command line switches of @itoffshore install, setup and update scripts before a new version is deployed.

👍
