### ISSUE TITLE
update-ngxblocker - Update Email - Mailgun Delivery Failure

### ISSUE THREAD

**Issue by nwentling5** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#70]
Hi again Mitchell,

I noticed on my MailGun logs that I was getting a consistent suppressed or failed delivery of mail:
![image](https://user-images.githubusercontent.com/11902610/28577821-75e579f4-711d-11e7-931f-703b20047cd9.png)

Investigating further, I looked into Step 8 of the installation and realized there was a need to update the email address within `sudo /usr/sbin/update-ngxblocker`.

![image](https://user-images.githubusercontent.com/11902610/28578095-4a5a71b2-711e-11e7-8192-6b29d7df5ffd.png)

It might be a good idea to let others know in Step 8 of this requirement.

**Comment by mitchellkrogza** [comment]
Thanks Nic @nwentling5 I will update docs now.

You should run it as follows **"without"** doing any modifications to the update-ngxblocker file at all.

`sudo /usr/sbin/update-ngxblocker -e yourname@youremail.com`

The `-e` command line switch allows you to specify the email address to send the report to.

Doc update in 5 minutes 👍

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/4509a596e4f9d55b6dd68b2b239332c1f940a7d8

**Comment by nwentling5** [comment]
If you didn't want email notifications, what would the command be?

**Comment by mitchellkrogza** [comment]
`sudo /usr/sbin/update-ngxblocker -n`

**Comment by mitchellkrogza** [comment]
all the scripts have help options, run any of them using `-h` to show the command line parameters

**Comment by mitchellkrogza** [comment]
I will also add that to the docs tomorrow, as you can see, been doing a lot of updates lately.

**Comment by mitchellkrogza** [comment]
@nwentling5 added note about using the `-n` switch into the docs in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/57ce313885696def748d1e331676ec790cc45f50
