### ISSUE TITLE
[emerg] unknown directive "~*xxx" in /etc/nginx/bots.d/xxx.conf:xx

### ISSUE THREAD

**Issue by Synopis** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#72]
I recently installed all of this but for some reason it's not working or at the very least the way it's supposed to.

> This is what was in the access.log after installing everything
[09/Aug/2017:11:23:39 +0200] "HEAD / HTTP/1.1" 200 0 "http://zx6.ru" "curl/7.47.0"

> This is what I tried from ssh
curl -A "Xenu Link Sleuth/1.3.8" http://domain.com:55889
curl: (6) Could not resolve host: http://domain.com
Ubuntu:~# curl -I https://domain.com -e http://zx6.ru
curl: (7) Failed to connect to domain.com port 55889: Connection refused

When i add include /etc/nginx/bots/*.conf to my nginx.conf or add it to my default file in sites.availableI just get a bunch of [emerg] unknown directive "~*xxx" in /etc/nginx/bots.d/xxx.conf:xx whenever i do nginx -t. 
nginx version: nginx/1.13.3

**Comment by mitchellkrogza** [comment]
You can't add the includes within a http {} block which is what you are
doing. The includes must be done within a server {} block on a vhost
configuration. Please read the install instructions carefully or rather use
the install-ngxblocker and setup-ngxblocker scripts which does all the
includes for you in the correct places and also downloads all required
files.

**Comment by mitchellkrogza** [comment]
@Synopis have you managed to resolve this yet ??

**Comment by itoffshore** [comment]
@Synopis - the settings should be something like:

`nginx.conf`(if you do **NOT** have `include /etc/nginx/conf.d/*` inside `http{}`:

```
http {
...
	# include vhosts after http settings
	include /etc/nginx/conf.d/default.conf;
	include /etc/nginx/sites-enabled/*.vhost;

 	# Bad Bot Blocker
	include /etc/nginx/conf.d/globalblacklist.conf; 
 	include /etc/nginx/conf.d/botblocker-nginx-settings.conf;
}
```
__________________________________________

`/etc/nginx/sites-available/my-domain.vhost`:

```
server {
...
        # Bad Bot Blocker
        include /etc/nginx/bots.d/blockbots.conf;
        include /etc/nginx/bots.d/ddos.conf; 

        location / {
....
}
```

**Comment by Synopis** [comment]
@mitchellkrogza Nope. Even uninstalled and reinstalled the entire thing along with nginx. Seems to made it worst

**Comment by mitchellkrogza** [comment]
Is it not because you are redirecting your site to /private/ ? What version
of Nginx? And did you do the CLI install of Ghost? I can send you my
install steps for Ghost. I sent you the real link to my Ghost site and you
can see the blocker works 100% with any curl command testing.

**Comment by mitchellkrogza** [comment]
@Synopis please post output of

`sudo nginx -V`

- please past contents on /etc/nginx.conf here

- please paste your contents of /etc/sites-available/yoursite.conf 

please paste output of 
`
ls -la /etc/nginx`
`
ls -la /etc/nginx/bots.d`
`
ls -ls /etc/nginx/conf.d`

**Comment by mitchellkrogza** [comment]
@Synopis any feedback on this issue?

**Comment by mitchellkrogza** [comment]
No response, closing.

**Comment by robert1112** [comment]
Hi I got the same issue here. Here is the output you requested. THANK YOU SO MUCH.

`2018/07/29 10:10:58 [emerg] 4107#4107: unknown directive "~*\badultgalls\b" in /etc/nginx/bots.d/bad-referrer-words.conf:52
nginx: [emerg] unknown directive "~*\badultgalls\b" in /etc/nginx/bots.d/bad-referrer-words.conf:52
nginx: configuration file /etc/nginx/nginx.conf test failed`

`root@web2:/usr/local/sbin# sudo nginx -V
nginx version: nginx/1.15.2
built by gcc 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
built with OpenSSL 1.1.0f  25 May 2017
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -fdebug-prefix-map=/data/builder/debuild/nginx-1.15.2/debian/debuild-base/nginx-1.15.2=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'`

`root@web2:/etc/nginx# cat nginx.conf
user  nginx;
worker_processes auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
  worker_connections  1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  server_names_hash_bucket_size 64;

  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

  access_log  /var/log/nginx/access.log  main;

  sendfile        on;
  #tcp_nopush     on;

  keepalive_timeout  65;

  client_body_buffer_size 32K;
  client_max_body_size 10M;

  client_body_timeout 10s;
  client_header_buffer_size 1k;
  large_client_header_buffers 2 16k;
  client_header_timeout 5s;

  gzip on;
  gzip_static on;
  gzip_disable "msie6";
  gzip_vary on;
  gzip_proxied expired no-cache no-store private auth;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json text/javascript application/x-javascript application/javascript text/xml application/xml application/xml+rss application/vnd.groove-tool-template application/octet-stream;

  include /etc/nginx/conf.d/*.conf;
  include /etc/nginx/bots.d/*.conf;
}`
(Equivalent for  /etc/sites-available/yoursite.conf)
`root@web2:/etc/nginx/conf.d# cat 5b49c3735073c91a13cf7d65.conf
server {
  listen 80;

  root /var/www/pma2;
  server_name pma2-www.2e1a7fa72c.at.d2c.io;
  index index.php index.html;
  resolver 172.17.0.1 valid=60s ipv6=off;
  set $backend pma2;
  include conf.d/letsencrypt.inc;
  location ~ /\.git {
 	# Bad Bot Blocker
	include /etc/nginx/bots.d/ddos.conf;
 	include /etc/nginx/bots.d/blockbots.conf;

    deny all;
  }

  try_files $uri $uri/ @rewrite;
  location @rewrite {
    rewrite ^/(.*)$ /index.php?$args;
  }
  location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|pdf|ppt|txt|bmp|rtf|js|json|tpl|ttf|woff|eot|svg)$ {
    access_log off;
    add_header Pragma public;
    add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    expires 30d;
  }
  location ~ \.php$ {
    try_files $fastcgi_script_name =404;
    fastcgi_keep_conn on;
    fastcgi_pass $backend:9000;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }
  location ~ /\.ht {
    deny all;
  }
}`
`root@web2:/etc/nginx/conf.d# ls -la /etc/nginx
total 56
drwxr-xr-x 1 root root 4096 Jul 29 03:48 .
drwxr-xr-x 1 root root 4096 Jul 29 09:59 ..
drwxrwxr-x 2 root root 4096 Jul 29 10:00 bots.d
drwxrwxr-x 3 root root 4096 Jul 29 10:03 conf.d
-rw-r--r-- 1 root root 1007 Jul 24 13:02 fastcgi_params
-rw-r--r-- 1 root root 2837 Jul 24 13:02 koi-utf
-rw-r--r-- 1 root root 2223 Jul 24 13:02 koi-win
-rw-r--r-- 1 root root 5231 Jul 24 13:02 mime.types
lrwxrwxrwx 1 root root   22 Jul 24 13:02 modules -> /usr/lib/nginx/modules
-rw-r--r-- 1 root root 1279 Jul 29 03:47 nginx.conf
-rw-r--r-- 1 root root  636 Jul 24 13:02 scgi_params
-rw-r--r-- 1 root root  664 Jul 24 13:02 uwsgi_params
-rw-r--r-- 1 root root 3610 Jul 24 13:02 win-utf`
`root@web2:/etc/nginx/conf.d# ls -la /etc/nginx/bots.d
total 48
drwxrwxr-x 2 root root 4096 Jul 29 10:00 .
drwxr-xr-x 1 root root 4096 Jul 29 03:48 ..
-rw------- 1 root root 3566 Jul 29 10:00 bad-referrer-words.conf
-rw------- 1 root root 2450 Jul 29 10:00 blacklist-domains.conf
-rw------- 1 root root 5046 Jul 29 10:00 blacklist-ips.conf
-rw------- 1 root root 3318 Jul 29 10:00 blacklist-user-agents.conf
-rw------- 1 root root 2105 Jul 29 10:00 blockbots.conf
-rw------- 1 root root 2638 Jul 29 10:00 custom-bad-referrers.conf
-rw------- 1 root root 1768 Jul 29 10:00 ddos.conf
-rw------- 1 root root 2485 Jul 29 10:00 whitelist-domains.conf
-rw------- 1 root root 1731 Jul 29 10:01 whitelist-ips.conf`
`root@web2:/etc/nginx/conf.d# ls -ls /etc/nginx/conf.d
total 308
  4 -rw-r--r-- 1 root root   2235 Jul 29 10:00 5b49c36d5073c9370fcf7d60.conf
  4 -rw-r--r-- 1 root root    967 Jul 29 10:00 5b49c3735073c91a13cf7d65.conf
  4 -rw------- 1 root root   1832 Jul 29 10:03 botblocker-nginx-settings.conf
  4 -rw-r--r-- 1 root root    910 Jul 29 03:47 cloudflare.conf
284 -rw------- 1 root root 287708 Jul 29 10:00 globalblacklist.conf
  4 -rw-r--r-- 1 root root    169 Jul 29 03:47 letsencrypt.inc
  4 drwxr-xr-x 2 root root   4096 Jul 29 03:48 wordpress`

**Comment by mitchellkrogza** [comment]
You have put the includes into an http {} block... It will not work. The bot blocker includes only go inside server {} blocks.
