### ISSUE TITLE
Fail2ban + Debian

### ISSUE THREAD

**Issue by UiharuKazari2008** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#8]
I am running the latest version of Debian and when i add everything for Fail2Ban it will not start. First it could not understand the nginx logs location and i replaced that with the path to my access logs and now i get bad substitution 

> ● fail2ban.service - LSB: Start/stop fail2ban
>   Loaded: loaded (/etc/init.d/fail2ban)
>   Active: active (exited) since Wed 2017-01-11 19:39:44 UTC; 5min ago
>  Process: 25824 ExecStop=/etc/init.d/fail2ban stop (code=exited, status=0/SUCCESS)
>  Process: 25831 ExecStart=/etc/init.d/fail2ban start (code=exited, status=0/SUCCESS)
>
>Jan 11 19:39:43 ACROSS-LANTIS systemd[1]: Starting LSB: Start/stop fail2ban...
>Jan 11 19:39:44 ACROSS-LANTIS fail2ban[25831]: Starting authentication failure monitor: fail2banERROR  Failed during configuration: Bad value substitution:
>Jan 11 19:39:44 ACROSS-LANTIS fail2ban[25831]: section: [nginxrepeatoffender]
>Jan 11 19:39:44 ACROSS-LANTIS fail2ban[25831]: option : action
>Jan 11 19:39:44 ACROSS-LANTIS fail2ban[25831]: key    : port
>Jan 11 19:39:44 ACROSS-LANTIS fail2ban[25831]: rawval : ", protocol="%(protocol)s", chain="%(chain)s"]
>Jan 11 19:39:44 ACROSS-LANTIS fail2ban[25831]: failed!

**Comment by mitchellkrogza** [comment]
The best way to change your logs location on fail2Ban is to create a paths-common.local or path-debian.local file and then make your changes there like this.
`nginx_error_log = /var/log/nginx/*error.log
nginx_access_log = /var/log/nginx/*access.log`

Then you rather reference log locations in Fail2Ban using their recommended formatting of
`logpath = %(nginx_error_log)s`
or
`logpath = %(nginx_access_log)s`

What version of Fail2Ban are you running?

`sudo fail2ban-client version`

**Comment by mitchellkrogza** [comment]
I just tested the exact files for Fail2Ban in this repo on a brand new Ubuntu 16.04 test bench with Fail2Ban 0.9.3 and it starts first time. Might be your Fail2Ban version which I recommend you consider moving to the 0.9.3 branch as your repo branch is probably at 0.8.x

**Comment by UiharuKazari2008** [comment]
I didn't know that the versions were that different, I purged the old version and installed 0.9.X via a deb file
It looks to work now

**Comment by mitchellkrogza** [comment]
Great glad you got it working, yes 0.8.x branch is very old indeed and has lots of new features missing. I'm busy testing 0.10 branch myself and will probably move to that soon.

**Comment by mitchellkrogza** [comment]
also have a look at the new nginx-limit-req filter in 0.9 branch, works great for blocking wp-login brute force attempts. You set a rate limiting zone in nginx for wp-login called "wp-login" and then you configure the nginx-limit-req to scan the nginx error logs for that zone. Works like a charm.
