### ISSUE TITLE
setup-ngxblocker (not modifying globalblacklist.conf includes custom location)

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#81]
Hi @itoffshore tested with latest setup-ngxblocker, it does the includes correctly when specifying the `-b` and `-c` command line switched but it is not re-writing the globalblacklist.conf file to the non standard locations specified. I was so sure we had this working in an earlier release? Am I going mad or is there an issue here?

```
./setup-ngxblocker -c /etc/nginx/conf2.d -b /etc/nginx/bots2.d -x
Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt

inserting: include /etc/nginx/conf2.d/globalblacklist.conf;            => /etc/nginx/nginx.conf
inserting: include /etc/nginx/conf2.d/botblocker-nginx-settings.conf;  => /etc/nginx/nginx.conf
inserting: include /etc/nginx/bots2.d/blockbots.conf;                  => /etc/nginx/sites-available/default.vhost
inserting: include /etc/nginx/bots2.d/ddos.conf;                       => /etc/nginx/sites-available/default.vhost

Whitelisting ip:  154.73.152.134  => /etc/nginx/bots2.d/whitelist-ips.conf
```

Then looking in `/etc/nginx/conf2.d/globalblacklist.conf` the includes are still `include /etc/nginx/bots.d/blacklist-user-agents.conf;` and not `include /etc/nginx/bots2.d/blacklist-user-agents.conf;`

But then .... if I manually modify the version number and date in the downloaded globalblacklist.conf file and then run the following:

```
./update-ngxblocker -c /etc/nginx/conf2.d -b /etc/nginx/bots2.d

Update Available => 3.2017.08.848
Downloading: globalblacklist.conf ...OK

Checking url: https://raw.githubusercontent.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/master/include_filelist.txt

Nothing to update for directory: /etc/nginx/conf2.d
Nothing to update for directory: /etc/nginx/bots2.d
Nothing to update for directory: /usr/sbin
Updating bots.d path: /etc/nginx/bots2.d => /etc/nginx/conf2.d/globalblacklist.conf

Reloading NGINX configuration...[OK]
```

then it fixes the includes location correctly. So the updater does it correctly but not the initial setup script.

**Comment by itoffshore** [comment]
OK - `update_paths()` needs to be added to `setup-ngxblocker`

**Comment by mitchellkrogza** [comment]
Awesome, then we'll have this running like a beast 👍
