### ISSUE TITLE
-e command allows only email@domain.com

### ISSUE THREAD

**Issue by saschadd** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#86]
Hi mitchell,

one small issue with the updater script.
The -e command allows only email@domain.com but i have an name.lastname@subdomain.domain.tld emailadress. ;)
Well i can route it through a different mail address but maybe you want to change this.

**Comment by mitchellkrogza** [comment]
@saschadd that's weird, it should allow any email address. I am sure @itoffshore can look into this.

**Comment by mitchellkrogza** [comment]
@saschadd what is your output of `which mail`???

I have 

```which mail
/usr/bin/mail```

And I tested a command line mail like this which works, even though that email address does not exist.

```
mail -s "Hello" mitchell.krog@hosts.ubuntu101.co.za < /var/log/certbot-renew.log
Null message body; hope that's ok```

**Comment by mitchellkrogza** [comment]
@saschadd Okay but testing this 

`/usr/sbin/update-ngxblocker -e mitchell.krog@hosts.ubuntu101.co.za
ERROR: option '-e' argument 'mitchell.krog@hosts.ubuntu101.co.za' requires: email@domain.com`

Gives an error @itoffshore

**Comment by mitchellkrogza** [comment]
@saschadd please pull latest update-ngxblocker and test. Thanks @itoffshore for the quick fix

**Comment by mitchellkrogza** [comment]
@saschadd latest updates by @itoffshore now merged into main repo.

**Comment by jeremyj** [comment]
Hello,
I'm still having issues with this.
grep: Invalid range end
ERROR: option '-e' argument xxx requires: email@domain.com
Using Ubuntu 16.04 and latest BBB
The thing is on certain systems it works on others it doesn't. Can't seem to pin down the problem.
Any clues?

**Comment by itoffshore** [comment]
@jeremyj - let me know if the following fixes it on line `177`:

` email)   if ! echo $arg | grep -E ^[-\._[:alnum:]]+@[-\._[:alnum:]]+[\.a-z]+ 1>/dev/null; then`

or being extra safe:

` email)   if ! echo $arg | grep -E ^[\-\._[:alnum:]]+@[\-\._[:alnum:]]+[\.a-z]+ 1>/dev/null; then` 

(but I think the first should fix it)

**Comment by jeremyj** [comment]
@itoffshore not sure if you made a type but on version `3.2018.04.1091` your changes are on line `188`.
Anyhow, your first edit seems to work fine.
Also, as a workaround using `-m` worked too without your edit.
Thanks
