### ISSUE TITLE
Blocking my test request, but not actual bot request

### ISSUE THREAD

**Issue by benburleson** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#90]
```
<botIpAddress> - - [07/Sep/2017:20:23:08 +0000] "HEAD /phpmyadmin2018/ HTTP/1.1" 301 0 "-" "Mozilla/5.0 Jorgee" "<botIpAddress>"
<myIpAddress> - - [07/Sep/2017:20:23:20 +0000] "HEAD /phpmyadmin2018/ HTTP/1.1" 444 0 "-" "Mozilla/5.0 Jorgee"
```

Hi all, I'm a bit confused here. I set up blocking, ran a test with curl which was blocked, so I thought I was good to go. But then I noticed actual bot requests are getting a 301 response, not the expected 444 response. See above, actual bot request is first, my test curl request is second.

I can't figure out why these would be treated different. My `whitelist-ips.conf` is currently default with one line `111.111.111.111 0;`. Any ideas of what the difference is or how I can go about debugging this?

Let me know if more info will be helpful. Thanks!

**Comment by mitchellkrogza** [comment]
@benburleson please can you post the contents of your vhost config.

**Comment by benburleson** [comment]
Hi @mitchellkrogza , here's the `server` section. Thanks for your help!

```
server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  <myDomain.com>;
    root         /var/www/html/web/;
    index        app.php;
    add_header   X-Frame-Options "SAMEORIGIN";

    error_log    /var/log/nginx/error.log;
    access_log   /var/log/nginx/access.log;

    include /etc/nginx/bots.d/blockbots.conf;
    include /etc/nginx/bots.d/ddos.conf;

    location ~ ^/status$ {
        access_log off;
        allow 127.0.0.1;
        deny all;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000;
    }

    location ~ ^/nginx_status$ {
        stub_status on;
        access_log   off;
        allow 127.0.0.1;
        deny all;
    }

    location / {
        try_files $uri $uri/ /app.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_intercept_errors on;
        fastcgi_index app.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 600;
    }
}
```

**Comment by mitchellkrogza** [comment]
Thanks @benburleson are you only using http not https ?? Can you please email me your real domain name off list to mitchellkrog@gmail.com

**Comment by mitchellkrogza** [comment]
Can you also paste the contents of `ls -la /your/web/root/phpmyadmin2018/`

**Comment by benburleson** [comment]
Hi @mitchellkrogza , I replied via email and will post other details here:

It's an EC2 instance behind an ELB. The ELB proxies https requests to http which is sent to the EC2 instance, so that is actually running only http on port 80.

`/phpmyadmin2018/` does not actually exist, it's a path the bot is hoping to find some vulnerability.

**Comment by benburleson** [comment]
It turns out this was all because I had another server block acting as the default server, and the bot was making requests with an IP address, not a domain name. I didn't notice this before, but found out by looking at the ELB logs. Those requests were getting a 301 response from the default server block, while my requests were going to the expected server block and getting a 444 response.

Thanks @mitchellkrogza for your help debugging this!

**Comment by mitchellkrogza** [comment]
Thanks for the feedback @benburleson glad you got it working finally.
