### ISSUE TITLE
Use on Vesta?

### ISSUE THREAD

**Issue by kronflux** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#94]
Good morning!

I'm wondering if anyone has any insights on how this might be installed alongside VestaCP?
It seems VestaCP installs nginx in a different configuration than standard(stores multiple files used by it in alternate locations)

I managed to get it working once a while back using a VM, but I no longer have that VM for reference, and I can't seem to reproduce my results.

**Comment by mitchellkrogza** [comment]
@kronflux you need to configure your own custom template for Nginx this might help you, https://forum.vestacp.com/viewtopic.php?t=9714

**Comment by kronflux** [comment]
ah, alright, that pointed me enough in the right direction :) thanks!

Basically, install as per usual up until adding the include lines to the vhosts, then add those lines to the vesta templates.
After that, simply rebuild web from the control panel and voila!

Thanks again :+1:

**Comment by mitchellkrogza** [comment]
No problem, please report back once you get it sorted. Good to have this info here for other users in the future who may also be using VestaCP.

**Comment by kronflux** [comment]
yep! working perfectly on my live server. all sorted!

Would it be pointless to also include the robots.txt? or would this cause a conflict? I was thinking redundancy is usually not a bad thing.

Also, I noticed VestaCP adds the line "Crawl-delay: 10" to the robots.txt, which apparently limits the time between certain crawl bots indexing your site.
Could be worth adding to the robots.txt in nginx-ultimate-bad-bot-blocker just as a minor additional layer of protection. I doubt that most bad bots would respect it, but it couldn't hurt.
Just a thought! :)

**Comment by mitchellkrogza** [comment]
Awesome, that's great to hear. Yes indeed, no need for robots.txt at all, the blocker does a much better job of blocking bots than any robots.txt file could do. That's only for people who cannot use the blocker. 

Thank for that info on `Crawl-delay: 10` will add it in next commit.

Remember the blocker does it's own rate limiting and DDOS prevention so depending what CMS you are using you can alway tweak this section of the botblocker-nginx-settings.conf file. These settings which are the default are tweaked for Wordpress sites which require a lot of calls for loading just one page.

Enjoy it and thanks for feeding back to me. You will start to see the great benefits of the blocker in the weeks and months ahead. Make sure you setup the update-ngxblocker as per the instructions to make sure you are always up to date with the latest emerging threats.
 👍 

Closing.

**Comment by mitchellkrogza** [comment]
Oh yes and as per my recommendations monitor your logs daily.
