### ISSUE TITLE
WARN: missing /usr/bin/mail => disabling emails

### ISSUE THREAD

**Issue by djeraseit** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#97]
On CentOS mail is installed in /bin/mail

Update script should check that location as well.
Also, consider not using -e for email since it is used in another script to specify extension (i.e. my extensions are .conf like apache ).

Excellent software!

**Comment by itoffshore** [comment]
@djeraseit - I added detection for `/bin/mail` but left the email command line switch as `-e` so as not to break any existing cron scripts

**Comment by itoffshore** [comment]
@djeraseit  - I've added a `-m` command line switch to specify an email address in the latest `PR` (`-e` still works too so not to break existing `cron` jobs)
